### ISSUE TITLE
Inefficient thread utilization

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#11]
If the `Executor` of the evolution `Engine` is set to a different value than a `ForkJoinPool`, the thread utilization is far below then expected. Setting the executor to a fixed thread pool,
```java
Engine
    .builder(knapsack.function(), knapsack.genotype())
    .populationSize(150)
    .survivorsSelector(new TournamentSelector<>(5))
    .offspringSelector(new RouletteWheelSelector<>())
    .alterers(
        new Mutator<>(0.03),
        new SinglePointCrossover<>(0.125))
    .executor(Executors.newFixedThreadPool(6))
    .build();
```
the threads will be created, but not fully utilized.
![htop](https://cloud.githubusercontent.com/assets/1509203/6604750/015e9d9c-c82b-11e4-8ac4-b6c96d89f1d2.png)

On the other hand, if you set the executor to `new ForkJoinPool(1)`, all of the cores are busy.

**Comment by jenetics** [comment]
First tests couldn't reproduce the error: https://github.com/jenetics/jenetics/commit/c4779ce6d4cb553624718903fb0a97259bb0d64b

**Comment by jenetics** [comment]
Not reproducible.

**Comment by iirekm** [comment]
Maybe this issue depends on specific use. Even now in 2017 I get only 50-60% use of my CPU cores. Maybe the threads exchange data too often? I would reduce the data exchanges between threads (something like allopatiric evolution in the nature).
