### ISSUE TITLE
Example to use different IntegerGene in an IntegerChromosome

### ISSUE THREAD

**Issue by agantz** [jenetics/jenetics#110]
Hi my world (population) the IntegerChromosome should be consist from different IntegerGene each one has different min and max.
In the example I created the IntegerChromosome takes the min and max only from the first Gene

What is the correct way to fix that?

        public class HelloWorld {
	private static Integer eval(final Genotype<IntegerGene> gt) {
		IntegerChromosome chromo = (IntegerChromosome) gt.getChromosome();
		return chromo.stream().mapToInt(i-> i.getAllele()).sum();		 
	 }
	
	public static void main(String[] args) {

		IntegerGene[] genes = new IntegerGene[5];
		genes[0] = IntegerGene.of(1,5);
		genes[1] = IntegerGene.of(1,9);
		genes[2] = IntegerGene.of(1,15);
		genes[3] = IntegerGene.of(1,7);
		genes[4] = IntegerGene.of(1,2);
		final Factory<Genotype<IntegerGene>> gft = 
                          Genotype.of(IntegerChromosome.of(genes[0], genes[1], genes[2], genes[3], genes[4]));
				
			
		final Engine<IntegerGene, Integer> engine = Engine.builder(HelloWorld::eval, gft).build();
		
		// 4. start execution
		final Genotype<IntegerGene> result =                   
                                     engine.stream().limit(100).collect(EvolutionResult.toBestGenotype());
		

		System.out.println("Hello World: \n \t" + result);
		System.out.println("eval: \n \t" + HelloWorld.eval(result));

	}

**output**:

Hello World: 
 	[[[5],[5],[5],[5],[5]],[[3],[1],[5],[1],[4]],[[4],[4],[5],[3],[5]],[[3],[5],[4],[3],[2]],[[3],[5],[1],[5],[3]]]
eval: 
 	25

**Comment by jenetics** [comment]
You can't use different constraints within one chromosome. Jenetics assumes that the every gene of one chromosome has the same constraint (min-max value). The algorithm takes the min-max values from the first gene.

You have to create a genotype with 5 chromosomes of length 1. This allows you to define different min-max values.

```java
public class HelloWorld {
    private static int eval(final Genotype<IntegerGene> gt) {
        return gt.stream().mapToInt(ch -> ch.getGene().intValue()).sum();
    }

    private static Factory<Genotype<IntegerGene>> gtf = Genotype.of(
         IntegerChromosome.of(1, 5),
         IntegerChromosome.of(1, 9),
         IntegerChromosome.of(1, 15),
         IntegerChromosome.of(1, 7),
         IntegerChromosome.of(1, 2)
    );
}
```

**Comment by agantz** [comment]
Thank you for the quick answer I check and indeed it worked.I have 2 additional questions:
1. Can yo u advise why it was design like this, my assumption was that each gene is independent and can has his own mutation and transformation.Can I override and have the genes determine the solution?2. I am planing to use statistical breeding (cross entropy) in my implementations, Is there an example I can see as a reference.
10xAssaf



Date: Mon, 16 May 2016 10:39:23 -0700

**Comment by jenetics** [comment]
The chromosomes within a genotype are independently altered and _not_ the genes within a chromosome. If you could define different ranges within one _numeric_ chromosome, the `SwapMutator` would happily destroy your constraints. Since all alterers will work on _one_ chromosome, this will not happen in the current design. The Java type-system is used to prevent most of the possible miss-configurations of the evolution `Engine`.

In my opinion, it is not necessary to encode your problem in one chromosome. Every chromosome contains only one gene, so you can treat the 5 `IntegerChromosome`s of length 1 as transposition of your single `IntegerChromosome` of length 5.

**Comment by doctorpangloss** [comment]
I ran into this problem, maybe you should throw an exception if users set different ranges on different genes?

**Comment by jenetics** [comment]
@doctorpangloss you are right, I should do a precondition check for these factory methods instead of ignoring it silently. I created #443 for this.
