### ISSUE TITLE
Speciating and/or extending Population

### ISSUE THREAD

**Issue by Alex-Cosma** [jenetics/jenetics#117]
Hello!

I would like to add speciation in an implementation. Basically, I would treat newly mutated individuals differently based on what species that end up into, all according to some logic which I will define. Once a mutation occurs, I would like to compare that individual's traits with one random individual from all different species to see which one it is closest to. If the distance is too far, I create a new species and add this particular individual to that species.

I think this would be easily done by extending the `Population` class, so my question is, is there any way to do this? 
Or better yet, could you maybe point me in another (better) direction?
Oh and another detail to add here is that within a species, individuals should share their fitness (explicit fitness sharing), so I'm guessing this has to be placed in a different container? Not sure..

Much obliged!

**Comment by jenetics** [comment]
I'm not sure what you are trying to achieve. But I guess the right way to implement it is via the `Alterer` interface. An implementation via the `Population` would bypass the GA implementation of the `Engine`.

```java
public class DelegateAlterer<
	G extends Gene<?, G>,
	C extends Comparable<? super C>
>
	implements Alterer<G, C>
{
	private final Alterer<G, C> _delegate;
	public DelegateAlterer(final Alterer<G, C> delegate) {
		_delegate = requireNonNull(delegate);
	}

	@Override
	public int alter(final Population<G, C> population, final long generation) {
		final int count = _delegate.alter(population, generation);

		for (int i = 0; i < population.size(); ++i) {
			final Phenotype<G, C> pt = population.get(i);

			// This condition means, that this PT has been changed by the
			// given alterer.
			if (pt.getGeneration() == generation) {
				// Do something with the PT and change the Population.
			}
		}

		return count;
	}
}
```

With the given alterer you can manipulate the population after it has been altered. Seems to be the cleanest way in implementing your _algorithm_.

**Comment by Alex-Cosma** [comment]
I think that you idea *might* work, but I am unsure. Let me make it a tad more clear as to what I want to achieve.

I am trying to evolve a neural network. Now one of the issues of neuroevolution is crossing-over two individuals which contain incompatible structure. You might now about this problem but if you do not, it is called "Competing conventions problem".
Here is a diagram to showcase what might happen:

![Competing conventions problem](http://image.prntscr.com/image/dc0881de8a2b4a7ca756dc6008c5e3fb.png)

I am quoting an article which can be easily found [here](http://nn.cs.utexas.edu/downloads/papers/stanley.ec02.pdf) so I am only trying to implement the things in it.

Now what they propose in this article is to keep track of *when* exactly a new node OR connection between two nodes appears (by mutation) in individuals, such that structural incompatibilities which might make crossing-overs yield damaged individuals can be detected easily. Whenever such a mutation occurs, a 'global innovation number' is incremented and assigned to that gene. The innovation numbers represent a chronology of the appearance of every gene in the system.
Using such a notation, structural differences between networks ("how different a network is from another") can be very easily computed without any topological analysis. This leads to *grouping by species*. Basically, individuals with similar structure (very small structural difference) can be grouped into a species such that they compete with only individuals *from that species*. Besides this, individuals from a specific species are assigned an explicit fitness value such that a species cannot afford to become too big even if many of its organisms perform well. 

So, with all this explained, do you think it can be done?
