### ISSUE TITLE
Mutate genes seq / chromosome by adding a gene

### ISSUE THREAD

**Issue by Alex-Cosma** [jenetics/jenetics#118]
Hello,

I want to mutate a chromosome by adding (or removing) a gene to it. Is that possible in any way? 
I tried to basically override the whole `Mutator` class and create a `CustomMutator` class of my own, but I then cannot access the `newInstamce( ... )` method from:
` return genotype.newInstance(chromosomes.toISeq()); ` 

Is there any workaround this?

**Comment by jenetics** [comment]
You can safely use the `Genotype.of(Iterable)` method. The `newInstance` method is used internally and is optimized for chromosome with the same number of genes.

**Comment by Alex-Cosma** [comment]
You are perfectly right! Thank you for your awesomely quick answer.

As a really small suggestion, might I suggest that you make both
```
 private Genotype<G> mutate(Genotype<G> genotype, double p, IntRef alterations)
```
and 
```
 private int mutate(MSeq<Chromosome<G>> c, int i, double p)
```
protected? Maybe someone else will have to deal with a similar problem such as mine (add/remove genes from a chromosome at mutation level) and then that person will have to alter the second method, which he/she won't be able to do as it is private now. 

Many thanks again!

**Comment by jenetics** [comment]
@Alex-Cosma I thought about your suggestion and created a follow-up  (#121) for making the `Mutator` class easier extendable.
