### ISSUE TITLE
Typo in user manual

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#12]
Section 5.1
Search for: "The customer Genes and Chromosomes"
Replace "customer" by "custom"

**Comment by cowwoc** [comment]
Section 6.1.1
Search for: "non of the Crossover"
Replace "non" with "none"

**Comment by cowwoc** [comment]
Section 6.1.1
Search for: "altererd by"
Replace "altererd" by "altered"

**Comment by jenetics** [comment]
Thank you, it seems you are the first who reads the manual ;-)

**Comment by cowwoc** [comment]
The manual is quite excellent. Thank you very much for writing it.

I will let you know if I catch any other typos.

**Comment by jenetics** [comment]
Releasing 3.1.
