### ISSUE TITLE
Change Maven group ID to 'io.jenetics'

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#127]
Changing the group ID for the Maven artifacts from `org.bitbucket.fwilhelm` to `io.jenetics`. Also change the artifact ID.
- Base module: `io.jenetics:jenetics:4.0.0`
- Random module: `io.jenetics:jenetics-random:4.0.0`

**Comment by ashata** [comment]
How do I contribute to this project? I have no experience in jenetics and would LOVE to learn. I'm a good Java and Spring developer with basic front end skills. I have good knowledge of maven and I'm learning Gradle

**Comment by jenetics** [comment]
Hi, @ashata, thank you for your interest in this project. There are no big hurdles for contributing to the library. In general it is sufficient to create a [pull-request](https://help.github.com/articles/about-pull-requests/) (against the master branch) with your changes. This will then the place where we can discuss the changes. If the changes are useful and fit into the overall structure, they will be part of the next release.
If you are planning bigger changes, its a good idea to create an [issue](https://help.github.com/articles/discussing-project-details-in-issues-and-pull-requests/) first. This gives us the opportunity to clarify things which are still unclear and define where and how the changes should be implemented.
There are no written down coding styles. Good documentation and a clear structure are required. (But this is discussed best with a concrete pull-request.)

I hope this will help you getting started and I'm looking forward for your contribution.

Regards,
Franz

**Comment by jenetics** [comment]
Goup ID has been changed.

https://issues.sonatype.org/browse/OSSRH-26954
