### ISSUE TITLE
Elitism?

### ISSUE THREAD

**Issue by DiAvisoo** [jenetics/jenetics#128]
I've been running some tests here and wanted to add elitism but couldn't find a pre-defined setting for this? (always keep the best n individuals for every generation)

Is it just me not seeing it?

**Comment by jenetics** [comment]
The elitism is built into the evolution `Engine`. If you use the engine as expected,
```java
final Engine<DoubleGene, Double> engine = ...;
final EvolutionResult<DoubleGene, Double> result = engine.stream()
    .limit(100)
    .collect(EvolutionResult.toBestEvolutionResult());
```

the `EvolutionResult.toBestEvolutionResult` collector will always return the *best* `EvolutionResult` found while evaluating the stream. No need for an elitism selector, or a similar thing. The reason for this is, that (for me) it doesn't make sense to throw away the best solution found so far.

It's documented in the Javadoc of the `EvolutionResult.toBestEvolutionResult` method: "Return a collector which collects the best result of an evolution stream."

**Comment by DiAvisoo** [comment]
Got it, thank you 👍
