### ISSUE TITLE
View state of evolution after each iteration

### ISSUE THREAD

**Issue by wnyffenegger** [jenetics/jenetics#130]
I want to evolve large numbers on individuals; but, after each evolution I want to run analysis on each of those individuals. From what I've seen, once engine.stream() is called, there is no stopping until every iteration has run.

Is it possible to pull the whole population after each iteration of evolution?

**Comment by jenetics** [comment]
You can easily do this with the `Stream.peek` method.
```java
void run() {
    final Engine<DoubleGene, Double> engine = ...;
    final Phenotype<DoubleGene, Double> engine.stream()
        .limit(100)
        .peek(this::inspect)
        .collecto(toBestPhenotype());
}
void inspect(final EvolutionResult<DoubleGene, Double> interimResult) {
    final Population<DoubleGene, Double> pop = interimResult.getPopulation();
    System.out.println(pop);
}
```
The `peek` method calls the `inspect` method for every iteration, where you can access the current population with `EvolutionResult.getPopulation`.
