### ISSUE TITLE
Compiling in Eclipse

### ISSUE THREAD

**Issue by monospacesoftware** [jenetics/jenetics#131]
I am attempting to import the entire project into Eclipse. I pulled from GitHub, ran a gradlew jar (which appeared to succeed), and gradlew eclipse. But Eclipse reports many errors in the code and refuses to build the project. I suspect it's due to differences between the Eclipse compiler and javac. Most of the problems are related to generic type inference and conversion. I've put the problem list here: https://gist.github.com/monospacesoftware/1774eb3470014ca7a41bac269a9fb038

**Comment by jenetics** [comment]
Yes, thats a problem of Eclipse. I'm developing the library with IntelliJ, which can compile the current code without errors. But even IntelliJ sometimes reports false errors. The continuous builds with [Shippable](https://app.shippable.com) also doesn't report this Eclipse compile errors. To keep the testing effort as small as possible, I decided to only trust the Java compiler and see it as a bug of the IDEs.

Another Eclipse compiler problem: #9

**Comment by monospacesoftware** [comment]
Thanks.  For what it's worth, there are far less Eclipse issues in branch r3.6.0.  Only 1 actually, in CompositeCodec line 67 "Incompatible conditional operand types Factory<Genotype<G>> and Genotype<?>".  Which appears can be worked around by removing the <?>.
