### ISSUE TITLE
Finding differentiated fit Genotypes

### ISSUE THREAD

**Issue by monospacesoftware** [jenetics/jenetics#132]
I'm interested in finding differing fit individuals.  In other words, Genotypes that are highly fit, but not necessarily the fittest, and more than a given percentage different than other fit individuals, based on the makeup of their genes. Can  you suggest an efficient way to accomplish this?  BTW thank you for this library, I'm finding it useful and very well written and documented.

**Comment by jenetics** [comment]
I'm not sure if I understand your question. Do you want to write a new, special `Selector`?
