### ISSUE TITLE
Interfaces should not implement Serializable

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#14]
According to Effective Java 2nd edition, classes meant for subclassing (including interfaces) should not implement `Serializable`. The book provides a long list of reasons which I will not repeat here (if you don't have access to the book, let me know and I'll figure something out)

Instead of declaring `implements Serializable` on classes like `Gene`, consider moving this down to the concrete classes that are not meant to be subclassed.

**Comment by jenetics** [comment]
Good point, thank you for the reminder.

**Comment by jenetics** [comment]
Fixed, see pull request #15
