### ISSUE TITLE
Invalid Javadoc for class Engine

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#16]
The Javadoc for class Engine renders fine at http://jenetics.io/javadoc/org.jenetics/org/jenetics/engine/Engine.html but if you try viewing it using an IDE (using Netbeans in my case, but I believe other IDEs would be the same) the code block and newlines don't render correctly.

I believe all you need to do is replace `[code]` with `{@code}` and replace newlines with `<p>`.

**Comment by cowwoc** [comment]
Also, please add `@param` tags explaining the meaning of the two type parameters: `G` and `C`.

**Comment by jenetics** [comment]
I'm using a customized version of the `colapi` library (http://mvnrepository.com/artifact/org.javolution/colapi/2.0) used by the Javolution (http://javolution.org/) project for rendering the `[code]` tags. The default javadoc rendering for code blocks have no keyword highlighting.

**Comment by jenetics** [comment]
Adding type parameter documenation should be no problem.

**Comment by cowwoc** [comment]
I understand, but how do we handle the fact that the resulting Javadoc is not usable by IDEs?

Is there a way to transform normal Javadoc to the former expected by `colapi` at build-time as opposed to using this format directly in the source-code?

**Comment by jenetics** [comment]
I considered this as a minor problem, because it is still possible to create a valid javadoc with `./gradlew javadoc`. By the way, it seems that surrounding the `[code]` block by a `<pre></pre>` pair might be a viable workaround.

**Comment by jenetics** [comment]
Replaced special code tags with '<pre>{@code' and '}</pre>'.
