### ISSUE TITLE
Allow Genotype with different Chromosome types

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#165]
Currently a `Genotype` can only consist of `Chromosome` of the same type.
```java
final Genotype<DoubleGene> gt = Genotype.of(
    DoubleChromosome.of(1.0, 2.0, 10),
    DoubleChromosome.of(2.0, 3.0, 15)
);
```

It should be possible to create genotypes of heterogeneous chromosomes, create an `Engine` and solve a given problem.
```java
final Genotype<NumericGene> gt = Genotype.of(
    DoubleChromosome.of(1.0, 2.0, 10),
    IntegerChromosome.of(0, 10, 15)
);

final Engine<NumericGene, Double> engine = ...;
final Genotype<NumericGene> result = engine.stream()
    .limit(10)
    .collect(EvolutionResult.toBestGenotype());
```

**Comment by ipsq** [comment]
Any update on this?

**Comment by jenetics** [comment]
Currently no update on this issue. As a work around, you still have to use raw-types. Have a look at the [MixedGenotype](https://github.com/jenetics/jenetics/blob/master/org.jenetics.example/src/main/java/org/jenetics/example/MixedGenotype.java) example.

**Comment by ipsq** [comment]
Thanks, hadn't thought of simple casting. I can only think of a solution for this problem, that would be type-safe, in scala. I don't think this is possible in Java since you need a HList of some sort.

**Comment by jenetics** [comment]
After some experiments I think it's not possible with the current `Gene` type structure. To have a heterogeneous `Genotype`, I need a common (denotable) `Gene` base type. Since it is possible to define 
```java
Gene<Integer, ?> gene = ...;
``` 
it is not possible to write
```java
Genotype<Gene<Integer, ?>> gt = ...; // will not compile
Genotype<? extends Gene<Integer, ?>> gt = ...; // will compile
```
But the compilable Genotype definition doesn't work with the existing `Engine` and `EvolutionStream` methods. Also the `EvolutionResult.toBestGenotype` collectors doesn't compile with this kind of genotypes.

After all, I think heterogeneous `Genotype`s are only possible using Java raw-types.

**Comment by jenetics** [comment]
After thinking about this, I concluded that this feature is not possible. As a work-around, we have to use raw-types instead.
