### ISSUE TITLE
Different Alterers for each Chromosome

### ISSUE THREAD

**Issue by lfbrito** [jenetics/jenetics#166]
According to what I could see, once we select a type of crossover (for example PMX) it will be applied across the same-sized set of Chromosomes of the Genotype.

This means that, for example, we can not apply PMX on the first Chromosome and Single-Point Crossover on the second Chromosome of the same Genotype, correct?

**Comment by jenetics** [comment]
No, that's currently not possible. A redesign of the `Alterer` interface would be necessary for implementing this. But this is not planned in the near future.
