### ISSUE TITLE
how to find two optimal parameters with jenetics ?

### ISSUE THREAD

**Issue by ZUOJIANYI** [jenetics/jenetics#167]

**Comment by ZUOJIANYI** [comment]
here the code, can anyone help me? thanks
`
public double fitness(double C, double gamma) {

        problem = scaler.scale(runoff, rain, evap, rbye, rde, doub_rain, doub_evap, doub_rainbye, doub_evapbyr, triple_rain, triple_evap);
        param.svm_type = SvmParameter.EPSILON_SVR;
        param.kernel_type = SvmParameter.RBF;
        param.cache_size = 500;
        param.eps = 0.01;
        param.C = Math.pow(2,C);
        param.gamma = Math.pow(2,gamma);


        CrossValidation cv = new CrossValidation();
        cv.doCrossValidation(problem,param,5);

        return cv.getCVSCC();
    }
public void testGA(){

        final Engine<DoubleGene,Double> engine = Engine
                .builder(GetMonthDataForQPE::fitness,
                        codecs.ofScalar(DoubleRange.of(-8.0,8.0)),codecs.ofScalar(DoubleRange.of(-8.0,8.0)))
                .populationSize(500)
                .optimize(Optimize.MAXIMUM)
                .alterers(
                        new Mutator<>(0.03),
                        new MeanAlterer(0.6)
                )
                .build();


        // Create evolution statistics consumer.
        final EvolutionStatistics<Double, ?>
                statistics = EvolutionStatistics.ofNumber();

        final Phenotype<DoubleGene, Double> best = engine.stream()
                // Truncate the evolution stream after 7 "steady"
                // generations.
                .limit(bySteadyFitness(7))
                // The evolution will stop after maximal 100
                // generations.
                .limit(100)
                // Update the evaluation statistics after
                // each generation
                .peek(statistics)
                // Collect (reduce) the evolution stream to
                // its best phenotype.
                .collect(toBestPhenotype());

        System.out.println(statistics);
        System.out.println(best);

    }
`

**Comment by ZUOJIANYI** [comment]
In the mthond 'testGA', i got the error with Engine.builder:
Cannot resolve method 'builder(<method reference>, org.jenetics.engine.Codec<java.lang.Double,org.jenetics.DoubleGene>, org.jenetics.engine.Codec<java.lang.Double,org.jenetics.DoubleGene>)'

**Comment by jenetics** [comment]
The main problem with your code was, that the fitness function can only take one parameter. If you want to have more, you have to *wrap* it into an array:
```java
static double fitness(final double[] params) {
    final double C = params[0];
    final double gamma = params[1];

    // Your fitness calculation.
    return C + gamma;
}
```

The fixed program would look like this:
```java
public class GetMonthDataForQPE {

    static double fitness(final double[] params) {
        final double C = params[0];
        final double gamma = params[1];
    
        // Your fitness calculation.
        return C + gamma;
    }

    public static void main(final String[] args) {
        codecs.ofVector(DoubleRange.of(-8.0, 8.0), 2);

        final Engine<DoubleGene, Double> engine = Engine
            .builder(
                GetMonthDataForQPE::fitness,
                codecs.ofVector(DoubleRange.of(-8.0, 8.0), 2))
            .populationSize(500)
            .optimize(Optimize.MAXIMUM)
            .alterers(
                    new Mutator<>(0.03),
                    new MeanAlterer<>(0.6)
                )
            .build();


        // Create evolution statistics consumer.
        final EvolutionStatistics<Double, ?>
            statistics = EvolutionStatistics.ofNumber();

        final Phenotype<DoubleGene, Double> best = engine.stream()
            .limit(bySteadyFitness(7))
            .limit(100)
            .peek(statistics)
            .collect(toBestPhenotype());

        System.out.println(statistics);
        System.out.println(best);
    }

}
```
