### ISSUE TITLE
Recombination with different Chromosome length

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#17]
I don't understand what the user manual means when it says "Because of the possible different Chromosome length and/or Chromosome constraints within a Genotype, only Chromosomes with the same Genotype position are recombined."

Can you please provide a visual example demonstrating when recombination may or may not take place?

**Comment by jenetics** [comment]
![genotypechromosomerecombination](https://cloud.githubusercontent.com/assets/1509203/6923868/ba63f018-d7d4-11e4-8822-6744da587c26.png)

If this diagram makes it clearer, I will add a similar one to the manual.

**Comment by cowwoc** [comment]
Okay, so you seem to be implying that all Genotypes must contain the same Chromosome type at the same position. I assumed that each Genotype (even different instances of the same Genotype) could contain Chromosomes in different order.

If you were to clarify this point about Chromosome ordering then the original paragraph would make sense as-is.

**Comment by jenetics** [comment]
Improved description in manual.
