### ISSUE TITLE
How to model problems with a deep hierarchy?

### ISSUE THREAD

**Issue by cowwoc** [jenetics/jenetics#18]
I couldn't find a mailing list for jenetics, nor am I sure that is the best place to ask such questions (versus say Stackoverflow).

I'm trying to figure out how to model a scenario where there are more levels of hierarchy in the problem set than the hierarchy provided by jenerics. Example:

* I've got a population of individuals.
* Each individual lives 30-100 years (the length is only known at runtime, and differs between individuals).
* Each year, the individual carries out 0 to X different operations (example: buy or sell stocks).
* Each operation may buy or sell multiple stocks at once.
* There are different types of stocks.

So we've got multiple individuals, each individual has multiple years, each year has multiple operations, each operation operates on one or more stocks.

It's not clear how to model this information in the context of a population, phenotype, genotype, chromosome and gene.

Second problem:

Mutation and crossover are highly likely to fail to produce a valid individual. This is because modifying an individual's state at any given year depends heavily on the operations that occurred in previous and subsequent years. An individual can only sell 100 units of stock X if he purchased those units in previous years. Similarly, selling all shares of stock X at year 10 might invalidate year 11's state because it originally sold shares of stock X (which the individual no longer owns).

I still want mutation and crossover to take place, but I'm concerned about the fact that 99% of attempts will fail which will substantially increase the cost of a successful operation.

Any ideas?

**Comment by cowwoc** [comment]
I took a moment to review the WatchMaker framework, which I've used in the past and I noticed that they chose to omit the definition of a Chromosome or a Gene, letting the user decide the type of each "candidate": http://watchmaker.uncommons.org/api/index.html

For example, `EvolutionaryOperator` operates on type `T` which may be a chromosome or any arbitrary concept the user comes up with.

This is more flexible than the model Jenetics provides and, to a certain degree, makes it easier to model problems in terms of the API. I'm genuinely hoping that you can model the above problem in terms of Jenetics' existing API, but if that's not possible then I'd propose to modify the API to do the same as Watchmaker (allow users to operate on arbitrary types, `Chromosome` being the common choice).

**Comment by jenetics** [comment]
I'm not sure if I understand your problem correctly. But its true, Jenetics has its limitations now. I tried to choose a sane balance between simplicity and flexibility. Witht the existing classes it is possible to model 2-dimensional problems (no hierarchy).

Having a look at your given WatchMaker example, I think the `ColouredPoligon` would be a `Gene` in the Jenetics API and the `MovePolygonMutation` would implement the `Alterer` interface. Then you could create a Jenetics `Engine` in the following way:

```java
final Factory<Genotype<ColouredPolygon>> gtf = 
    Genotype.of(ColouredPolygonChromosome.of(ColouredPolygon.of(...)));
final Function<Genotype<ColouredPolygon>, Double> ff = ...;
Engine<ColouredPolygon, Double> engine = Engine
    .builder(gtf, ff)
    .alterers(new MovePolygonMutation<>(...))
    .build();
```

**Comment by cowwoc** [comment]
I think some more flexibility is warranted.

The immediate problem I am running into is that Crossover:74 assumes that `gt1.length()` is equal or greater than `gt2.length()`, which is not true in my case.

Bigger picture, it would be great if the framework would allow users to specify an arbitrary candidate type (what you call genotype) so we can model something more flexible than the current genotype, chromosome, gene hierarchy. Any chance of that, or will I need to use a different framework for that?

**Comment by jenetics** [comment]
To rephrase it: it would help if the Engine can handle Genotypes with a varying number of Chromosomes, where the Chromosomes also contains a varying number of Genes?

This should be possible in principle. But this would require to check and fix the whole `Alterer` hierarchy. I can' make promises when I would have time to implement it.

**Comment by kennelbound** [comment]
This feature is exactly what I came here looking for.  Being able to create a genotype with multiple chromosomes of different types of genes (i.e. mix bitgene with doublegene in a single chromosome) and then the mutations would only modify some number of the genes if it is selected for alteration.

**Comment by jenetics** [comment]
@kennelbound If you don't mind to loose type safety, you can mix different `Chromosome` types in one `Genotype` by using raw-types:
```java
import java.util.function.Function;

import org.jenetics.BitChromosome;
import org.jenetics.Chromosome;
import org.jenetics.DoubleChromosome;
import org.jenetics.Genotype;
import org.jenetics.IntegerChromosome;
import org.jenetics.Phenotype;
import org.jenetics.engine.Engine;
import org.jenetics.engine.EvolutionResult;

@SuppressWarnings({"raw", "unchecked"})
public class MixedGenotype {

	private static final Genotype ENCODING = Genotype.of(
		(Chromosome)DoubleChromosome.of(0, 4, 5),
		(Chromosome)BitChromosome.of(70),
		(Chromosome)IntegerChromosome.of(0, 10, 3)
	);

	private static double fitness(final Genotype gt) {
		final DoubleChromosome dc = (DoubleChromosome)gt.getChromosome(0);
		final BitChromosome bc = (BitChromosome)gt.getChromosome(1);
		final IntegerChromosome ic = (IntegerChromosome)gt.getChromosome(2);

		return dc.doubleValue() + bc.bitCount() + ic.doubleValue();
	}

	public static void main(final String[] args) {
		final Engine engine = Engine
			.builder((Function<Genotype, Double>)MixedGenotype::fitness, ENCODING)
			.build();

		final Phenotype best = (Phenotype)engine.stream()
			.limit(10)
			.collect(EvolutionResult.toBestPhenotype());

		System.out.println(best);
	}
}
``` 
It's possible, but not the intended library usage.  It's a kind of a hack.

Having dynamic Genotype/Chromosome length is possible if you use a `Factory<Genotype<G>>` instead of the usual `Genotype` template. This will create dynamic `Genotypes` for the initial population and when the `Engine` has to replace old individuals. A `DynamicAlterer` is not part of the library. You have to write it yourself. You might have a look at the simple [DynamicGenotype](https://gist.github.com/jenetics/cb2c2a285a855966ac1de86d34a7b995) example.
