### ISSUE TITLE
Improve CPU utilization for long running fitness functions

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#197]
**Jenetics** is calculating the fitness values for each generation concurrently. The main assumption is, that the calculation of the fitness function is relatively *cheap* and the calculation costs are *constant* for all genotypes. With this assumption in mind, the population is split into *sub*-populations, which group the fitness function into bigger *evaluation units*. This should reduce the evaluation *overhead*. If we have to deal with long-running fitness functions, or with fitness function with *unpredictable* computation costs, the existing computation strategy no longer works as expected. We get *idle* CPU cores. 

This ticket is about to improve the CPU utilization for long-running fitness functions and for fitness functions with *non*-constant evaluation costs.

**See**
#196 

**Hint**
Consider usage of [getSurplusQueuedTaskCount()](http://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ForkJoinTask.html#getSurplusQueuedTaskCount--) method.

```java
@Override
protected void compute() {
	if ((_high - _low) <= 1 || ForkJoinTask.getSurplusQueuedTaskCount() > 3) {
	//if (_high - _low < threshold) {
		for (int i = _low; i < _high; ++i) {
			_runnables.get(i).run();
		}
	} else {
		final int mid = (_low + _high) >>> 1;
		invokeAll(
			new RunnablesAction(_runnables, _low, mid, threshold),
			new RunnablesAction(_runnables, mid, _high, threshold)
		);
	}
}
```

**Comment by dyorgio** [comment]
Hi, where can I get a preview? Do you will create a new branch?
I can test for you :)

**Comment by jenetics** [comment]
Merged into r3.8.0 branch.
