### ISSUE TITLE
Genotype validity

### ISSUE THREAD

**Issue by lfbrito** [jenetics/jenetics#20]
Hi,

I am working the so called Cut Order Planning problem for the textile industry.
I have been doing a couple of trials and I started out by working with the generic IntegerChromosome and Genotype. However, the fact is that, in order to reduce the search space (by removing lots of invalid genotypes) I think I would have to extend Genotype: the overall genotype's validity depend on the multiplication result of each chromosome gene by a factor contained on another chromosome (the bounds of each of genes on each of these chromosomes are also different).
The situation is that Genotype is final. Do you see any other solution for this?

Kind regards,
Luis

**Comment by jenetics** [comment]
I'm aware of this limitation and have thought for a solution for it. One possible solution would be to _override_ the validity check with an `Engine` parameter:

```java
final Predicate<? super Genotype<DoubleGene, Double>> genotypeValidator = ...
final Engine<DoubleGene, Double> engine = Engine.builder(gtf, ff)
    .genotypeValidator(genotypeValidator)
    .build();
```

If no validator is given it would be set to `Genotype::isValid`.

**Comment by lfbrito** [comment]
Hi,

That sounds like a good solution.
But correct me if I am wrong, this hasn’t been implemented yet, right?

Kind regards,
Luis

**Comment by jenetics** [comment]
Yes, I haven't start implementing yet. But it should possible to integrate it into version 3.1, which I plan to release in May.

**Comment by lfbrito** [comment]
Many thanks.
Another situation that this leads to is that, since the chromosomes in the genotype are inter-related, we need to generate a valid population to start with.
The current genotype factory generates random chromosomes based on the bounds of each gene, which leads to invalid individuals on the initial population.  The system will evaluate them as “invalid”, but since there is no defined strategy to create new individuals, any valid substitutes are hard to get with a random procedure.

Is this something you would consider adding to the next release?

PS: congratulations on your great software! :)

**Comment by jenetics** [comment]
Generating only valid Genotypes for a given problem, can be quite challenging. For implementing an more advanced Genotype generation mechanism, you currently have two possibilities:

1.) Create the `Engine` instance with your own Genotype factory (`Factory<Genotype<>>`), which only produces valid Genotypes. Creating new Genotypes from a _template_ is meant as a _convenient_ short-cut.
2.) Implement your own `Gene`/`Chromosome` pair and implement proper `newInstance` factory methods.

It's currently not planned to pull out the factories from the Gene/Chromosome and add it as _pluggable_ strategy.

**Comment by lfbrito** [comment]
Thanks.
I thought about the Genotype factory solution. I will try it out.
