### ISSUE TITLE
Different gene type

### ISSUE THREAD

**Issue by shiivaa** [jenetics/jenetics#206]
how to develop genetic algorithm with chromosomes consist of different gene type?

**Comment by jenetics** [comment]
Do you want to do something like in the [MixedGenotype](https://github.com/jenetics/jenetics/blob/master/org.jenetics.example/src/main/java/org/jenetics/example/MixedGenotype.java) example?

**Comment by shiivaa** [comment]
I want to extend a class to hold genes but every gene of a chromosome might be of different type

**Comment by jenetics** [comment]
So the chromosome holds different instances from `NumberGene`, e.g. `IntGene`, `LongGene` or `DoubleGene`, right? I thought you want to put completely different gene types into a chromosome, like `DoubleGene` and `CharacterGene`. If the chromosome should only contain different number genes, it would be easier to create a `DoubleChromosome` and do the *casting* in the fitness function (`DoubleGene.intValue()`).

What are the arguments of your fitness function?

**Comment by shiivaa** [comment]
thanks for your helpful comment,i agree use the same gene type and casting is better way.i want to apply GA in cloud computing and argument for fitness function relates to cloud .
