### ISSUE TITLE
Repair procedure

### ISSUE THREAD

**Issue by lfbrito** [jenetics/jenetics#22]
Hi,

During the crossover/mutation operators, on our specific problema we might get invalid individuals. I know you are thinking about implementing a validity check at the genotype level for a future version.

However, what would be the best way to implement a repair procedure for the genotype?
During the evaluation procedure itself?

Kind regards,
Luis

**Comment by jenetics** [comment]
The validity check has been implemented and will be part of release 3.1. The repair functionality is not yet planned, but the `PartiallyMatchedCrossover` is using an repair functionality as implementation detail. Currently I haven't thought to make this "public", but it might be a useful extension.

I can think of two possible solution which will work for the current code:
1) If the validity check is cheap, you can write an `Alterer` adapter.
```java
public final class RepairingAlterer<
    G extends Gene<?, G>,
    C extends Comparable<? super C>
>
    implements Alterer<G, C>
{
    private final Alterer<G, C> _adoptee;
    private final Function<Genotype<G>, Genotype<G>> _repair;

    public RepairingAlterer(
        final Alterer<G, C> adoptee,
        final Function<Genotype<G>, Genotype<G>> repair
    ) {
        _adoptee = requireNonNull(adoptee);
        _repair = requireNonNull(repair);
    }

    @Override
    public int alter(final Population<G, C> population, final long generation) {
        final int altered = _adoptee.alter(population, generation);
        for (int i = 0, n = population.size(); i < n; ++i) {
            if (!population.get(i).isValid()) {
                population.set(i, repair(population.get(i)));
            }
        }
        return altered;
    }

    private Phenotype<G, C> repair(final Phenotype<G, C> pt) {
        return Phenotype.of(
            _repair.apply(pt.getGenotype()),
            pt.getGeneration(),
            pt.getFitnessFunction(),
            pt.getFitnessScaler()
        );
    }
}
```  

2) If the validity check is to expensive, you must (re) implement the `Alterer` (most likely by copy-paste code re-use ;-) and check-and-repair the altered `Genotype`. The `PartiallyMatchedCrossover` `Alterer` has an separate repair step.
