### ISSUE TITLE
Allow for Multi-Objective Optimization

### ISSUE THREAD

**Issue by StephanPirnbaum** [jenetics/jenetics#223]
Currently, Jenetics uses one fitness function in order to select the survivors and offspring. This single-objective approach has several drawbacks in problems were multiple objectives exist. Even combining them into one fitness function does not implement the constraint of the Pareto frontier. 

Possible Solution: 
- The Engine needs to allow for multiple evalutation functions
- The Selector class must be extended by a, e.g. ParetoOptimalSelector or NSGA2Selector

**Comment by ZiyeHan** [comment]
I don't really understand. Do you mean, Jenetics can't evolve a solution for a system to achieve a balance, where every object in that system gets to their bests? 

If this is what you mean, I think Jenetics fits your need. You just need to treat the group as the population and figure out the customized limit function. Maybe the most difficult part for you is to figure out the fitness function and customized limit function, which I think is possible.

Adding a ParetoOptimalSelector is not a bad idea though.

**Comment by jenetics** [comment]
Jenetics currently can't do multi-objective optimization. But it would be nice extension. I've currently found no smooth way for adding this feature.

**Comment by StephanPirnbaum** [comment]
After some time spending on trying to implement a MOO-approach using jenetics, I ended up with a workaround optimized for my specific task. If there is some time left, I'll try to figure out a better way and share it with you using a pull request.

**Comment by jenetics** [comment]
Merged into 'r4.1.0' branch.
