### ISSUE TITLE
How to specify different types of genes for fitness function?

### ISSUE THREAD

**Issue by nfrik** [jenetics/jenetics#258]
Currently fitness function can have one or multiple arguments of the same type with the same boundaries specified by for example DoubleChromosome in the Engine. However it is mentioned in the documentation that it is possible to specify different constraints for genes in chromosome. Could you please explain how to specify individual boundaries and maybe types for each argument in the fitness function?

**Comment by nfrik** [comment]
I found answer to my question on page 7 of you documentation and javadoc http://jenetics.io/javadoc/jenetics/3.9/org/jenetics/engine/Engine.html

Thank you for great library!

**Comment by jenetics** [comment]
You are welcome. :smile:
