### ISSUE TITLE
Questions: How can I access the active population of current generation? / How can I ensure nonrepetitive individuals among the population?

### ISSUE THREAD

**Issue by yoranl** [jenetics/jenetics#261]
Hi!

I wrote my own diversity measure to be executed on every generation. I'm using the peek method to invoke my method so I can access the population via result.getPopulation() method. But by assessing the population i've noticed that population size increases during each evolution step. I tried to filter the population by generation and isValid method, but it didn't seem to be correct because i'm getting a population greater than my population size parameter and there are duplicated individuals inside of it. So, here comes my questions:

How can I access the **active** population of current generation?
How can I ensure nonrepetitive individuals among the population? 

Accessing population
`final Population<IntegerGene, Double> population = result.getPopulation();`

This is my genotype:
`Factory<Genotype<IntegerGene>> gtf =
            Genotype.of(IntegerChromosome.of(1, 5, (int) chromosomeSize));`

===
Thank you for the library, by the way!

**Comment by jenetics** [comment]
Hi @yoranl I couldn't reproduce the growing population size. I tried to reproduce it with the following test:

```java
public class Test_261 {

    final static Problem<Integer, IntegerGene, Integer> PROBLEM = Problem.of(
        s -> s,
        Codec.of(
            Genotype.of(IntegerChromosome.of(1, 5, 10)),
            gt -> gt.getChromosome().getGene().intValue()
        )
    );

    public static void main(final String[] args) {
        final int populationSize = 10;
        final Engine<IntegerGene, Integer> engine = Engine.builder(PROBLEM)
            .populationSize(populationSize)
            .build();

        engine.stream()
            .limit(100)
            .peek(r -> {assert r.getPopulation().size() == populationSize;})
            .collect(EvolutionResult.toBestPhenotype());
    }

}
```
But the code runs without error. The population size stays constant.

Jenetics doesn't take care about duplicate individuals in the population. But a special `Alterer` can do the trick:

```java
public class Deduplication<
    G extends Gene<?, G>,
    C extends Comparable<? super C>
>
    implements Alterer<G, C>
{

    private final Factory<Genotype<G>> _factory;

    public Deduplication(final Factory<Genotype<G>> factory) {
        _factory = requireNonNull(factory);
    }

    @Override
    public int alter(final Population<G, C> population, final long generation) {
        final Set<Phenotype<G, C>> elements = new HashSet<>();
        elements.addAll(population);

        while (elements.size() < population.size()) {
            elements.add(population.get(0).newInstance(_factory.newInstance(), generation));
        }
        return 0;
    }
}
```

You have to take care that this alterer is at the last position of your alterers.

```java
final Engine<IntegerGene, Integer> engine = Engine.builder(PROBLEM)
    .populationSize(populationSize)
    .alterers(
        new MeanAlterer<>(),
        new SwapMutator<>(),
        new Deduplication<>(PROBLEM.codec().encoding())
    )
    .build();
```

**Comment by jenetics** [comment]
The proposed deduplication code using a special alterer removes duplicate individuals from the survivor and offspring population, but it is still possible to have duplicates in the overall population. Mapping the evolution stream can remove global duplicates:

```java
public static void main(final String[] args) {
    final int populationSize = 10;
    final Engine<IntegerGene, Integer> engine = Engine.builder(PROBLEM)
        .populationSize(populationSize)
        .alterers(
            new MeanAlterer<>(),
            new SwapMutator<>(),
            new Deduplication<>(PROBLEM.codec().encoding())
        )
        .build();

    engine.stream()
        .limit(100)
        .peek(r -> {assert r.getPopulation().size() == populationSize;})
        .map(r -> deduplication(r, PROBLEM.codec().encoding()))
        .collect(EvolutionResult.toBestPhenotype());
}

private static <G extends Gene<?, G>, C extends Comparable<? super C>>
EvolutionResult<G, C>
deduplication(final EvolutionResult<G, C> result, final Factory<Genotype<G>> factory) {
    final Population<G, C> population = result.getPopulation();
    final Set<Phenotype<G, C>> elements = new HashSet<>();
    elements.addAll(population);

    while (elements.size() < population.size()) {
        elements.add(
            population.get(0)
                .newInstance(factory.newInstance(), result.getGeneration()));
    }

    return EvolutionResult.of(
        result.getOptimize(),
        new Population<>(elements),
        result.getGeneration(),
        result.getTotalGenerations(),
        result.getDurations(),
        result.getKillCount(),
        result.getInvalidCount(),
        result.getAlterCount()
    );
}
```

**Comment by yoranl** [comment]
Thank you, @jenetics! 

I'll try your new filter.

Just a question: when i was investigating the duplicated individuals among a population, they were actually the same objects on the list, not just different individuals with the same codification, but the same objects (same object ID). Is that possible?

**Comment by jenetics** [comment]
This can happen when the offspring selector and the survivor selector are selecting the same individual, since the two selectors work independently from each other.

**Comment by yoranl** [comment]
It also happened for me even if I set survivorsSize to zero. Can I set survivorsSize to zero?

**Comment by jenetics** [comment]
You can set the survivors size to zero. And I forgot to mention that all `ProbabilitySelector`s can select one individual more than one time. This selectors selects an individual (selection probability is proportional to its fitness) and _puts_ it back to the _pool_. If this is not the desired behavior, I guess you know it already ;.), you have to implement your own selector(s).

**Comment by yoranl** [comment]
Hey, @jenetics, you're right. Sorry, my mistake.

**Comment by yoranl** [comment]
Maybe I've found the situation where population becomes larger than population size parameter.

Simple adding survivorsSize to zero in the Test Class below, population doubles in size on each generation:

`public class Test_261 {

    final static Problem<Integer, IntegerGene, Integer> PROBLEM = Problem.of(
        s -> s,
        Codec.of(
            Genotype.of(IntegerChromosome.of(1, 5, 10)),
            gt -> gt.getChromosome().getGene().intValue()
        )
    );

    public static void main(final String[] args) {
        final int populationSize = 10;
        final Engine<IntegerGene, Integer> engine = Engine.builder(PROBLEM)
            .populationSize(populationSize)
            .survivorsSize(0)
            .build();

        engine.stream()
            .limit(100)
            .peek(r -> {assert r.getPopulation().size() == populationSize;})
            .collect(EvolutionResult.toBestPhenotype());
    }

}`

**Comment by jenetics** [comment]
Hm, I still can't reproduce it. Runs without assertion with version 3.9 and development version 4.0.  Which version are you using? Is anything special of your environment?

**Comment by yoranl** [comment]
Was using 3.8! Thought it was 3.9, sorry. Running on 3.9 everything went fine! Thanks!

**Comment by jenetics** [comment]
Good, I think #234 caused the problem.
