### ISSUE TITLE
How to turning “400 elements permutation combinations” problem？

### ISSUE THREAD

**Issue by frankiezdh** [jenetics/jenetics#305]
There is an array of length 400. The goal is to fill the array with a certain amount of 1,2,3,4,5,6,7,8,9 in a certain way.   The goal of optimization is to minimize the array element changes. Code below: 

```java
        ISeq<Integer> orders = buildOrders();
        Codec<ISeq<Integer>, EnumGene<Integer>> codec = buildCodec(orders);
        Engine<EnumGene<Integer>, Integer> engine = buildEngine(codec);
        Genotype<EnumGene<Integer>> collect = engine.stream()
                .limit(Limits.byFitnessThreshold(30))
//                .limit(Limits.byExecutionTime(Duration.ofMinutes(2)))
                .collect(EvolutionResult.toBestGenotype());
        ISeq<Integer> best = codec.decode(collect);
        System.out.println(best);
        System.out.println(fitness(best));
```

```java
    static Engine<EnumGene<Integer>, Integer> buildEngine(Codec<ISeq<Integer>, EnumGene<Integer>> codec) {
        return Engine.builder(App::fitness, codec)
                .offspringSelector(new RouletteWheelSelector<>())
                .alterers(new SwapMutator<>(), new PartiallyMatchedCrossover<>(0.38))
                .populationSize(10000)
                .optimize(Optimize.MINIMUM)
                .build();
    }
```
```java
    //fitness return the changes of array.
    private static Integer fitness(ISeq<Integer> result) {
        result = result.stream().filter(x -> x != 0).collect(ISeq.toISeq());
        int count = 0;
        for (int i = 1; i < result.size(); i++) {
            if (!result.get(i).equals(result.get(i - 1))) {
                count += 1;
            }
        }
        return count;
    }
```

I tried some approaches, like modifing offspringSelector Parameteres, alterers Parameteres, populationSize. The results were always greater than 140，not good enough。

So can some one give somthing  advises?

**Comment by jenetics** [comment]
Is this some kind of test program or a "real" problem which needs to be optimized? Your fitness function is filtering the zero(s) out of the result. Maybe there is some _problem_ with your encoding. Since you are using an `EnumGene`, your trying to solve a combinatorial problem, right? Can you post the _Codec_ as well?

**Comment by frankiezdh** [comment]
@jenetics  Codec is below
```java
    static final int ROW_NUM = 20;
    static final int COL_NUM = 20;
    static final int TOTAL_NUM = ROW_NUM * COL_NUM;
    static final ISeq<Integer> A = ISeq.of(40, 40, 40, 40, 40, 40, 40, 40, 39);

    static ISeq<Integer> buildOrders() {

        List<Integer> tmp = new ArrayList<>(TOTAL_NUM);
        for (int i = 1; i <= A.size(); i++) {
            int finalI = i;
            List<Integer> a = IntStream.rangeClosed(1, A.get(i - 1)).boxed().map(x -> finalI).collect(Collectors.toList());
            tmp.addAll(a);
        }

        for (int i = 0; i < TOTAL_NUM - A.stream().mapToInt(x -> x).sum(); i++) {
            tmp.add(0);
        }
        return ISeq.of(tmp);
    }


    static Codec<ISeq<Integer>, EnumGene<Integer>> buildCodec(ISeq<Integer> orders) {
        return Codecs.ofPermutation(orders);
    }
```

**Comment by jenetics** [comment]
I did some experimenting with your example and could reproduce the _bad_ optimization performance. Then I did some calculations for estimating the size of the search space.
An array of length 400 has ~ 10^868 element permutations. From this permutations are 10!*40! ~ 10^54 _optimal_ solutions. So we have a search space of about 10^814. This is really **huge**. So I don't think there is a problem with the implementation or your codec (I'm saying this without knowing your actual problem). You simply have a huge search space.

PS: Just for curiosity, is a GA the right algorithm for your problem? The initial permutation you are creating for the codec has a fitness of 8.

**Comment by frankiezdh** [comment]
Thanks @jenetics 

Yes，you are right. The initial permutation you are creating for the codec has a fitness of 8.
The real problem to a multiobjective optimization. I want to describe the problem clearly so simplify the fitness。

**Comment by jenetics** [comment]
Yes, I don't think you can tune your problem with the existing `SwapMutator` or `PartiallyMatchedCrossover`. They will rather destroy your solutions than find better ones. 
A possible solution is to implement your own `Alterer` class, which takes care of your special problem and doesn't destroy already found good solutions. This can be done by choosing a crossover- or swap-point which is not in the middle of a  _run_.

**Comment by frankiezdh** [comment]
OK，I get it. Thank you.
