### ISSUE TITLE
Ensure any Gene is found only once among all chromosomes

### ISSUE THREAD

**Issue by quentin-sommer** [jenetics/jenetics#310]
Hi,

I'm working on a combinatorial problem in which I try to optimally position things in `n` different buckets. I'm trying to use chromosomes to represent buckets. To do this I'd like to be able to ensure that there won't be any value duplication in all of the `n` chromosomes. I've seen that `PermutationChromosome` and `PartiallyMatchedCrossover` do exactly this one the 1 chromosome scale. Is there a way to do it for all the chromosomes?

Best,

**Comment by jenetics** [comment]
There is no way to ensure unique genes over more than one chromosome. Without knowing your concrete problem/encoding, I would recommend to _flatten_ your _n_ chromosomes into one and do the un-flattening in the fitness function or in the `Codec.decoder` function.

**Comment by quentin-sommer** [comment]
I hadn't thought about flattening the data. It worked perfectly thanks! Great library by the way enjoyed using it
