### ISSUE TITLE
Execution and result review of each evolution step

### ISSUE THREAD

**Issue by wolfig** [jenetics/jenetics#320]
Dear Experts, I am looking for advice in the following implementation problem: I'd like to use jenetics as optimization algorithm for the optimization of a particle Accelerator beamline. My idea is to create DoubleGenes for each of the device-settings and then let jenetics optimize on the readout of a particle detector. To monitor and visualize the process it would be very desirable to do the evolution stepwise and with the corresponding result passed to a surrounding app. do you have a good code example (I guess engine . evolve could be the ansatz) how to tackle this? I did not find any as almost any example uses engine.stream.  regards

**Comment by jenetics** [comment]
I have done something similar in the [Evolving images](https://github.com/jenetics/jenetics#evolving-images) example. You can have a look at the [EvolvingImagesWorker](https://github.com/jenetics/jenetics/blob/master/jenetics.example/src/main/java/io/jenetics/example/image/EvolvingImagesWorker.java) where I implemented the pause/resume capability.

**Comment by wolfig** [comment]
Thanks a lot
