### ISSUE TITLE
Do I need a custom gene for an allele with 3 numeric values?

### ISSUE THREAD

**Issue by hackerbunny** [jenetics/jenetics#330]
Hi,

To begin with, thanks for creating Jenetics.

The allele of the problem I want to solve consists of three numeric values (I am using integers).  Two of the integers have the same range (e.g. 0 to 9), the other integer has a smaller range (e.g. 0 to 5).

For simplicity's sake, the fitness function just calculates the sum of all 3 values in a gene's allele, and the chromosome with the lowest sum value of its genes is the fittest. So I am using .optimize (Optimize.MINIMUM) in the engine. But I keep getting an error when I run the main program: 

Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
..........
Caused by: java.lang.IllegalArgumentException: bound must be positive
	at java.util.concurrent.ThreadLocalRandom.nextInt(ThreadLocalRandom.java:352)
	at org.jenetics.SinglePointCrossover.crossover(SinglePointCrossover.java:87)

I've created a custom gene class, a custom chromosome class, and even a custom class for the allele. I am not sure if using a class to encapsulate the allele is a good idea though. 

What is frustrating is that, when I search for the maximum sum as fitness, the program runs fine and I get consistent results. The error I get when the fitness function is minimum, seems to be related to my custom chromosome class length perhaps?

Am I over-complicating things by using custom classes to solve this problem? Could this be done with the existing jenetics classes?

Thanks.

PS: I have not included code samples or the full error message because first I would like to know if what I want to do could be achieved without creating custom Genes and Chromosomes.

**Comment by jenetics** [comment]
It seems that you try to create chromosome of length one. But to be honest, I don't no what your problem is you try to solve with Jenetics. Can you be more specific? Then I might be able to help you.

**Comment by hackerbunny** [comment]
Ok, let's see if I can explain correctly what I want to achieve

My fitness function is actually an external C++ program. The encoded solution takes the form of an array of variable length made of tuples that contain 3 values. When this data structure is feed to the program, it returns a value from 0 to 100, lowest values being fitter.

So what I need is a chromosome of variable length (within a range), made of genes that contain 3 values (also within a range).

I have chosen to use integers for the 3 values, but I guess I could use characters too. It does not really matter, as long as the external program receives 3 different symbols per gene.

I hope that clarifies it.

**Comment by jenetics** [comment]
If I understand you correctly, you don't need to implement your allele/gene/chromosome type. It should be possible to do this with the existing classes. You can actually use two different encodings, given in the following example:
```java
// Strawman for your tuple data structure.
class IntTuple3 {
    int x, y, z;
    IntTuple3(int x, int y, int z) {
        this.x = x; this.y = y; this.z = z;
    }
}

// The valid integer range of your tuple elements.
final IntRange range = IntRange.of(0, 100);

// The length range of your IntTuple3[] array.
final IntRange length = IntRange.of(10, 15);

double fitness(final IntTuple3[] values) {
    // Your fitness function.
    return 0;
}

// First encoding uses 3 different chromosomes, one for each tuple element.
// This allows you to define different int ranges (which is not done in this
// example.
final Codec<IntTuple3[], IntegerGene> codec1 = Codec.of(
    Genotype.of(
        IntegerChromosome.of(range, length),
        IntegerChromosome.of(range, length),
        IntegerChromosome.of(range, length)
    ),
    gt -> {
        final int[] x = gt.get(0).as(IntegerChromosome.class).toArray();
        final int[] y = gt.get(1).as(IntegerChromosome.class).toArray();
        final int[] z = gt.get(2).as(IntegerChromosome.class).toArray();

        final int size = min(min(x.length, y.length), z.length);
        return IntStream.range(0, size)
            .mapToObj(i -> new IntTuple3(x[i], y[i], z[i]))
            .toArray(IntTuple3[]::new);
    }
);

// Second encoding uses one chromosome with 3*length. This is OK if you have
// the same int range for your tuple elements.
final Codec<IntTuple3[], IntegerGene> codec2 = Codec.of(
    Genotype.of(IntegerChromosome.of(
        range,
        IntRange.of(length.getMin()*3, length.getMax()*3)
    )),
    gt -> {
        final int[] ints = gt.get(0).as(IntegerChromosome.class).toArray();
        final int size = ints.length/3;

        return IntStream.range(0, size)
            .mapToObj(i -> new IntTuple3(ints[i*3], ints[i*3 + 1], ints[i*3 + 2]))
            .toArray(IntTuple3[]::new);
    }
);
```
I hope this would solve your problem.

**Comment by hackerbunny** [comment]
Yes it does. I didn't look into using codecs, this makes it so much simpler than my custom classes.

Thank you so much!

**Comment by jenetics** [comment]
Good to hear. This was the plan when I introduced the `Codec` interface :smile:

**Comment by jenetics** [comment]
The `get(int)` method is available since version 4.0 and is a shortcut for `getChromosome(int)`.

This is the correct way for creating an engine instance. The purpose of the `Codec` interface is to move the genotype conversion code out of your fitness function. It also allows me to create some predefined codecs for common types, like int[] or double[] vectors.

**Comment by hackerbunny** [comment]
Ok, corrected that, still getting a similar error. Perhaps I need to change something in the fitness function declaration?

Error:(106, 21) java: no suitable method found for builder(Main::fitness,io.jenetics.engine.Codec<main.IntTuple3[],io.jenetics.IntegerGene>)
    method io.jenetics.engine.Engine.<T,G,C>builder(io.jenetics.engine.Problem<T,G,C>) is not applicable
      (cannot infer type-variable(s) T,G,C
        (actual and formal argument lists differ in length))
    method io.jenetics.engine.Engine.<G,C>builder(java.util.function.Function<? super io.jenetics.Genotype<G>,? extends C>,io.jenetics.util.Factory<io.jenetics.Genotype<G>>) is not applicable
      (cannot infer type-variable(s) G,C
        (argument mismatch; invalid method reference
          incompatible types: io.jenetics.Genotype<G> cannot be converted to main.IntTuple3[]))
    method io.jenetics.engine.Engine.<G,C>builder(java.util.function.Function<? super io.jenetics.Genotype<G>,? extends C>,io.jenetics.Chromosome<G>,io.jenetics.Chromosome<G>...) is not applicable
      (cannot infer type-variable(s) G,C
        (argument mismatch; invalid method reference
          incompatible types: io.jenetics.Genotype<G> cannot be converted to main.IntTuple3[]))
    method io.jenetics.engine.Engine.<T,G,C>builder(java.util.function.Function<? super T,? extends C>,io.jenetics.engine.Codec<T,G>) is not applicable
      (cannot infer type-variable(s) T,G,C
        (argument mismatch; invalid method reference
          cannot find symbol
            symbol:   method fitness(T)
            location: class main.Main))

**Comment by jenetics** [comment]
Then I guess it is the non-static fitness function. If you want to use `Main::fitness`, the `fitness` method must be static.

**Comment by hackerbunny** [comment]
Yes, that was it. Thanks! The IDE was not giving me any warning about the fitness function being non-static and I missed it. It usually does in these cases.

One question about the way Jenetics handles the fitness function:
Does it execute it several times in parallel for each individual in multiple threads?

I am asking this because my fitness function modifies on disk the config file of the C++ program prior to executing it every time. So if this is done concurrently I will need to find a way of using different config files with randomised names to avoid conflicts when accesing it on disk.

**Comment by jenetics** [comment]
The fitness evaluation is done in parallel, by default. It is also assumed, that the fitness function is thread safe. One the other hand, the fitness function is only executed once and the fitness value is then cached by the phenotype. If you don't mind the performance decrease, you can also execute the fitness function in the main thread.

```java
final Engine<DoubleGene, Double> engine = Engine
    .builder(...)
    // Executor used for fitness evaluation.
    .executor(Runnable::run)
    .build();
```

With this `Executor` implementation, no extra thread safety measures are necessary.

**Comment by hackerbunny** [comment]
Ok. I will give it a try and see how it affects performance. I am not too bothered about it, but if it slows to a crawl, I will make the fitness function thread safe with some extra work.

Thank you very much for your help!
