### ISSUE TITLE
:jenetics:javadoc "unmappable character for encoding ASCII" on ``./gradlew assemble``

### ISSUE THREAD

**Issue by travisfw** [jenetics/jenetics#340]
To reproduce, just type ``./gradlew assemble``

    jenetics ) ./gradlew assemble
    
    > Task :jenetics:javadoc FAILED
    /home/travisfw/workspace/jenetics/jenetics/src/main/java/io/jenetics/stat/IntMomentStatistics.java:3: error: unmappable character for encoding ASCII
     * Copyright (c) @__year__@ Franz Wilhelmst??tter
                                               ^
The error output continues with another hundred errors like this.

**Comment by jenetics** [comment]
Which OS are you using? Seems you have problems with your charset. If you check it out with UTF-8, everything should be be working.

**Comment by travisfw** [comment]
I'm on Fedora Linux. How does one "check it out with UTF-8"?
I see a UTF-8 charset declaration in the root ``build.gradle``

    task alljavadoc(type: Javadoc) {
        options.encoding = 'UTF-8'

Why might this ``options.encoding`` setting not be effective? Maybe I could do something with my OS to stop having these errors, but other builds would still fail. It's probably just a one line fix for a gradle file. I just don't know where to put it.

**Comment by jenetics** [comment]
What's the actual encoding of the files? For my local sources it is UTF-8.
```
$ file EvolutionStream.java
EvolutionStream.java: HTML document, UTF-8 Unicode text
```

Maybe something went wrong when cloning the repository.

**Comment by travisfw** [comment]
Mine looks similar:

    jenetics ) file jenetics/src/main/java/io/jenetics/engine/EvolutionStream.java
    jenetics/src/main/java/io/jenetics/engine/EvolutionStream.java: HTML document, UTF-8 Unicode text

But still, ``./gradlew javadoc`` gives the same errors.
