### ISSUE TITLE
Allow async fitness functions

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#364]
The fitness function currently must be evaluated synchronous. It should be possible to define fitness functions which return a `Future` object.
```java
public Future<Double> fitness(final Genotype<DoubleGene> gt) {
    return ...;
}

Genotype<DoubleGene> gtf = Genotype.of(DoubleChromosome.of(0, 1));
Engine<DoubleGene, Double> engine = Engine.build(this::fitness, gtf).build();
```

**Comment by gfrison** [comment]
Hello,

Instead of ``Future`` could be possible to return a ``CompletableFuture``? The latter is more suitable for callbacks.

Thank you,

**Comment by jenetics** [comment]
Merged into r5.0.0 branch.
