### ISSUE TITLE
multi-task learning

### ISSUE THREAD

**Issue by gfrison** [jenetics/jenetics#365]
Hello,

``ProgramGene`` is designed for dynamic programming, it accepts N parameters in input (defined as terminal operators) ``<T> T ProgramGene::eval(T...)`` and returns a single value.
I'd get multiple values that represents a multi-task learning. How could I get a ``T[]`` in return? Is it possible in jenetics?

Thank you,

**Comment by jenetics** [comment]
Returning an array of `T[]` is not possible. You can try to make `T` itself an array type.

**Comment by gfrison** [comment]
I created this snippet:
```
  /*
  0 = sum(x,y)
  1 = x
  2 = y
   */
  static final double[][] samples = {
      {2, 1, 1},
      {6, 4, 2},
      {3, 2, 1},
      {4, 1, 3},
      {5, 3, 2},
      {7, 3, 4},
      {8, 6, 2},
      {6, 5, 1}
  };
  static final ISeq<Op<Double>> operations = ISeq.of(MathOp.values());
  static final ISeq<Op<Double>> terminals = ISeq.of(Var.of("x", 0), Var.of("y", 1),
      EphemeralConst.of(() -> (double) RandomRegistry.getRandom().nextInt(10)));
  static final Codec<ProgramGene<Double>, ProgramGene<Double>> codec = Codec.of(
      Genotype.of(
          ProgramChromosome.of(2, ch -> ch.getRoot().size() <= 50, operations, terminals)
      ), Genotype::getGene
  );
  private static Engine.Evaluator<ProgramGene<Double>, Double> evaluator = population -> {
    // Already evaluated.
    final ISeq<Phenotype<ProgramGene<Double>, Double>> evaluated = population.stream()
        .filter(Phenotype::isEvaluated)
        .collect(ISeq.toISeq());

    // Must be evaluated.
    final ISeq<Phenotype<ProgramGene<Double>, Double>> evaluate = population.stream()
        .filter(pt -> !pt.isEvaluated())
        .collect(ISeq.toISeq());

    final ISeq<Observable<Phenotype<ProgramGene<Double>, Double>>> phenotypes = evaluate.map(pt ->
        error(pt.getGenotype().getGene())
            .map(pt::withFitness));

    // Append the already evaluated population.
    return evaluated.append(Observable.merge(phenotypes)
        .toList()
        .blockingGet());
  };

  public static void main(String[] args) {
    Engine<ProgramGene<Double>, Double> engine = Engine.builder(obj -> 0d, codec)
        .minimizing()
        .alterers(new SingleNodeCrossover<>(),
            new Mutator<>(),
            new MathTreePruneAlterer<>(0.5))
        .evaluator(evaluator)
        .build();

    Phenotype<ProgramGene<Double>, Double> p = engine.stream()
        .limit(1000)
        .collect(EvolutionResult.toBestPhenotype());
    System.out.println(Tree.toDottyString(p.getGenotype().getGene()));
    System.out.println(p.getGenotype().getGene().apply(new Double[]{4d, 3d}));
  }

  private static Observable<Double> error(ProgramGene<Double> object) {
    return Observable.just(Arrays.stream(samples)
        .mapToDouble(sample -> pow(sample[0] - object.eval(ArrayUtils.toObject(Arrays.copyOfRange(sample, 1, sample.length))), 2) + object.size() * 0.00001)
        .sum());
  }
```
and it works:

```
digraph T {
    node_1691185247 -> node_153245266;
    node_1691185247 -> node_1699679644;
    node_153245266 [label="y"];
    node_1699679644 [label="x"];
    node_1691185247 [label="add"];
}

```

my objective now is to add another function for jenetics to learn. for example
 ```
  /*
  0 = sum(x,y)
  1 = mul(x,y)
  2 = x
  3 = y
   */
  static final double[][] samples = {
      {2,1, 1, 1},
      {6, 8, 4, 2},
....
  };
```
do you think it would be possible? how can I do that? could be the ``ext.moea`` comes in the rescue?
if I define ``ProgramGene<Double[]>`` I should define custom operations and terminators for that, could that work?

Thank you,

**Comment by jenetics** [comment]
So, you want to find a function _f: R² -> R²_, which fits your data-points, right?
In this case, you just have to create a `ProgramGene<double[]>` and define proper vector operations (`Op<double[]>`), the `jenetics.prog` classes will do the rest. The predefined `MathOp` operations are working with scalars, your operations have to handle vectors. You will also have only one input variable x element of R².

**Comment by gfrison** [comment]
if I write operations for vectors, jenetics should create a program for every element of the returned ``double[]`` but I guess this is not the case. am i wrong?let me make a more explanatory example:
I have input _a_ and _b_ and I want in output 2 variables _x_ and _y_ by which _x_  represents the tens  while _y_ are units  of the sum _x+y_. 
```output = {(x,y):0<=x<=9,0<=y<=9, x*10+y == a+b}```
The fitness function is the squared distance of the _xy_ couple minus the the sum of inputs:

``fitness = ((x*10 + y) - (a + b) )²``

in this way there is not a direct fitness function for each output but instead there is only the aggregated one.

is there an easy and elegant way to do that?

thank you

**Comment by jenetics** [comment]
Lets have another try: It is possible to evolve two different programs. One for input a and one for input b. I adapted the `jenetics.prog` [Example](https://github.com/jenetics/jenetics/blob/master/jenetics.prog/src/test/java/io/jenetics/prog/Example.java).

```java
static final ISeq<Op<Double>> TERMINALS = ISeq.of(
	Var.of("x", 0),
	EphemeralConst.of(() -> (double)RandomRegistry.getRandom().nextInt(10))
);

static double error(final ISeq<Tree<Op<Double>, ?>> programs) {
	return Arrays.stream(SAMPLES)
		.mapToDouble(sample -> {
			final Tree<Op<Double>, ?> x = programs.get(0);
			final Tree<Op<Double>, ?> y = programs.get(1);
			final double a = sample[0];
			final double b = sample[1];

			final double z = Program.eval(x, a)*10 + Program.eval(y, b);
			return (z - (a + b))*(z - (a + b));
		}).sum();
}

static final Codec<ISeq<Tree<Op<Double>, ?>>, ProgramGene<Double>> CODEC =
	Codec.of(
		Genotype.of(
			ProgramChromosome.of(
				5,
				ch -> ch.getRoot().size() <= 50,
				OPERATIONS,
				TERMINALS
			),
			ProgramChromosome.of(
				5,
				ch -> ch.getRoot().size() <= 50,
				OPERATIONS,
				TERMINALS
			)
		),
		gt -> gt.toSeq().map(Chromosome::getGene)
	);
```

Does this make sens?

**Comment by gfrison** [comment]
how can I get the 2 programs from the engine?
```
    Engine<ProgramGene<Double>, Double> engine = Engine.builder(BiProgram::error, codec)
        .minimizing()
        .alterers(new SingleNodeCrossover<>(),
            new Mutator<>(),
            new MathTreePruneAlterer<>(0.5))
        .build();
    ProgramGene<Double> gene = engine.stream()
        .limit(20000)
        .collect(EvolutionResult.toBestGenotype()).getGene();
```
here I have only one ``gene``. which api should I invoke?

**Comment by gfrison** [comment]
that's cool! So it is possible to define more programs from the same engine. Thank you!
One question. Previously I asked for an async fitness function through rx.Observable. I used:
```
  private static Engine.Evaluator<ProgramGene<Double>, Double> evaluator = population -> {
    // Already evaluated.
    final ISeq<Phenotype<ProgramGene<Double>, Double>> evaluated = population.stream()
        .filter(Phenotype::isEvaluated)
        .collect(ISeq.toISeq());

    // Must be evaluated.
    final ISeq<Phenotype<ProgramGene<Double>, Double>> evaluate = population.stream()
        .filter(pt -> !pt.isEvaluated())
        .collect(ISeq.toISeq());

    final ISeq<Observable<Phenotype<ProgramGene<Double>, Double>>> phenotypes = evaluate.map(pt ->
        error(pt.getGenotype())
            .map(pt::withFitness));

    // Append the already evaluated population.
    return evaluated.append(Observable.merge(phenotypes)
        .toList()
        .blockingGet());
  };
```
as evaluator for the engine, but the method `` error(pt.getGenotype())`` doesn't fit with the new error function. I'm not very familiar with jenetics api, how can I get ``ISeq<Tree<Op<Double>, ?>> programs`` from the ``Phenotype``? 

Thank you,

**Comment by jenetics** [comment]
```java
final Phenotype<ProgramGene<Double>, Double> phenotype = ...;
final ISeq<Tree<Op<Double>, ?>> programs = phenotype.getGenotype().toSeq()
    .map(Chromosome::getGene);
```

**Comment by gfrison** [comment]
Thank you very much!

**Comment by gfrison** [comment]
in a case like this with multi programs trained against an aggregated fitness function, is it possible to specify a greedy optimizer so it is possible to improve the training speed? What do you think about it?

Thank you,

**Comment by jenetics** [comment]
What do you mean with "greedy optimizer"?

**Comment by gfrison** [comment]
it's about optimize one program at time while leaving the others steady. For convex problems it improves the velocity of training. instead of having an exponential complexity on the number of programs, it grows almost linearly. what do you think about it? would be possible to set such behavior in this case?

thank you

**Comment by jenetics** [comment]
If I understand you right, you can do this by using one of the [CyclicEngine](http://jenetics.io/javadoc/jenetics.ext/io/jenetics/ext/engine/CyclicEngine.html) class:

```java
final Engine<ProgramGene<Double>, Double> changeFist = Engine.builder(...)
	.populationSize(500)
	.alterers(new Mutator<>(0.115, 0))
	.build();

final Engine<ProgramGene<Double>, Double> changeSecond = Engine.builder(...)
	.populationSize(500)
	.alterers(new Mutator<>(0.115, 1))
	.build();

final EvolutionStreamable<ProgramGene<Double>, Double> engine = CyclicEngine.of(
	changeFist.limit(10),
	changeSecond.limit(15)
);

final EvolutionResult<ProgramGene<Double>, Double> best = engine.stream()
	.limit(bySteadyFitness(50))
	.collect(toBestEvolutionResult());
```

Unfortunately one important part is missing: there are currently no alterers where you can define the chromosome index they are allowed to alter. The chromosome which is going to be changed is currently chosen randomly. You have to implement such alterer yourself. 
To add this capability to the alterer would require some refactoring.
