### ISSUE TITLE
Assignment Problem codes implementation

### ISSUE THREAD

**Issue by ShivKJ** [jenetics/jenetics#398]
Hi,

I was looking the travelling salesman problem(TSP), in which Permutation Codecs was used.

Can you provide Assignment codec implementation that is essential a boolean matrix (say A) and where A[i][j] is true if ith worker does the jth job.

Further if that is possible then, can we ensure that each job is served by a worker(worker is capable of doing multiple jobs) while mutation and crossover take place?

**Comment by ShivKJ** [comment]
In my case, it is possible that a worker is not assigned a job. This problem is similar to Facility location problem. 

"For the other cases I would create a PermutationChromosome<Integer> of length max(|J|, |W|) and treat all indices out of the valid (job, workder) range as unassigned"
Could you elaborate this part.

**Comment by jenetics** [comment]
I created a sample `Codec`, which should make it clear what I mean.

```java
public class WorkerJobMapping {

    static final class Worker {}
    static final class Job {}

    static final ISeq<Worker> WORKERS = ISeq.of(
        new Worker(),
        new Worker(),
        new Worker(),
        new Worker(),
        new Worker()
    );
    static final ISeq<Job> JOBS = ISeq.of(
        new Job(),
        new Job(),
        new Job()
    );

    final static Codec<Map<Worker, Job>, EnumGene<Integer>> CODEC = Codecs
        .ofPermutation(WORKERS.size())
        .map(WorkerJobMapping::toWorkerJobMappping);

    private static Map<Worker, Job> toWorkerJobMappping(final int[] perm) {
        final Map<Worker, Job> map = new HashMap<>();
        for (int i = 0; i < perm.length; ++i) {
            final Worker worker = WORKERS.get(i);
            if (perm[i] < JOBS.size()) {
                map.put(worker, JOBS.get(perm[i]));
            }
        }
        return map;
    }
}
```

**Comment by jenetics** [comment]
I think it is worth of having a predefined `Codec` for this kind of problem. #400

**Comment by jenetics** [comment]
@ShivKJ  does this new mapping-codec solve your problem?

**Comment by ShivKJ** [comment]
Sorry for delayed reply.
In the above Codec, a worker can not be assigned multiple Jobs as the key in the map has to be unique. In my case a worker can be assigned multiple jobs.

Apparently this can be handled by  using 'ofPermutation(JOBS.size())' and corresponding changes and instead of Map<Worker,Job> we would have Map<Job,Worker>.

We are currently implementing this method.
