### ISSUE TITLE
Limits.byFitnessThreshold doesn't enable a perfect fitness stop

### ISSUE THREAD

**Issue by p3dromig** [jenetics/jenetics#422]
As far as I can understand (and test), Limits.byFitnessThreshold will truncate the evolution stream if there is a better fitness in the current population than the threshold. And will consider the previous population as the best result.

In my case, I was trying to minimize and wanted to have as the best genotype the first population that has a fitness value of exactly 0, which is also the minimum value of the fitness function.
The problem is that by using Limits.byFitnessThreshold(0) it with never stop the stream as 0 is the min value of the fitness function and thus is never goes below 0.
Because I'm using integers, I could use Limits.byFitnessThreshold(1). That does stop when a population with fitness 0 is found. However, the best genotype will be the one with fitness 1 and not the first with fitness 0, which was the goal.

I understand the function might be working as intended, but I can't seem to have any other way (other Limits functions) to achieve my goal, that is, end the evolution exactly when a fitness value is found and return that population as a result.
Maybe there could be a flag to select if byFitnessThreshold should stop at < or <= than the threshold.

[343](https://github.com/jenetics/jenetics/issues/343) is a similar issue, although I'm not sure the report is trying to achieve the same goal as me.

Here is a simplified example of what I'm trying to achieve.

`
    // Goal is to get zero.
    private static int eval(Genotype<IntegerGene> gt) {
        int fitness = 0;
        IntegerChromosome ic = gt.getChromosome().as(IntegerChromosome.class);

        for (int i = 0; i < ic.length(); ++i ) {
            fitness += ic.getGene(i).intValue();
        }
        return fitness;
    }

    @Test
    public void zeroFitnessThreshold() {
        Factory<Genotype<IntegerGene>> gtf =
                Genotype.of(IntegerChromosome.of(0, 9, 3));

        Engine<IntegerGene, Integer> engine = Engine
                .builder(JeneticsLibTest::eval, gtf)
                .minimizing()
                .build();

        Genotype<IntegerGene> resultGenotype = engine.stream()
                .limit(Limits.byFitnessThreshold(1))
                .peek(er -> System.out.print("#" + er.getGeneration() + ": "))
                .peek(er -> System.out.println(er.getBestPhenotype()))
                .collect(EvolutionResult.toBestGenotype());

        int resFit = eval(resultGenotype);
        System.out.println("Result: " + resultGenotype + " with fitness " + resFit);
        
        assertTrue( resFit == 0 );
    }
`

**Comment by jenetics** [comment]
You are right, this problem is similar to #343 and has been fixed in #420. The fix is part of release 4.3.0, which will be released soon.
