### ISSUE TITLE
Model multiple gene types into one genotype

### ISSUE THREAD

**Issue by ipsq** [jenetics/jenetics#423]
Is it possible to model multiple gene types into one genotype utilizing only one fitness function?

Imagine you have to design a piece of furniture. You have a broad selection of materials, heights, widths, etc. to choose from in order to come to the final design. This search space is too big to brute force so a genetic algorithm makes most sense here. The fitness function only evaluates the final design, e.g. the combination of all the different selections are given a final score. This would probably mean some sort of an HList implementation for both the `Engine`, `Genotype` etc. I saw issue #277 where some work was done but ultimately given the "wontdo" tag in favor of #223. I'm not sure how the solution proposed there would apply to my problem definition. 

I've written some Scala code as to how these HList classes could be implemented:

```scala
import shapeless.UnaryTCConstraint.*->*
import shapeless.ops.hlist.At
import shapeless._
import shapeless.nat._

case class Genotype[L <: HList : *->*[Chromosome]#λ](chromosomes: L) {

  def chromosome(n: Nat)(implicit at: At[L, n.N]): at.Out = chromosomes[n.N]

}

trait Chromosome[A] {
  // ...
}

trait Gene[A] {
  def allele: A
}

object Test {

  def main(args: Array[String]): Unit = {
    val chromosomes: Chromosome[Foo] :: Chromosome[Bar] :: HNil = FooChromosome() :: BarChromosome() :: HNil
    val out: Chromosome[Bar] = Genotype(chromosomes).chromosome(1)
    println(out.toString)
  }

}

case class FooChromosome() extends Chromosome[Foo]
case class FooGene(allele: Foo) extends Gene[Foo]
case class Foo()
case class BarChromosome() extends Chromosome[Bar]
case class BarGene(allele: Bar) extends Gene[Bar]
case class Bar()
```

This probably wouldn't play well with Java but I don't think there is much to be done about that.

**Comment by jenetics** [comment]
You already found the tickets, where I tried to solve this problem. Implementing and using an HList in Java is cumbersome. With the current design it is also not possible to define a `Genotype` with a common gene type, like `Genotype<? extends NumericGene<?, ?>>`.

My solution for this problem is:
* Using raw-types: `Genotype`. This solution will only work with Java
* Mapping your problem to one gene-type, like `DoubleGene`. You need an additional mapping from the common gene-type to the desired type.

**Comment by jenetics** [comment]
Using `AnyGene` is quite mighty. Most of the selector/alterer implementations have _restrictions_ on the return type of the fitness function. Numerical fitness values gives you the most _power_. Only `Meanalterer` and `GaussianMutator` will require a numerical genes.
If you can encode your problem with an `AnyGene<Object>`, you can _simulate_ a heterogeneous `Genotype`.
