### ISSUE TITLE
Manual minor issue in listing 1.6

### ISSUE THREAD

**Issue by RalfHerzog** [jenetics/jenetics#424]
Hi, I am just reading through your awesome manual. In listing 1.6 on page 17 you create a random int `i2` in line 5. In line 7, I think, you want to use it (instead of just `.get(2)`).

**Comment by jenetics** [comment]
@RalfHerzog you are right, and it's nice to see that somebody is reading the manual ;-)

**Comment by jenetics** [comment]
Fixed in r4.4.0 branch.
