### ISSUE TITLE
Unexpected number of calls of fitness function

### ISSUE THREAD

**Issue by SimonSchmid** [jenetics/jenetics#435]
Hi,

Since I have an expensive fitness function, I am wondering how I could calculate the number of calls of the fitness function before the actual computation. I assumed it is population size * number of generations but it is not. Does it depend on another parameter?

Thanks!
Simon

**Comment by jenetics** [comment]
Whats the actual number? Jenetics will cache the fitness values. The fraction of the surviving individuals also influences this number. Additional y, individuals will be killed if they are to old.

**Comment by SimonSchmid** [comment]
So but then I would expect population size * number of generations being an upper bound., right? If I set population size to 10 and number of generations to 2, I get sometimes more than 20 calls. I use the default value of survivor fraction. Or do you mean witch caching, that it is cached for the next "round"?

**Comment by jenetics** [comment]
Jenetics  also have to evaluate the initial population, which is generation zero.

**Comment by SimonSchmid** [comment]
That answers my question! Thank you!
