### ISSUE TITLE
How to replace specific Genotype from Population

### ISSUE THREAD

**Issue by ShivKJ** [jenetics/jenetics#436]
I found that not all candidate (genotype) which are generated in population are useful for my problem although I can modify to make them more helpful (this I do while finding fitness function).

I see that there is a method "mapping"  in Engine builder class which can be used to update genotype of current generation. Using this method will force me to check (evaluate) each individual genotype again.

Is there a way which can help update individual chromosome more efficiently ?

**Comment by jenetics** [comment]
I think you should have a look at the [Engine.Evaluator](http://jenetics.io/javadoc/jenetics/io/jenetics/engine/Engine.Builder.html#evaluator-io.jenetics.engine.Engine.Evaluator-), which give you the flexibility you need. The drawback of this approach is, that you are also responsible for doing the parallel evaluation, if desired.
