### ISSUE TITLE
Pretty Printing GP program

### ISSUE THREAD

**Issue by tr8dr** [jenetics/jenetics#476]
I am new to Jenetics and struggling to determine how to get the underlying tree for a given individual (ProgramGene) and then print this in Lisp or infix form.   I noticed that there is a static method in the Trees class:

```
Trees.toLispString(tree)
```
But this takes a Tree object, and not sure how to get a tree from a ProgramGene.   Many Thanks!

**Comment by jenetics** [comment]
A `ProgramGene` is a tree. The following examples may help:
```java
ProgramChromosome<Double> chromosome = ...;
assert chromosome.getGene() == chromosome.getRoot();

ProgramGene<Double> gene = chromosome.getGene();
Tree<Op<Double>, ?> tree1 = gene;
Tree<?, ?> tree2 = tree1;
```

The `Trees.toLispString(Tree<?, ?>)` is currently untested and therefore still package private. But feel free to test it.

**Comment by jenetics** [comment]
In the 'r5.0.0' branch, this is part of the `io.jenetics.ext.util.TreeFormatter`.
