### ISSUE TITLE
Program Tree with custom operations

### ISSUE THREAD

**Issue by wookieJ** [jenetics/jenetics#479]
Hi, I am quite new to Jenetics and I wonder if it is possible to create ProgramChromosome with custom non-math operations like sequence in leaves or XOR-operation (occurrence of an event in child leaves). Terminals A, B, C, D, E would be for example Strings or some custom objects.

![Zrzut ekranu 2019-03-10 o 18 57 47](https://user-images.githubusercontent.com/34069409/54089176-775fc100-4366-11e9-9e20-795b6b00f51e.png)

For example events [A, B, E] or [A, C, D, E] are possible, from above graph.

I found only double support examples for Jenetics.prog library. Perhaps there is another way to solve such a problem using the jenetics library.

**Comment by jenetics** [comment]
You can define operations (and terminals) from an arbitrary type.
```java
final ISeq<Op<String>> terminals = ISeq.of(
	Const.of("A"), Const.of("B"), Const.of("C")
);
```
The only requirement is that your operations have a dedicated arity and all nodes have the same (base) type.

**Comment by wookieJ** [comment]
I had a problem with the operation declaration, but I just solve it. Thank you very much for your response.
