### ISSUE TITLE
Population creation error during evolving

### ISSUE THREAD

**Issue by Yuanyuan517** [jenetics/jenetics#483]
Hi Franz, I am using ur library to solve a job shop problem with dual resources (schedule both machine and worker to each operation of a job). I create one class called OpSchedule to represent an operation with possible machine and worker to be used, then I modify the gene to include OpSchedule instance as attribute. However, when I execute the evolving process, the population is always empty. 

Could you help me with it? Thank you very much!
The zip package of the complete code are in the [link:](https://drive.google.com/open?id=1oyU0x1yodj9jqAiKcve7qcBW-nmoS5TX)

**Comment by Yuanyuan517** [comment]
public static ISeq<MyGene> convertSchedule(Instance I) {
    		
    		ArrayList<MyGene> genes = new ArrayList<>();
    		for (OpSchedule os : I.getSchedule()) {
    			genes.add(MyGene.of(os));
    		}
    		return ISeq.of(genes);
    	}
    
    public static void main(String[] args) throws IOException {
    		
    		Main main = new Main();
    		Main.I = main.loadInstance("./instances/toyInstance5");
    		// construct initial schedule
    		// 1. create chromosome
    		ISeq<MyGene> iseq = Main.convertSchedule(I);
    		MyChromosome chromo1 =  new MyChromosome(iseq);
    
    		int populationSize = 20;
    		int crossOverN=2;
    		// 2.) Create the execution environment.
    		final Predicate<? super Genotype<MyGene>> validator = 
    				Genotype::isValid;
    		// Use EvolutionStatistics class
    		final Consumer<? super EvolutionResult<MyGene, Integer>> statistics =
    			EvolutionStatistics.ofNumber();
    		
    		Genotype<MyGene> gtf = Genotype.of(chromo1);
    		// G extends Gene<?,G>,C extends Comparable<? super C>, I think G genetype, C comparator, which is makespan, so Integer
    		Builder<MyGene, Integer> builder = Engine.builder(Main::eval, gtf);
    		builder.executor(Runnable::run);
    		builder.optimize(Optimize.MINIMUM);
    		Engine<MyGene, Integer> engine = builder.populationSize(populationSize)
    		.survivorsSelector(new TournamentSelector<>(5))
    		.offspringSelector(new RouletteWheelSelector<>())
    		.alterers(new MyMultiPointCrossover<>(0.76, crossOverN, I), new MyGaussianMutator<>(0.115))
    		.build();
    		
    		// 3.) Start the execution (evolution) and collect the result
    		int generation = 2;
    	     EvolutionResult<MyGene, Integer> result = engine
            		.stream()	// create a new, possibly infinite, evolution stream
                .limit//(Limits.byExecutionTime(duration)) // terminate the evolution after 100 generation
                (Limits.byFixedGeneration(generation)) // it will truncate the evolution stream after the given number of generations.
                .peek(statistics)
                .collect(EvolutionResult.toBestEvolutionResult());  
                 System.out.println(statistics); 
    }


MyGene class file:
import io.jenetics.Gene;

public class MyGene implements Gene<OpSchedule, MyGene> {

	private OpSchedule os;
	private static boolean debug = false;

	public MyGene(OpSchedule os) {
		this.os = os;
	}

	public OpSchedule getOs() {
		return os;
	}

	public void setOs(OpSchedule os) {
		this.os = os;
	}
	
	@Override
	public boolean isValid() {
		// to modify later
		
		return true;
	}

	@Override
	public OpSchedule getAllele() {
		return os;
	}

	@Override
	// randomly assign available machine and worker to the operation
	public MyGene newInstance() {
		// TODO Auto
		if (debug)
			System.out.println("In MyGene1 "+os);
		return MyGene.of(os.clone());
	}

	public MyGene newInstance(OpSchedule os) {
		// TODO Auto-generated method stub
		if (debug)
			System.out.println("In MyGene2 "+os);
		return MyGene.of(os);
	}

	/**
	 * Create a new random {@MyGene} with the job op, possible machine and worker sets,
	 * assign the machine and worker to the op
	 * **/
	public static MyGene of (OpSchedule os) {
		OpSchedule osCopy = os.clone();
		if (debug)
			System.out.println("In MyGene3 "+os);
		// cz if machine num is -1, it means it doesn't need machine
		if (osCopy.getMchN()!=-1)
			osCopy.setMchN(os.getRM());
		osCopy.setWorkerN(os.getRW());
		return new MyGene(osCopy);
	}
	
	public static MyGene of (OpSchedule os, int mN, int wN) {
		OpSchedule osCopy = os.clone();
		osCopy.setMchN(mN);
		osCopy.setWorkerN(wN);
		return new MyGene(osCopy);
	}

}
    import io.jenetics.Gene;
    
    public class MyGene implements Gene<OpSchedule, MyGene> {
    
    	private OpSchedule os;
    	private static boolean debug = false;
    
    	public MyGene(OpSchedule os) {
    		this.os = os;
    	}
    
    	public OpSchedule getOs() {
    		return os;
    	}
    
    	public void setOs(OpSchedule os) {
    		this.os = os;
    	}
    	
    	@Override
    	public boolean isValid() {
    		// to modify later
    		
    		return true;
    	}
    
    	@Override
    	public OpSchedule getAllele() {
    		return os;
    	}
    
    	@Override
    	// randomly assign available machine and worker to the operation
    	public MyGene newInstance() {
    		// TODO Auto
    		if (debug)
    			System.out.println("In MyGene1 "+os);
    		return MyGene.of(os.clone());
    	}
    
    	public MyGene newInstance(OpSchedule os) {
    		// TODO Auto-generated method stub
    		if (debug)
    			System.out.println("In MyGene2 "+os);
    		return MyGene.of(os);
    	}
    
    	/**
    	 * Create a new random {@MyGene} with the job op, possible machine and worker sets,
    	 * assign the machine and worker to the op
    	 * **/
    	public static MyGene of (OpSchedule os) {
    		OpSchedule osCopy = os.clone();
    		if (debug)
    			System.out.println("In MyGene3 "+os);
    		// cz if machine num is -1, it means it doesn't need machine
    		if (osCopy.getMchN()!=-1)
    			osCopy.setMchN(os.getRM());
    		osCopy.setWorkerN(os.getRW());
    		return new MyGene(osCopy);
    	}
    	
    	public static MyGene of (OpSchedule os, int mN, int wN) {
    		OpSchedule osCopy = os.clone();
    		osCopy.setMchN(mN);
    		osCopy.setWorkerN(wN);
    		return new MyGene(osCopy);
    	}
    
    }

**Comment by jenetics** [comment]
There are several problems (bugs) in your `MyChromosome` implementation.
1. Jenetics follows a functional approach where possible. This means that the used domain classes **must** be immutable. Your chromosome violates this in line 49.
```java
iSeq = Main.convertSchedule(Main.I).asList();
```
Make the `iSeq` member final and replace it with a local variable.
```java
@Override
public MyChromosome newInstance() {
	List<MyGene> seq = Main.convertSchedule(Main.I).asList();
	if (seq.isEmpty()) {
		throw new IllegalArgumentException("ISeq is empty!");
	}
	ISeq<MyGene> genes = ISeq.empty();
	for (int i=0; i<length; i++) {
		MyGene gene = seq.get(i);
		gene = gene.newInstance();
		// 2. Problem: The append creates a new instance.
		genes = genes.append(gene);
	}
	ISeq<MyGene> genes2 = shuffleGene(genes);
	ISeq<MyGene> genes3 = shuffleGene(genes2);
	return MyChromosome.of(genes3);
}
```
2. The `ISeq.append` method creates a new instance. Your `genes` sequence stayed empty.
3. The `ISeq.asList` returns an immutable view of the sequence. Fix the `shuffleGene` method as follows:
```java
public ISeq<MyGene> shuffleGene(ISeq<MyGene> genes) {
	Random rn = new Random();
	List<MyGene> tempList = new ArrayList<>(genes.asList());
    ...
}
```

After this fixes it worked for me.

PS: You owe me a beer for this analysis ;-)

**Comment by Yuanyuan517** [comment]
Wow, it works! So cool and kind you are!

I suppose Jenetics follows a functional approach mainly because of the simplicity to implement concurrency (once output is produced and returned by the function, it becomes immutable), right?

PS: I can always learn something newer (for me) from your code. I really would like to treat you a beer:) At first I will introduce Jenetics to the future paper I will write!

**Comment by jenetics** [comment]
Yes, Jenetics uses a functional style where possible and almost all data types are immutable.

You are welcome, and I looking forward to read your paper :-)
