### ISSUE TITLE
Evaluator's evaluate function is called twice per generation

### ISSUE THREAD

**Issue by sachag678** [jenetics/jenetics#501]
I'm using the Evaluator class to perform fitness evaluations on all phenotypes at one go. There seems to be an issue where it calls the evaluate() function twice per generation. Is this by design? Or is there a way I can only call it once?  The following code reproduces the issue.

    public class TestingEvaluator {
	
	static final Evaluator<ProgramGene<Double>, Double> evaluator = new Evaluator<ProgramGene<Double>, Double>() {

		@Override
		public ISeq<Phenotype<ProgramGene<Double>, Double>> evaluate(Seq<Phenotype<ProgramGene<Double>, Double>> phenotypes) {
			System.out.println("Evaluate");
			//do some fitness evaluation on phenotypes
			//update all phenotypes
			return ISeq.of(phenotypes);
		}
		
	};
	
	static double fitness(final Genotype<ProgramGene<Double>> gene) {
		return 0.0;
	}

	public static void main(String [] args) {
		
		//functions
		final Op<Double> add2 = Op.of("add2",2, v-> v[0]+v[1]);
		final Op<Double> neg = Op.of("neg",1, v-> -v[0]);

		//terminals
		final Var<Double> x1 = Var.of("x1", 0);
		final Var<Double> x2 = Var.of("x2", 1);

		final ISeq<Op<Double>> Terminals = ISeq.of(x1);
		final ISeq<Op<Double>> Operations = ISeq.of(add2, neg);
		
		int treeDepth = 2;
    	final Genotype<ProgramGene<Double>> CODEC = Genotype.of(ProgramChromosome.of(treeDepth, ch->ch.getRoot().size()<=50,  Operations, Terminals));
		
		final Engine<ProgramGene<Double>, Double> engine = Engine.builder(TestingEvaluator::fitness, CODEC)
    			.maximizing()
    			.populationSize(10)
    			.evaluator(evaluator)
    			.build();
		
		 //evolve using round robin for first set of trees
		final EvolutionResult<ProgramGene<Double>, Double> evolutionResult = engine.stream()
			    .limit(1)
                .collect(EvolutionResult.toBestEvolutionResult());
	}

    }

The output is:

Evaluate
Evaluate

**Comment by jenetics** [comment]
The observed behaviour is intended. At the beginning of every evaluation step, I evaluate the population, because for the selection stage I need the fitness values. The second evaluation call comes after the altering, where I create new individuals. The second evaluation guarantees that the population in the `EvolutionResult` is evaluated. To prevent re-evaluation of individuals, you can filter the incoming population:
```java
final ISeq<Phenotype<G, C>> phenotypes = population.stream()
    .filter(pt -> !pt.isEvaluated())
    .collect(ISeq.toISeq());
```

**Comment by sachag678** [comment]
I see. Thank you for the response. This works perfectly. I don't need to re-evaluate.
