### ISSUE TITLE
how to find the ten best result?

### ISSUE THREAD

**Issue by lightning0016** [jenetics/jenetics#507]
i use this code can only find the best result,but i want find many results order by fitness.
```
                 .collect(EvolutionResult.toBestGenotype());
```
does jenetics have this api or other method can solve it

**Comment by jenetics** [comment]
The feature of finding the _n_ best results is currently not possible. I've thinking of a similar feature in a different context. I created #508 and #509 and targeted it to v5.0.0. #509, which will result in the desired feature.

**Comment by jenetics** [comment]
If you check out the latest version of the r5.0.0 branch, you can used the following code for finding the 10 best results.
```java
final ISeq<EvolutionResult<DoubleGene, Double>> best = engine.stream()
	.limit(Limits.bySteadyFitness(50))
	.flatMap(MinMax.toStrictlyIncreasing())
	.collect(ISeq.toISeq(10));
```
