### ISSUE TITLE
parallel evolution only parallel in the beginning

### ISSUE THREAD

**Issue by TheBoegl** [jenetics/jenetics#512]
I have a question regarding the parallel computation possibilities of the fitness function.
Opposed to your issue description in #27 there is no `parallelStream()`, though the parallelization seems to work half parallel  in the beginning, i.e. 4 of 8 processors are utilized, but it degrades into only one thread or two threads calling the fitness function.
Currently, I do the following:
```
        int lambda = 20;
        int mu = 5;

        engine = Engine
            .builder(this::eval, Genotype.of(chromosomes))
            .mapping(EvolutionResult.toUniquePopulation())
            .optimize(Optimize.MINIMUM)
            .populationSize(lambda)
            .survivorsSize(0)
            .offspringSelector(new TruncationSelector<>(mu))
            .alterers(new Mutator<>(0.05))
            .build();
```
and I'm starting the evaluation like that:
```
        final EvolutionStatistics<Double, ?> statistics = EvolutionStatistics.ofNumber();

        EvolutionStream<DoubleGene, Double> stream = engine.stream();
        Genotype<DoubleGene> best = stream
            .limit(Limits.bySteadyFitness(5))
            .peek(statistics)
            .parallel()
```

Do you have any hints on how to bring me closer to utilize my machines' CPU more and, therefore, gaining evaluation speed?

**Comment by jenetics** [comment]
Jenetics is evaluating the fitness function _all_ the time, not only in the beginning. In the beginning there is only more initialization work to do. By default Jenetics uses the `ForkJoinPool.commonPool()` instance, which is using a parallelism which is equal to the number of available processors.

For a better CPU utilization you can create the `Engine` with a separate executor service or using some concurrency tweaks. This depends on your fitness function cost. I describe this tweaks in the manual chapter [1.4.1 Concurrency](http://jenetics.io/manual/manual-4.4.0.pdf#subsection.1.4.1).

**Comment by jenetics** [comment]
The `parallelStream()` method in #27 is a _typo_. I made the `Stream.parallel()` _work_.

**Comment by TheBoegl** [comment]
I know that the fitness function is and has to be evaluated every time.  In my case it is very costly (like minutes to hours).
I've read your excellent documentation a few times and thought I should get the default parallelism of all CPU threads. Thus, I created this question/issue.

**Comment by jenetics** [comment]
For a full control of the fitness evaluation, you might use the `Engine.Evaluator` interface. But the synchronization point of the GA is after each generation, where I have to wait for all fitness values to be evaluated.
