### ISSUE TITLE
Redundant use of depth variable in GP documentation

### ISSUE THREAD

**Issue by martinomburajr** [jenetics/jenetics#524]
In the [document][1]. Within the *ProgramTrees* -> *ProgramCreation* section the variable `depth` is created, but not used. Which makes it redundant.

A fix would be to replace the number 5 with a the variable `depth`

[1]: https://github.com/jenetics/jenetics/blob/master/jenetics.prog/README.adoc

**Comment by jenetics** [comment]
@martinomburajr Thank you for this hint.

**Comment by jenetics** [comment]
Update the documentation with the new _regression_ classes. Fixed on branch r5.0.0.
