### ISSUE TITLE
Selecting k out of n number with every number has different probability of selection.

### ISSUE THREAD

**Issue by ShivKJ** [jenetics/jenetics#545]
I see a method **subset** in **comb** class. Here it selects a random subset of size k from a set of size n, which means probability of any element getting picked for subset is same. 

What if we want to give more weightage to some of the numbers, that is p is **not constant** and same for all genes

**Comment by ShivKJ** [comment]
To resolve this, I have written the following code

`        
static class CustomChromosome extends BitChromosome {
		private static final long serialVersionUID = 1L;
		private final double[]    ps;

		CustomChromosome(byte[] bits, int length, double[] ps) {
			super(bits, 0, length);
			this.ps = ps;
		}

		@Override
		public CustomChromosome newInstance() {
			return new CustomChromosome(newArray(), length(), ps);
		}

		private byte[] newArray() {
			byte[] bytes = bit.newArray(length());

			Random random = getRandom();

			IntStream.range(0, length())
			         .filter(i -> random.nextInt() < toInt(ps[i]))
			         .forEach(i -> bytes[i >>> 3] |= 1 << (i & 7));

			return bytes;
		}

		@Override
		public CustomChromosome newInstance(ISeq<BitGene> genes) {
			byte[] bits = bit.newArray(genes.length());

			for (int i = genes.length(); --i >= 0;)
				if (genes.get(i).booleanValue())
					bit.set(bits, i);

			return new CustomChromosome(bits, length(), ps);
		}

		@Override
		public CustomChromosome invert() {
			final byte[] data = _genes.clone();
			bit.invert(data);

			return new CustomChromosome(data, length(), ps);
		}

		@Override
		public double getOneProbability() {
			throw new UnsupportedOperationException("With class="
			+ CustomChromosome.class.getSimpleName()
			+ ", this function is undefined as"
			+ " probability is now a function of grid location.");
		}
	}
`

**Comment by jenetics** [comment]
The `subset` function doesn't let you define probabilities for given elements. But maybe you can take a detour over a `DoubleChromosome`.
```java
public static void main(final String[] args) {
    // Your probabilities.
    final double[] p = new Random().doubles()
        .limit(100)
        .toArray();

    final Codec<int[], DoubleGene> codec = Codecs
        .ofVector(DoubleRange.of(0, 1), p.length)
        .map(v -> toSubset(v, p));
}

private static int[] toSubset(final double[] v, final double[] p) {
    return IntStream.range(0, v.length)
        .filter(i -> v[i] < p[i])
        .toArray();
}
```

**Comment by ShivKJ** [comment]
But it does not ensure that subset will be of size **k** always.

**Comment by jenetics** [comment]
Yes, that's correct. One Idea is to calculate some other metric instead: selection strength. The return the *k* indices with the best selection strengths.
```java
private static int[] toSubset(final double[] v, final double[] p, final int k) {
    // Selection strength array.
    final double[] s = IntStream.range(0, v.length)
        .mapToDouble(p[i] - v[i])
        .toArray();

    // Sort indexes in ascending order and returning the k best results.
    final int[] indices = IndexSorter.sort(s);
    array.revert(indices);
    return Arrays.copyOf(indices, k);
}
```
Be aware that the example uses some _internal_ API, which is not exposed/supported officially (`IndexSorter` and `array`), but it should illustrate the idea.
