### ISSUE TITLE
Custom CrossOver Mutator for finding the shortest path in a maze.

### ISSUE THREAD

**Issue by zollen** [jenetics/jenetics#549]
I want to use Jenetics to find the shortest path from S  to E as following
```

-------------
| S         |
|  *** ***  |
|         E |
-------------


```
Clearly each position has a limited number of possible moves because there are walls and obstacles in the maze. Therefore I must write my own crossover function. 

1. Each MazeGame object generates a random path from S to E.
2. The MazeGame class has two methods to facilitate crossover and mutation operations.
MazeGame.mutate(n) // truncate the last n moves and randomly regenerate n+1 to E
MazeGame.crossover(MazeGame [] games) // approximate the path from parents games

**Question**
Is it possible to utilize any existing Jenetics CrossoverMutator, Mutator, Alterer for easy integration of game.mutate(n) and game.crossover(games)?
**OR**
Do I need to write my own custom CrossoverMutator?

**Comment by zollen** [comment]
Work in Progress.....
```
final Codec<MazeGame, AnyGene<MazeGame>> CODEC = Codecs
				.ofScalar(MazeAgent::newInstance).map(MazeAgent::random);
		
		final Engine<AnyGene<MazeGame>, Integer> engine = Engine
				.builder(MazeAgent::score, CODEC)
					.populationSize(8000)
					.optimize(Optimize.MAXIMUM)
					.offspringSelector(new StochasticUniversalSelector<>())
		//			.alterers(new Mutator<>(0.01), new MeanAlterer<>(0.5))
					.build();
```

I am still unsure about how to implement the Mutator/Alterer with my existing MazeGame class.

**Comment by zollen** [comment]
Nevermind. I wrote my own custom Mutator and it worked.

**Comment by jenetics** [comment]
:+1:
