### ISSUE TITLE
NOOB: Can't run examples

### ISSUE THREAD

**Issue by thealy** [jenetics/jenetics#55]
Hi, just git cloned and believe I followed the instructions correctly to use griddle to build jars- no errors were reported. I then cd to /Users/thealy/Downloads/jenetics/org.jenetics.example/src/main/scripts and ran ./run-examples.sh I get these errors:

readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
readlink: illegal option -- f
usage: readlink [-n] [file ...]
readlink: illegal option -- f
usage: readlink [-n] [file ...]
Error: Could not find or load main class org.jenetics.example.Knapsack
Error: Could not find or load main class org.jenetics.example.OnesCounting
Error: Could not find or load main class org.jenetics.example.RealFunction
Error: Could not find or load main class org.jenetics.example.StringGenerator
Error: Could not find or load main class org.jenetics.example.TravelingSalesman

I tried a few guesses as to a command line argument, but none worked. Something stupid I know,
but can someone help me to get started here?

Thanks.

**Comment by jenetics** [comment]
OK, the `run-example.sh` script only works with the downloaded package zip file. The jars are then in the right directory and can be found by the script.

Alternatively you can build the package yourself. Call
* `./gradlew packaging`: this is an _internal_ Gradle task, which create the Jenetcis package (the unit tests are also executed).

It will create a `build/package/jenetics-<version>/scripts` directory where the test scripts are copied. Starting the script from there should work.

**Comment by thealy** [comment]
OK, ./gradlew packaging ran ok and created the scripts directory, but the result was the same errors. I managed to run it with a manually-crafted string of java -cp ....

**Comment by jenetics** [comment]
The problem was the `readlink` command, which worked on Linux but not on Mac. I replaced it with a portable version.

**Comment by thealy** [comment]
Thank you very much Franz. I look forward to working with Jenetics.

-Terry
