### ISSUE TITLE
Creating Phenotype instance with a double instead of a C

### ISSUE THREAD

**Issue by 942u3895hjf** [jenetics/jenetics#559]
Hello,

First, thanks for this wonderful project! 

I have a custom Evaluator based on ConcurrentEvaluator that runs the fitness function via a custom java Executor on Apache Hadoop. Our fitness function is extremely heavy.

Inside the executor i serialize and save the Genotype to Apache HDFS, where it is later retrieved to be run inside the cluster. The double the fitness function returns is also stored back to HDFS, and when the generation is finished, i load the doubles back into the Evaluator.PhenotypeFitness instance that was still waiting for everything to complete.

This is all well, but i have trouble understanding how i can create the Phenotype with the Double, instead of the C. In the original PhenotypeFitness there is:

`
  Phenotype<G, C> phenotype() {
    return phenotype.withFitness(fitness);
  }
`

fitness is a C here, but i cannot just convert my Double to a C, i don't even know what the C type means, probably Comparable, but i cannot cast the Double to that either, for obvious reasons. Generics is not my strong point obviously, especially the amount of it in Jenetics is confusing to me.

Knowing the fitness function returns a Double, i searched for invocations of it, looking to see how Jenetics turns the Double somehow magically into a C.

So, how does Jenetics do it, and how should i my Double version of the above method?

Many thanks,
Markus

**Comment by jenetics** [comment]
Hi,
for creating a new `Phenotype` you need a `Genotype` and the (optional) fitness value.

```java
final Genotype<DoubleGene> gt = ...;
final long generation = ..;
final Double fitness = ...;
final Phenotype<DoubleGene, Double> pt = Phenotype.of(gt, generation, fitness);
```

So, if you want to create a new phenotype you also need the genotype from where the fitness value was calculated.

PS: Thank you for finding the library valuable.

**Comment by 942u3895hjf** [comment]
Hello,

`final Genotype<DoubleGene> gt = phenotype.getGenotype();`

throws an error:

`incompatible types: io.jenetics.Genotype<G> cannot be converted to io.jenetics.Genotype<io.jenetics.DoubleGene>`

but

`final Phenotype pt = Phenotype.of(phenotype.getGenotype(), phenotype.getGeneration(), score);`

compiles cleanly and runs nicely.

I am stunned by being able to pass the Double score to the C type here. While passing a Double to:
`
  static void setFitness(C fitness) { this.fitness = fitness; }
`

throws the famous:
`double cannot be converted to C`
error. I feel stupid.

Anyway, thank you very much!

Markus

**Comment by jenetics** [comment]
It seems you are lost in Java's (generic) type system. If you can give me a more actual code, it would be easier for me to give you some guidance.
