### ISSUE TITLE
How to model f(x, y) where x, y are different type

### ISSUE THREAD

**Issue by arisliang** [jenetics/jenetics#56]
for example x is integer, y is double.
Must we model x and y as same type?

**Comment by jenetics** [comment]
Yes, the gene type must be the same. If you have a function f(int, double), you have to define a double genotype and do an int conversion (rounding) for the int parameter.

**Comment by arisliang** [comment]
As there're two options, first is 1 chromosome, with 2 genes, second is 2 chromosome, each with 1 gene. The second one is out, because chromosome must be the same type in a genotype according to the user manual. How about the first option? If I recall correctly, user manual doesn't mention all genes must be the same type inside a chromosome. Is it possible to define a chromosome with 1 int type, 1 long type, 1 double type?

Or let's say, the target function is f(long, double)? Casting double to long may result in data loss. Therefore, straight casting may not work.

**Comment by jenetics** [comment]
The restriction of the same gene type for all chromosomes holds for all chromosome combinations. So the only easy way would be to cast the double value. Do you really need the whole long range? The double value can be safely used for values up to 2^52.
If you need the complete long domain, you have to implement your own
* LongDoubleGene
* LongDoubleChromosme
* LongDoubleMutator/Selector

classes.

**Comment by arisliang** [comment]
It's possible to break the whole long domain to smaller pieces, but it might be more straight-forward to treat it as long.

One example i can think of is milliseconds for date. Instead of having one gene to represent time (long milliseconds), it maybe breakdown to year/month/.../etc, into several genes of int type.

I guess break it down would still be easier than to roll our own domain/operator classes. Implementing own domain classes is probably fine, but own operator classes may be non-trivial.

**Comment by jenetics** [comment]
Splitting the field is one solution. But if the long value represents a date value, I don't think you need the whole long range. With the whole long range you can express date values form -999999999-01-01 to +999999999-12-31 (due to the new Java LocalDate class). Converting a double to a long value, your date will be save (roughly) between the year -14000000 and +14000000.

Implementing own domain classes is not that complicated ;-)

**Comment by arisliang** [comment]
Yeah, how about own operator classes?:)

**Comment by arisliang** [comment]
Actually come to think of it, it might be a good idea to implement own domain class, by composing simple valued domain classes. It's neater solution in the sense that no casting is needed, probably resulting in slightly better performance, and it encapsulates type requirement in domain class, which is transparent for the caller, rather than probably get casted whenever needed by framework, and cast back for caller.
Is there an example of such a composite domain class implementation?

**Comment by jenetics** [comment]
You might have a look at the `org.jenetics.engine.Codec` interface. This interface is meant to decouple the problem encoding, needed by the GA, from the domain classes, needed by your fitness functions. See section 6.2 in the manual. The restriction of the single gene type persists.

**Comment by arisliang** [comment]
I had a bit trouble understanding org.jenetics.engine.Codec interface section, which is quite short and doesn't have an example (other than a code snippet). Comparatively, real/vector function has quite good example.

It would be nice to have a simple and working example for optimizing f(int, long, double) using the custom domain approach, if implementing custom domain class wouldn't take too much time.

**Comment by jenetics** [comment]
I think you are expecting to much. The `Codec` interface allows the decoupling of the domain code from the GA code:
```java
public class CodecExample {

	// The domain class
	final static class Tuple {
		final int _1;
		final long _2;
		final double _3;

		Tuple(final int v1, final long v2, final double v3) {
			_1 = v1;
			_2 = v2;
			_3 = v3;
		}
	}

	// The fitness function. No need to know anything about GAs. Decoupling of
	// the problem function from the GA usage.
	static double f(final Tuple param) {
		return param._1 + param._2 + param._3;
	}

	// The encoding/decoding of the problem domain is defined at ONE place.
	static Codec<Tuple, DoubleGene> codec(
		final IntRange v1Domain,
		final LongRange v2Domain,
		final DoubleRange v3Domain
	) {
		return Codec.of(
			Genotype.of(
				DoubleChromosome.of(DoubleRange.of(v1Domain.getMin(), v1Domain.getMax())),
				DoubleChromosome.of(DoubleRange.of(v2Domain.getMin(), v2Domain.getMax())),
				DoubleChromosome.of(v3Domain)
			),
			gt -> new Tuple(
				gt.getChromosome(0).getGene().intValue(),
				gt.getChromosome(1).getGene().longValue(),
				gt.getChromosome(2).getGene().doubleValue()
			)
		);
	}

	public static void main(final String[] args) {
		// The domain of your fitness function.
		final IntRange domain1 = IntRange.of(0, 100);
		final LongRange domain2 = LongRange.of(0, 1_000_000_000_000L);
		final DoubleRange domain3 = DoubleRange.of(0, 1);

		// The problem domain encoder/decoder.
		final Codec<Tuple, DoubleGene> codec = codec(domain1, domain2, domain3);

		final Engine<DoubleGene, Double> engine = Engine
			.builder(CodecExample::f, codec)
			.build();

		final Genotype<DoubleGene> gt = engine.stream()
			.limit(100)
			.collect(EvolutionResult.toBestGenotype());

		final Tuple param = codec.decoder().apply(gt);
		System.out.println(param);
	}
}
```

You still have to write the encoding/decoding code.

**Comment by arisliang** [comment]
I enjoy this minimal example with three different types of ranges into it (and documented too!). Appreciate your time for writing it.
It helps me to understand by illustrating both custom domain class and Codec. More encapsulation gives a scalable OO feel.

**Comment by jenetics** [comment]
> What about f(int, String),or other different types?
> I have tried AnyGene, other types can evolution well expects String type.
> Simplify this problem, how can I get a target String "HelloWorld" with CharacterGene?

@IneverStop, I described this problem in #165.  The current desing of Jenetics doesn't allow a clean solution. A workaround is implemented in the [MixedGenotype](https://github.com/jenetics/jenetics/blob/master/jenetics.example/src/main/java/io/jenetics/example/MixedGenotype.java) example.
