### ISSUE TITLE
Mixed genotype with partial mean alterer

### ISSUE THREAD

**Issue by arkaelh** [jenetics/jenetics#562]
I have an issue similar to #116. I'm having difficulties using relevant Alterers with a MixedGenotype. Even if this kind of usage isn't intended, I don't see how a problem like the following could be converted to a problem with a single type of Gene. 

`private static final Genotype ENCODING = Genotype.of(`
   `(Chromosome) DoubleChromosome.of(0, 4, 5),`
   `(Chromosome) CharacterChromosome.of(['r', 'g', 'b'], 1)`
`);`

We could imagine the first chromosome as dimensions of a tool and the second as its colour, which can only take 3 values. 
How could I apply a MeanAlterer on the double chromosome and a non-numerical alterer on the character chromosome ? I've looked at the PartialAlterer and the Alterer.forChromosome method (#372), but the main problem is that the MeanAlterer is not able to interpret the first chromosome as a chromosome extending the Mean interface required.

**Comment by jenetics** [comment]
You can try it like in the following example:
```java
public class Example {

    static final class Tool {
        final double[] dimensions;
        final char color;
        Tool(final double[] dimensions, final char color) {
            this.dimensions = dimensions;
            this.color = color;
        }

        static Tool of(final Genotype<DoubleGene> gt) {
            final double[] dims = gt.getChromosome(0)
                .as(DoubleChromosome.class)
                .toArray();

            final char c;
            switch (gt.get(1, 0).intValue()) {
                case 0: c = 'r'; break;
                case 1: c = 'g'; break;
                default: c = 'b'; break;
            }

            return new Tool(dims, c);
        }
    }

    static final Problem<Tool, DoubleGene, Double> PROBLEM = Problem.of(
        tool -> 1.0,
        Codec.of(
            Genotype.of(
                DoubleChromosome.of(DoubleRange.of(0, 4), 5),
                DoubleChromosome.of(DoubleRange.of(0, 3))
            ),
            Tool::of
        )
    );

    public static void main(final String[] args) {
        final Engine<DoubleGene, Double> engine = Engine.builder(PROBLEM)
            .alterers(new MeanAlterer<>())
            .build();

        EvolutionResult<DoubleGene, Double> result = engine.stream()
            .limit(100)
            .collect(EvolutionResult.toBestEvolutionResult());

        System.out.println(result.getBestPhenotype());
    }
}
```
