### ISSUE TITLE
Collect and print EvolutionStatistics at each generation

### ISSUE THREAD

**Issue by arisliang** [jenetics/jenetics#58]
Is there anyway to collect and print EvolutionStatistics at each generation instead of at termination? Seeing the progress of the evolution, could be useful when the evolution is long-running.

**Comment by jenetics** [comment]
This is easily possible using the `Stream.peek` method:
```java
final EvolutionStatistics<Double, ?>
    statistics = EvolutionStatistics.ofNumber();

final Phenotype<DoubleGene, Double> best = engine.stream()
    .limit(100)
    .peek(statistics)
    .peek(r -> System.out.println(statistics))
    .collect(toBestPhenotype());
```

**Comment by arisliang** [comment]
Thanks, it works.
