### ISSUE TITLE
Unnecessary restriction on Var names added in 5.0

### ISSUE THREAD

**Issue by tschwenke7** [jenetics/jenetics#584]
I am writing a program which uses Jenetics to perform Symbolic Regression .In my program, I had a .csv parser which, amongst other things, would create `Var`s using the `Var.of(name, index)` method, taking the column header title from the csv to be the `name`. 

It worked fine when we were using Jenetics 4.4,  but since upgrading to 5.0, the `name` property now must past the `isJavaIdentifierStart(codepoint)` method in standard Java library rather than just `requireNotNull`. 

Is there a reason for this change? Many datasets now no longer work, due to having column headings with `-` characters, `.`s or starting with numbers, e.g. a dataset with column headings like "Longitudinal-position-of-the-center-of-buoyancy", "Prismatic-coefficient" etc.

This seems like an unnecessary restriction which hampers the usefulness of the Var class when printing out the best solution after a search. Could this restriction be removed, or is there an important reason it was added?

**Comment by jenetics** [comment]
The name of a `Var` allows to also define it's position/index: `x[1]` or `y[0]`. To make the index parsing easier, I desided to restrict the var name to a valid Java identifier. I hadn't your specific use case in mind, when I did the change. This restriction might be overly strong.
As a workaround you have to implement your own name mangling. I'm not sure yet whether to relax this restriction in a later version; have to think about it.

**Comment by tschwenke7** [comment]
Here's the solution I came up with for now, mainly adding underscores where necessary to make it valid:

```public class JavaIdentifierConverter {
    /**
     * Since upgrading to Jenetics 5.0, all Var names have to be valid Java identifiers
     * or the program will crash. Therefore, if we are to supply labels as Var names,
     * we must first check that they fit Java valid identifier standards.
     * This method achieves that standard by
     * - removing the UTF-8 meta character if it's found,
     * - adding an underscore to the beginning if the start character is invalid
     * - replacing any illegal characters with underscores
     * @param s - the String to convert
     * @return a modified version of that String which will pass as a valid Java variable name
     */
    public static String convertToJavaValidIdentifier(String s) {
        //remove meta-character which sometimes appears at the front of a file to label as UTF-8
        String UTF8_BOM = "\uFEFF";
        if (s.startsWith(UTF8_BOM)) {
            s = s.substring(1);
        }

        //if first character is not a valid identifier, add an underscore in front
        if(!Character.isJavaIdentifierStart(s.charAt(0))){
            s = "_" + s;
        }

        //replace any illegal characters with underscores
        for(int i=1; i < s.length(); i++){
            StringBuilder myName = new StringBuilder(s);
            if(!Character.isJavaIdentifierPart(s.charAt(i))){
                myName.setCharAt(i, '_');
            }
            s = myName.toString();
        }
        return s;
    }
}```
