### ISSUE TITLE
Problem Transformation

### ISSUE THREAD

**Issue by wangxiangtao** [jenetics/jenetics#59]
Hi , 

I have a problem that think can use GA to solve it, but don't know how to transform the problem via Jenetics. 

Suppose I have 5 Ads and want to display them on 5 different websites within 24 hours with a limited cost 300$.  (assume 15$ per hour)

I already have a fitness function to predict number of user clicks and want to maximise it via GA.  
The idea is try different strategy of the AD distribution to get the maximum user clicks 

<img width="955" alt="screen shot 2015-08-27 at 11 01 27 am" src="https://cloud.githubusercontent.com/assets/6140162/9511639/4b1f88f6-4cab-11e5-95f4-4cef4a844cb1.png">
  
There are several constrains that I do not know how to use Jenetics to add. 
1,  for each website.   the end time should bigger than start time
2,  (the summed during time from 5 website * 15$ per hour)  < 300$
3,  All the 5 ads should be displayed on 5 website.  

So it is actually a simple problem but have many constrains.   Basically i want to set 15 genes (3 genes per website,  include starttime ,endtime ,and number of AD )  there are some dependency between genes in one chromosome. 

Appreciate if can explain how to use Jenetics to do it ? 
Thanks

**Comment by jenetics** [comment]
The problem looks like a variation of the Knapsack problem. I don't think there is an encoding which will produce no _invalid_ individuals. A simple encoding might look like the following:

```java
Genotype<IntegerGene> gt = Genotype.of(
    // Chromosomes for website one:
    // 24 hourly time slots of ad number.
    IntegerChromosome.of(IntRange.of(0, 5), 24),

    // Chromosomes for website two:
    // 24 hourly time slots.
    IntegerChromosome.of(IntRange.of(0, 5), 24)
);

// Return the ad number of time-slot 0 (0:00 - 1:00) of web site 1.
gt.get(0, 0);

// Return the ad number of time-slot 14 (14:00 - 15:00) of web site 2.
gt.get(1, 14);
```

The fitness function can return zero for invalid genotypes.

**Comment by wangxiangtao** [comment]
Do you mean i should use multiply chromosomes to represent a solution (one row in the excel above) , instead of one chromosome with 15 genes inside ? 

If use multiply chromosomes .  then use 5 chromosomes to represent 5 websites,   and each chromosome consist of 3 genes (No. of Ad , start time and end time ) , right ?

How do i indicate the  start time and end time by using the code below ?
IntegerChromosome.of(IntRange.of(0, 5), 24) 

Because I want one Ad can continuously display on one website.  but for the code above,  think it will split the time , and  one Ad may display with intervals.   Actually , I only need a start time and end time. 

Another concern is  how to make sure one Ad don't be displayed on multiply websites at the same time ? 

Thanks

**Comment by jenetics** [comment]
I'd tried to find a solution by simplifying the problem. I also don't
think there is an encoding which will not create invalid individuals. A
good starting point is to create an object-model, which represents a
valid solution of your problem. Then you can start searching a proper
encoding.

To minimize the number of invalid individuals, you can also try to find
a repair-function, which converts an invalid solution into a valid one.
A simple example of such a repair-strategy could be used for the
encoding of a (int, double) tuple. Since the library only allows Genes
of the same type, your encoding would look like

```java
final Codec<Tuple, DoubleGene> codec = Codec.of(
    Genotype.of(DoubleChromosome.of(0, 10, 2)),
    gt -> new Tuple(
        (int)Math.round(gt.get(0, 0).doubleValue()), 
        gt.get(0, 1).doubleValue())
)
```

The repair-function in this example is the `Math.round` function.

I hope this helps you finding a proper encoding for your actual problem.
