### ISSUE TITLE
Weird fitness drops with quick recovery

### ISSUE THREAD

**Issue by ZagButNoZig** [jenetics/jenetics#595]
Hello, 
I have implemented a GA which evolves neural networks to play the game of snake. Each genotype is simply a DoubleChromosome representing the weights of each network. The network is then playing a few games of snake to calculate an accurate score. Weirldy sometimes the average and max fitness drops and "recovers" after a few generations. 
![weird](https://user-images.githubusercontent.com/39175622/67160453-2333ab00-f351-11e9-88be-d109d1b25697.png)
This seams to happen more often when I have a smaller population size and thus more generations / second. 
```  
 final Engine<DoubleGene, Integer> engine = Engine
                .builder(SnakeEvolution::eval, codec)
                .populationSize(300)
                .alterers(new Mutator<>(.05), new MultiPointCrossover<>(.1))
                .executor(executor)
                .selector(new TournamentSelector<>())
                .build();
```
This is the engine code that I am using and the selector does not seem to impact this event.
Any idea why the best solution seems to be lost?

**Comment by jenetics** [comment]
It looks like that the `maximalPhenotypeAge` comes into play. Its default value is 70, which seems to correspond with the first fitness drop. The engine _kills_ every phenotype older than 70 generations. For your current setup using the `EliteSelector` might solve the problem.

```java
final Engine<DoubleGene, Integer> engine = Engine
	.builder(SnakeEvolution::eval, codec)
	.populationSize(300)
	.alterers(new Mutator<>(.05), new MultiPointCrossover<>(.1))
	.executor(executor)
	.offspringSelector(new TournamentSelector<>())
	.survivorsSelector(new EliteSelector<>())
	.build();
```

**Comment by ZagButNoZig** [comment]
Changing the `maximalPhenotypeAge` reduces the spikes. The `EliteSelector` does not. I was wondering if it was bad or not because it increases exploration.

**Comment by jenetics** [comment]
Interesting, thank you for your feedback.
