### ISSUE TITLE
The constraint doesn't work.

### ISSUE THREAD

**Issue by zhuyuxing** [jenetics/jenetics#596]
`
import com.google.common.collect.Lists;
import io.jenetics.Genotype;
import io.jenetics.IntegerChromosome;
import io.jenetics.IntegerGene;
import io.jenetics.Phenotype;
import io.jenetics.engine.*;
import io.jenetics.util.ISeq;
import io.jenetics.util.IntRange;

import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.stream.IntStream;

public class GaBoxDesign3Algorithm 
{
    public static List<ItemProperty> items;
    public static int boxPropertyNum = 5;
    public static int maxBoxSize = 500;
    public static int maxBoxWidth = 500;
    public static int maxBoxLength = 500;
    public static int maxBoxHeight = 500;

    public static int maxItemSize = 0;

    private static Integer eval(int[] gt) {

        int maxSize = gt.length;
        List<BoxProperty> cubes = Lists.newArrayList();
        for(int i = 0; i < maxSize; i ++){
            ItemProperty candidateItem = items.get(gt[i]);
            if(i != 0 && gt[i] < gt[i-1]){
                // debug check
                int k = 0;
            }
            BoxProperty cube = new BoxProperty(String.valueOf(i), candidateItem.length
                    ,candidateItem.width,candidateItem.height,0);
            cubes.add(cube);
        }

        List<ItemProperty> copyItems = Lists.newArrayList(items);
        int diffArea = 0;
        for(BoxProperty boxProperty: cubes){
            double volume = boxProperty.getVolume();
            List<ItemProperty> candidateItems = Lists.newArrayList();
            for(ItemProperty itemProperty: copyItems){
                if(volume>= itemProperty.getVolume()
                        && compareBox2Item(boxProperty,itemProperty)
                ){
                    candidateItems.add(itemProperty);
                    double tempArea =
                            boxProperty.getArea()-itemProperty.getArea();
                    diffArea = (int)tempArea + diffArea;
                }
            }
            copyItems.removeAll(candidateItems);
        }
        for(ItemProperty itemProperty: copyItems){
            diffArea += 2*(Math.abs(itemProperty.length - maxBoxLength)
                    + Math.abs(itemProperty.width - maxBoxWidth)
                    + Math.abs(itemProperty.height - maxBoxHeight)
            );
        }
        return
                diffArea;
    }
    private static boolean compareBox2Item(BoxProperty boxProperty, ItemProperty itemProperty){
        if(boxProperty.length >= itemProperty.length
                && boxProperty.width >= itemProperty.width
                && boxProperty.height >= itemProperty.height
        ){

            return true;

        }
        return false;
    }

    /**
     * @param x input
     * @return output
     */
    private static int[] normalize(final int[] x){
        return
                Arrays.stream(x)
                        .boxed()
                        .map(index -> items.get(index))
                        .sorted(Comparator.comparing(ItemProperty::getVolume))
                        .map(item -> items.indexOf(item))
                        .mapToInt(Integer::valueOf)
                        .toArray();
    }

    public static void main(final String[] args){
        items= Lists.newArrayList();
        items.add(new ItemProperty("1",1,1,1));
        items.add(new ItemProperty("2",100,100,100));
        items.add(new ItemProperty("3",200,200,200));
        items.add(new ItemProperty("4",300,300,300));
        items.add(new ItemProperty("5",400,400,400));
        items.add(new ItemProperty("6",450,450,450));
        items.add(new ItemProperty("7",500,500,500));
        maxItemSize = items.size();
        Codec<int[], IntegerGene> codec = Codecs
                .ofVector(IntRange.of(0, maxItemSize - 1), boxPropertyNum)
                .map(GaBoxDesign3Algorithm::normalize);
        final Constraint<IntegerGene, Integer> constraint = Constraint.of(
                pt -> isValid(codec.decode(pt.getGenotype())),
                (pt, g) -> {
                    final int[] r = normalize(codec.decode(pt.getGenotype()));
                    return newPT(r, g);
                }
        );

        // 3.) Create the execution environment.
        Engine<IntegerGene, Integer> engine = Engine
                .builder(GaBoxDesign3Algorithm::eval,
                        codec
                )
                .constraint(constraint)
                .minimizing()
                .populationSize(1000)
                .build();

        // 4.) Start the execution (evolution) and
        //     collect the result.
        EvolutionStatistics<Integer,?> statistics = EvolutionStatistics.ofNumber();
        Phenotype<IntegerGene,Integer> result = engine.stream()
                .limit(1000)
                .peek(statistics)
                .collect(EvolutionResult.toBestPhenotype());

        System.out.println(statistics);
        System.out.println(result.getFitness());
        System.out.println(result.getGenotype());
    }
    private static boolean isValid(final int[] x) {
        ItemProperty currentBox = null;
        ItemProperty preBox = null;
        boolean check = true;
        for (int index : x) {
            currentBox = items.get(index);
            if (preBox == null) {
                preBox = currentBox;
                continue;
            }
            if (preBox.getVolume() > currentBox.getVolume()
            ) {
                check = false;
                break;
            }
            preBox = currentBox;
        }
        return check;
    }

    private static Phenotype<IntegerGene, Integer> newPT(final int[] r, final long gen) {
        final Genotype<IntegerGene> gt = Genotype.of(
                IntegerChromosome.of(
                        IntStream.of(r).boxed()
                                .map(v -> IntegerGene.of(v, IntRange.of(0, maxItemSize - 1)))
                                .collect(ISeq.toISeq())
                )
        );
        return Phenotype.of(gt, gen);
    }
    static class ItemProperty {

        public String itemId;
        public double length = 0;
        public double width = 0;
        public double height = 0;
        public ItemProperty(String b,double l,double w,double h){
            this.itemId = b;
            this.length = l;
            this.width = w;
            this.height = h;
        }
        public double getVolume(){
            return length*width*height;
        }
        public double getArea(){
            return 2*(this.height*this.width + this.height*this.length + this.width*this.height);
        }
    }
    static class BoxProperty {
        public String boxId;
        public double length;
        public double width;
        public double height;
        public BoxProperty(String b,double l,double w,double h,int k){
            this.boxId = b;
            this.length = l;
            this.width = w;
            this.height = h;
        }
        public double getVolume(){
            return this.length*this.width*this.height;
        }
        public double getArea(){
            return 2*(this.height*this.width + this.height*this.length + this.width*this.height);
        }
    }
}
`
The result is [[[0],[4],[2],[1],[3]]] ,cost is 300.
But I have the constraint (isValid and normalize) to limit it, do you have any idea of it?

**Comment by zhuyuxing** [comment]
Have solved it.

private static Phenotype<IntegerGene, Integer> newPT(final int[] r, final long gen) {
        Genotype<EnumGene<BoxProperty>> g = Genotype.of(new PermutationChromosome<>(
                    IntStream.range(0,r.size()).mapToObj(i -> EnumGene.of(i, r)).collect(ISeq.toISeq()))
        );
        return Phenotype.of(g,gen);
}

**Comment by jenetics** [comment]
OK, thanks for the feedback.

PS: I was a little bit busy lately.
