### ISSUE TITLE
Use External features (MOEA) from jenetics.ext not accessible

### ISSUE THREAD

**Issue by Sultan91** [jenetics/jenetics#598]
Hello, thank you for jenetics.io !
I am having an issue with importing external (`jenetics.ext`) package while using jenentics package as maven dependency. It appears that jenetics.ext doesnt exist in maven repo,

**Comment by jenetics** [comment]
Thats weired. I could download the library, at least from the web-page: https://search.maven.org/artifact/io.jenetics/jenetics.ext/5.0.1/jar

**Comment by Sultan91** [comment]
Ah right, I am sorry. I thought jenetics lib will itself contain external library
