### ISSUE TITLE
`Recombinator` performs `recombine` on an individual with itself

### ISSUE THREAD

**Issue by varunnayak26** [jenetics/jenetics#599]
I'm using @beatngu13's [knapsack-problem ](https://github.com/beatngu13/knapsack-problem) implementation using jenetics to illustrate this bug. To simplify the problem, I kept the population size to 2 knapsacks, set the offspring fraction to 1.0 to guarantee that all offspring's are selected to be altered. I re-implemented the Crossover classes to print the selected individuals to console. This is available in [bug/recombinator-selecting-individual](https://github.com/varunnayak26/knapsack-problem/tree/bug/recombinator-selecting-individual) branch of the forked repository.

```
	@Test
	void printing_individuals_for_recombination_to_console() throws Exception {
		final Engine<ItemGene, Vec<int[]>> knapsackEngine = Engine.builder(new ProfitFitness(), new KnapsackCodec()) //
				.executor(Runnable::run) // Single-threaded for reproducibility.
				.populationSize(2) //
				.offspringFraction(1.0) //
				.selector(NSGA2Selector.ofVec()) //
				.alterers(new CustomSinglePointCrossover<>(1.0)) //
				.constraint(new WeightAndItemsConstraint()) //
				.build();

		final EvolutionStatistics<Vec<int[]>, ?> stats = EvolutionStatistics.ofComparable();

		RandomRegistry.with(new Random(0L), // Fixed seed for reproducibility.
				rand -> knapsackEngine.stream() //
						.limit(Limits.byFixedGeneration(1)) //
						.peek(stats) //
						.collect(MOEA.toParetoSet(IntRange.of(1, 50))));

		System.out.println(stats);
	}
```

The log from `CustomCrossover` class which prints generation count and the indices of the individuals to be altered shows:
```
generation=1, individuals = [0, 1]
generation=1, individuals = [1, 1]
generation=2, individuals = [0, 1]
generation=2, individuals = [1, 1]
```
From this log, it can be deduced that the `Recombinator` is performing recombination of individual at index 1 with itself. Isn't this inefficient?

**Comment by jenetics** [comment]
Isn't this a consequence of the low population size and the Knapsack configuration? Will this _problem_ disappear with a more _realistic_ setup?

**Comment by varunnayak26** [comment]
As a matter of fact, it is. However, in theory, shouldn't the `Recombinator` work for any population size greater than or equal to 2?
I noticed that even with a population size of 50 and an offspring fraction of 0.5, it sometimes still produced one such instance every generation where an individual is recombined with itself. It seems that with the current implementation, there is always a chance (smaller as the population size is increased), this situation occurs.
At [Retest](https://retest.de/) we use Jenetics to implement our genetic algorithm with the goal of optimizing test suites for multiple objectives. The population we currently deal with is relatively small. The altered offsprings are evaluated each time which is expensive. Hence, we would like to avoid this situation.

**Comment by jenetics** [comment]
I had a close look at the code, and now I see your point. The function, which creates the indexes of the individuals to be recombined, indeed creates duplicate entries. This is because of replacing the first array element with the index of the _master_ individual. A simple fix can solve this problem.

```java
// Recombinator.java
final MSeq<Phenotype<G, C>> pop = MSeq.of(population);
final int count = indexes(random, population.size(), _probability)
    .mapToObj(i -> individuals(i, population.size(), order, random))
    .mapToInt(ind -> recombine(pop, ind, generation))
    .sum();
//...
static int[] individuals(
    final int index,
    final int size,
    final int order,
    final Random random
) {
    final int[] ind = subset(size, order, random);

    // Find the correct slot for the "master" individual.
    int i = 0;
    while (ind[i] < index && i < ind.length - 1) {
        ++i;
    }
    ind[i] = index;

    return ind;
}
```
I _just_ changed the `individuals` function.

**Comment by jenetics** [comment]
Merged into r5.1.0 branch.
