### ISSUE TITLE
problem with IDE integration for eclipse

### ISSUE THREAD

**Issue by syntheticperson** [jenetics/jenetics#6]
I tried to implement the IDE integration for eclipse:

cd build-dir
./gradlew eclipse

When I try to import the project into eclipse, I get multiple errors.
One of them is:

/org.jenetics/src/main/java/org/jenetics/PermutationChromosome.java

line 137:

		final ISeq<EnumGene<T>> genes = IntStream.range(0, alleles.length())
			.mapToObj(index -> new EnumGene<>(index, alleles))
			.collect(toMSeq())
			.shuffle(RandomRegistry.getRandom())
			.toISeq();

error:

Multiple markers at this line
	- Type mismatch: cannot convert from ISeq<EnumGene<capture#9-of ? 
	 extends T>> to ISeq<EnumGene<T>>
	- Line breakpoint:PermutationChromosome [line: 137] - of(ISeq<? extends 
	 T>)

What am i missing?

thanks

**Comment by jenetics** [comment]
You are right, I tried to open the project with Eclipse and got the same probleme as you described. 
I do the development work for Jenetics with IntelliJ IDEA and I compile it on the command line with Gradle. Neither IntelliJ nor the command line build produces an error or a warning. I guess that the Eclipse Java compiler doesn't support the full lambda syntax yet. Previous versions of IntelliJ had similar problems.

I'm sorry, but I think you have to wait till Eclipses fixes it's compiler or you have to change your favorite IDE. Hint: IntelliJ also has native Gradle support.

**Comment by syntheticperson** [comment]
Franz,
thanks for your response.
I thought the full lambda syntax was dependent on a minimum version of java
8.
Since Eclipse allows you to specify which version of java compiler to use,
is there a newer version of java 8 I should upgrade to?
I'll also take a look at IntelliJ.
Thanks!
Jeroen

**Comment by jenetics** [comment]
No, its not a matter of the JDK version you use, Java 8 is enough for compiling the project. The (false positive) error in the IDE is generated by the Eclipse code parser (compiler).

I will than close this issue.

**Comment by syntheticperson** [comment]
Thanks for the clarification.
