### ISSUE TITLE
need for a new kind of chromosome and crossover

### ISSUE THREAD

**Issue by hanbaoan123** [jenetics/jenetics#604]
Now I am doing Job Shop Scheduing with Jenetics. I want to represent the job shop scheduling problem with chromosome like 11222333444，in which the number of  each digit must stay the same all the time, so the swapmutator can be selected. However, I don't know how to implement crossover as below with existing alterer or perhaps a new alterer.

![图片1](https://user-images.githubusercontent.com/32160782/68911754-f5475800-0790-11ea-881a-dd5c0e9dca0c.jpg)

In the chromosome each digit represents a job, the number of occurrences of each digit represents which operation of the job. Before crossover, first divide the job into two groups randomly,for example jobset1={1,3}, jobset2={2,4}, then copy the jobs parent1 contained in jobset1 to children1 and parent2 contained in jobset2 to children2 and keep their position the same, last copy the jobs parent2 contained in jobset2 to children1 and parent1 contained in jobset1 to children2, retaining their orders .

**Comment by jenetics** [comment]
If you encoded your problem like a combinatorial problem, you probably can use the [PartiallyMatchedCrossover](http://jenetics.io/javadoc/jenetics/io/jenetics/PartiallyMatchedCrossover.html).

**Comment by hanbaoan123** [comment]
> If you encoded your problem like a combinatorial problem, you probably can use the [PartiallyMatchedCrossover](http://jenetics.io/javadoc/jenetics/io/jenetics/PartiallyMatchedCrossover.html).
But there are same genes in my chromosome which is different from PartiallyMatchedCrossover.

**Comment by jenetics** [comment]
There are different variations of the [Job shop scheduling](https://en.wikipedia.org/wiki/Job_shop_scheduling)  problem. Can you be more specific which variation are you trying to solve?

**Comment by hanbaoan123** [comment]
> There are different variations of the [Job shop scheduling](https://en.wikipedia.org/wiki/Job_shop_scheduling) problem. Can you be more specific which variation are you trying to solve?

I am trying to solve the general jsp, i.e.  each operation has only one optional machine.

**Comment by Sultan91** [comment]
> Now I am doing Job Shop Scheduing with Jenetics. I want to represent the job shop scheduling problem with chromosome like 11222333444，in which the number of each digit must stay the same all the time, so the swapmutator can be selected. However, I don't know how to implement crossover as below with existing alterer or perhaps a new alterer.
> 
> ![图片1](https://user-images.githubusercontent.com/32160782/68911754-f5475800-0790-11ea-881a-dd5c0e9dca0c.jpg)
> 
> In the chromosome each digit represents a job, the number of occurrences of each digit represents which operation of the job. Before crossover, first divide the job into two groups randomly,for example jobset1={1,3}, jobset2={2,4}, then copy the jobs parent1 contained in jobset1 to children1 and parent2 contained in jobset2 to children2 and keep their position the same, last copy the jobs parent2 contained in jobset2 to children1 and parent1 contained in jobset1 to children2, retaining their orders .

Hi? I am curious is it legit to crossover genes in a shifted way like on picture. E.g. Parent gene was on 1st place, now it is on 2nd place on child's chromosome?

**Comment by hanbaoan123** [comment]
> > Now I am doing Job Shop Scheduing with Jenetics. I want to represent the job shop scheduling problem with chromosome like 11222333444，in which the number of each digit must stay the same all the time, so the swapmutator can be selected. However, I don't know how to implement crossover as below with existing alterer or perhaps a new alterer.
> > ![图片1](https://user-images.githubusercontent.com/32160782/68911754-f5475800-0790-11ea-881a-dd5c0e9dca0c.jpg)
> > In the chromosome each digit represents a job, the number of occurrences of each digit represents which operation of the job. Before crossover, first divide the job into two groups randomly,for example jobset1={1,3}, jobset2={2,4}, then copy the jobs parent1 contained in jobset1 to children1 and parent2 contained in jobset2 to children2 and keep their position the same, last copy the jobs parent2 contained in jobset2 to children1 and parent1 contained in jobset1 to children2, retaining their orders .
> 
> Hi. I am curious is it legit to crossover genes in a shifted way like on picture. E.g. Parent gene was on 1st place, now it is on 2nd place on child's chromosome?

It is legal and used as a standard encoding in many papers about scheduling, which is known as POX(precedence operation crossover).
