### ISSUE TITLE
FYI, Creating custom gene from seems to have worse performance than using DoubleGene

### ISSUE THREAD

**Issue by Sultan91** [jenetics/jenetics#609]
Hello, I was experimenting with Jenetics and wanted to create custom Gene that would represent a rectangular figure (Rectangle(x0, y0, w,h) as an Allele) and created Genotype of such genes. Also I did the same thing with DoubleGene (x4 times larger chromosomes, encoding each value x0, y0, w, h - as DoubleGene).
Fitness function consisted of some geometrical evaluations like distance and overlap.
In first case I wasn't able to achieve minimal ff of 0 (it is theoretically possible)? while second gave almost 0 zero values.
I am guessing there might be an issue in implementation of my Custom Genes but I am not sure :)

**Comment by jenetics** [comment]
Doing a code review without code is quite hard, even for me ;-) But do you really need a custom gene?  This usually pays off, if you also need to implement your own mutation strategies. My first impression is, that you only need your `Rectangle` class and a corresponding `Codec<Rectangle, DoubleGene>`.  

If you give me your actual gene implementation, I will have a look at it.

**Comment by Sultan91** [comment]
This is kind of my implementation of gene:
(Motivation behind creating custom genes, consequently using mixed genes is to be able to encode various types of objects e.g. rectangle(with room, stair, elevator subtypes), orientation ) into their unique genes so that fitness function can easily know which type of gene I am working with )

`public class public class CustomGene
    implements Gene<Rectangle, CustomGene>
{
    private final static int XYRANGE = 120;
    private final static int MINSIDESIZE = 20;
    private final static int MAXSIDESIZE = 70;
    private final static Random random = RandomRegistry.getRandom();

    private final Rectangle rectangle;

    public CustomGene(double x, double y, double w, double h) {
        this.rectangle = new Rectangle(x, y, w, h);
    }
    private static Rectangle getRandomRectangle(){
        final Random random = RandomRegistry.getRandom();

        return new Rectangle(random.nextInt(XYRANGE), random.nextInt(XYRANGE),
                getRandomNumberInRange(), getRandomNumberInRange());
    }
    @Override
    public Rectangle getAllele() {
        return rectangle;
    }

    @Override
    public CustomGene newInstance() {

        return new CustomGene(random.nextInt(XYRANGE), random.nextInt(XYRANGE),
                getRandomNumberInRange(), getRandomNumberInRange());
    }

    @Override
    public CustomGene newInstance(Rectangle rectangle) {
        return of(rectangle);
    }

    @Override
    public boolean isValid() {
        return true;
    }
    public static CustomGene of(final Rectangle rectangle){
        return new CustomGene(rectangle.getMinX(), rectangle.getMinY(), rectangle.getWidth(), rectangle.getHeight());
    }
    public static ISeq<CustomGene> seq(final int rectCount){
        return MSeq.<CustomGene>ofLength(rectCount)
                .fill(() -> of(getRandomRectangle()))
                .toISeq();
    }
    private static int getRandomNumberInRange() {
        int min = MINSIDESIZE;
        int max = MAXSIDESIZE;
        if (min >= max) {
            throw new IllegalArgumentException("max must be greater than min");
        }

        Random r = new Random();
        return r.nextInt((max - min) + 1) + min;
    }
}

    implements Gene<Rectangle, CustomGene>
{
    private final static int XYRANGE = 120;
    private final static int MINSIDESIZE = 20;
    private final static int MAXSIDESIZE = 70;
    private final static Random random = RandomRegistry.getRandom();

    private final Rectangle rectangle;

    public CustomGene(double x, double y, double w, double h) {
        this.rectangle = new Rectangle(x, y, w, h);
    }
    private static Rectangle getRandomRectangle(){
        final Random random = RandomRegistry.getRandom();

        return new Rectangle(random.nextInt(XYRANGE), random.nextInt(XYRANGE),
                getRandomNumberInRange(), getRandomNumberInRange());
    }
    @Override
    public Rectangle getAllele() {
        return rectangle;
    }

    @Override
    public CustomGene newInstance() {
        // give random Customs.Genes.CustomGene

        return new CustomGene(random.nextInt(XYRANGE), random.nextInt(XYRANGE),
                getRandomNumberInRange(), getRandomNumberInRange());
    }

    @Override
    public CustomGene newInstance(Rectangle rectangle) {
        return of(rectangle);
    }

    @Override
    public boolean isValid() {
        return true;
    }
    public static CustomGene of(final Rectangle rectangle){
        return new CustomGene(rectangle.getMinX(), rectangle.getMinY(), rectangle.getWidth(), rectangle.getHeight());
    }
    public static ISeq<CustomGene> seq(final int rectCount){
        return MSeq.<CustomGene>ofLength(rectCount)
                .fill(() -> of(getRandomRectangle()))
                .toISeq();
    }
    private static int getRandomNumberInRange() {
        int min = MINSIDESIZE;
        int max = MAXSIDESIZE;
        if (min >= max) {
            throw new IllegalArgumentException("max must be greater than min");
        }

        Random r = new Random();
        return r.nextInt((max - min) + 1) + min;
    }
}

`

**Comment by Sultan91** [comment]
After little bit of thinking and looking into Crossovers and Mutators, I am guessing the convergence problem appears due to Rectangle object is being encoded as one gene instead of representing him as four genes (x0, y0, x1,y1) coordinate points. Consequently Rectangle genotype changing whole rectangle after some alteration which is too bold, I think)
