### ISSUE TITLE
Change variations to standard deviation in EvolutionStatistics

### ISSUE THREAD

**Issue by arisliang** [jenetics/jenetics#61]
Not sure if this applies to others, but to me standard deviation is more meaningful than variations due to unit of measure.

**Comment by jenetics** [comment]
I used the variance, because its the second central and perfectly fits into the list of calculated moments, from the first to the fourth moment. Calculating the standard deviation on the caller side should not be a big issue.

**Comment by arisliang** [comment]
If calculating from caller side, we may lose the nice statistics summary output. Writing a new output format from caller side takes some time. It would be easier if we can configure it to show on the statistics output.

**Comment by jenetics** [comment]
If the main issue is the summary output, I can additionally print the standard deviation.

**Comment by arisliang** [comment]
Yeah, that'll work. Thanks.
