### ISSUE TITLE
Lock genes from mutating during algorithm execution

### ISSUE THREAD

**Issue by wolfig** [jenetics/jenetics#617]
Hi Franz,

this is rather a question or a feature request: is it possible to "lock" genes or exclude genes from mutating ahead of time during optimization based on custom logic? Even better would be to narrow the search ranges of the genes during optimization.
Background of my question: I am optimizing an ion accelerator beamline with your code, where one element has a very narrow transmission function (more or less one value). As soon as the algorithm found this value (which happens normally quite early in the process), it is very undesirable that the gene related to this devices still mutates within the initial gene value range. It would be great if the gene can either be excluded from mutation as soon as the value has been found or if the search range could shrink during the process - e.g. based on a statistical analysis of the values collected during searching.

Is there a way to achieve this already with existing code?

Kind regards
Wolfgang

**Comment by jenetics** [comment]
One possible solution is to use the [EvolutionStream.ofAdjustableEvolution](http://jenetics.io/javadoc/jenetics/io/jenetics/engine/EvolutionStream.html#ofAdjustableEvolution-java.util.function.Supplier-java.util.function.Function-) method for creating an `EvolutionStream`. An usage example can be found [here](https://github.com/jenetics/jenetics/blob/master/jenetics/src/test/java/io/jenetics/engine/EvolutionStreamTest.java).
A drawback is, that it is quite cumbersome to use. I couldn't simplify it's usage yet.
