### ISSUE TITLE
Novelty Search

### ISSUE THREAD

**Issue by ZagButNoZig** [jenetics/jenetics#618]
### Lets imagine the following game : 
We have a little red square in a simple maze and the goal is to reach the top right corner while avoiding the walls. 

![Unbenannt](https://user-images.githubusercontent.com/39175622/70572849-ec378400-1ba0-11ea-8990-0c2a76e8be1f.png)
(The green square is the goal. The walls kill you)
The **genotype** in this game represents a neural network which is trying to solve the maze. 

When running a genetic algorithm on it it often gets stuck on the top right wall because it tries to minimize the distance to the goal. 

### The point I am trying to make is:

Genetic algorithms are weak to local optimum traps. (In this case) 
Even with very high exploration (mutation at 15%).

### And my question is: 

Could we implement a novelty reward system which calculates the fitness based on a fitness function F and a *novelty function N*? So the GA encourages objectives and novelty.

I would like to implement this. Any suggestions?

PS:
[Helpful explanation](http://eplex.cs.ucf.edu/noveltysearch/userspage/)

**Comment by jenetics** [comment]
Sounds interesting. I think a good starting point is to implement a special `Evaluator`:
```java
public class NoveltyEvaluator implements Evaluator<DoubleGene, Double> {
    @Override
    public ISeq<Phenotype<DoubleGene, Double>>
    eval(final Seq<Phenotype<DoubleGene, Double>> population) {
        // Evaluate your fitnesses.
        return ...;
    }
}

final Genotype<DoubleGene> gtf = null;
final Engine<DoubleGene, Double> engine =
    new Engine.Builder<>(new NoveltyEvaluator(), gtf).build();
```

Once you have an idea on how to generalize the novelty concept, we can try to integrate the (`Evalutator`) classes into the library.

**Comment by jenetics** [comment]
Implementing a `NoveltySelector` or `NonObjectiveSelector` might also be a good starting point.

**Comment by ZagButNoZig** [comment]
> Implementing a `NoveltySelector` or `NonObjectiveSelector` might also be a good starting point.

So the selector woulöd select individuals bassed on novelty? But then the selector would need to reevaluate the genotypes which might reduce performance. 

One the main goal is to provide away to just extend the fitness function to return 2 values (novelty and fitness). Because often those can be measured in the same simulation (just like in the maze game).

**Comment by jenetics** [comment]
> > Implementing a `NoveltySelector` or `NonObjectiveSelector` might also be a good starting point.
> 
> So the selector would select individuals based on novelty? But then the selector would need to reevaluate the genotypes which might reduce performance.

Yes, this would not be for free ;-)

> Another problem is normalization. What if a good fitness score is between 100 -120 and a good novelty score is between 4 - 10.
> This could also be generally implemented as a `ScoreNormalizer`

Having two values, fitness and novelty score, can be treated as multi-object optimization. This might be worth some experimentation, right?

**Comment by ZagButNoZig** [comment]
Just an update :
I will try to share an implementation on thursday :)

**Comment by ZagButNoZig** [comment]
`public class NoveltyEvaluator implements Evaluator<DoubleGene, Double> {
    private Function<Genotype<DoubleGene>, double[]> N;
    private double[][] pastNovelties;
    private int k;
    private int samples;
    private SplittableRandom random;

    public NoveltyEvaluator(Function<Genotype<DoubleGene>, double[]> _N, int noveltySpace, int k) {
        this.N = _N;
        this.pastNovelties = new double[noveltySpace][];
        this.k = k;
        this.random = new SplittableRandom();
        /* This should be an option too? */
        this.samples = noveltySpace / 2;
    }

    @Override
    public ISeq<Phenotype<DoubleGene, Double>>
    eval(final Seq<Phenotype<DoubleGene, Double>> population) {
        double[][] noveltyScores = population.stream()
                .parallel()
                .map(Phenotype::getGenotype)
                .map(N)
                .toArray(double[][]::new);
        double[] actualNovelty = new double[noveltyScores.length];
        for (int i = 0; i < noveltyScores.length; i++) {
            double[] distances = new double[samples];
            /* Compute the novelty difference */
            for (int j = 0; j < distances.length; j++) {
                int index = random.nextInt(pastNovelties.length);
                if (pastNovelties[index] == null) {
                    continue;
                }

                /* We sample random ones because its faster */
                distances[j] = euclideanDistance(noveltyScores[i], pastNovelties[index]);
            }
            /* The novelty is the averaged sum of the k-nearest distances.
             *  So we sort the array.
             */
            Arrays.sort(distances);
            /* And compute the novelty */
            double factor = 1d / k;
            for (int j = 0; j < k && j < distances.length; j++) {
                actualNovelty[i] += factor * distances[j];
            }
        }
        ISeq<Phenotype<DoubleGene, Double>> newPopulation = IntStream.range(0, actualNovelty.length)
                .mapToObj(i -> population.get(i).withFitness(actualNovelty[i]))
                .collect(ISeq.toISeq());
        /* We add the highest novelty to the past ones */
        pastNovelties[random.nextInt(pastNovelties.length)] = noveltyScores[argmax(actualNovelty)];
        return newPopulation;
    }

    private static double euclideanDistance(double[] a, double[] b) {
        if (a.length != b.length) {
            throw new IllegalArgumentException("Cannot calculate Euclidean Distance with different size arrays");
        }

        double sum = 0;

        for (int i = 0; i < a.length; i++) {
            sum += Math.pow(a[i] - b[i], 2);
        }

        return Math.sqrt(sum);
    }`

Here is a general concept.
It is very inefficient but has better results than "greedy" evaluation.

The next would be to improve this algorithm and to combine it with a fitness evaluator.

**Comment by jenetics** [comment]
Cool, I will have a closer look next week. (Still on _vacation_ :smile: )

**Comment by jenetics** [comment]
@ZagButNoZig, are you implementing a specific novelty algorithm here? Is there a paper, for this algorithm, which I can compare your implementation? Thanks.

**Comment by ZagButNoZig** [comment]
The implementation is based on [this article](https://lilianweng.github.io/lil-log/2019/09/05/evolution-strategies.html#extension-ea-in-deep-learning) in section "Exploration with ES".
