### ISSUE TITLE
Does this library supports Tree structure of Chromosome?

### ISSUE THREAD

**Issue by wihoho** [jenetics/jenetics#63]
Hi,

Many problems solved by genetic programming requires the tree structure of Chromosome like symbolic regression. So is there a way to support tree structure of using this library?

Thanks in advance.

**Comment by jenetics** [comment]
Jenetics currently doesn't support tree structured chromosomes. I'm currently thinking about a way of how to implement this (but currently not with highest priority).  One possible solution would be to use an array representation of such a (binary) tree: https://en.wikipedia.org/wiki/Binary_tree#Arrays 
This would also require a _special_ mutator class, which obeys the tree-structure of a given chromosome.

**Comment by wihoho** [comment]
Thanks.

I am looking forward to this feature. Right now, due to the task urgency, I will have to look for other alternative libraries.
