### ISSUE TITLE
Concurrent population initialization

### ISSUE THREAD

**Issue by beatngu13** [jenetics/jenetics#651]
We use Jenetics as part of a GUI-based test generator, similar to e.g. [Sapienz](http://www0.cs.ucl.ac.uk/staff/K.Mao/archive/p_issta16_sapienz.pdf). As you can imagine, population initialization and fitness evaluation are the most expensive parts since this means executing GUI actions. We distribute these tasks over network, where we concurrently send out requests via Jenetics.

The problem is that while the fitness evaluation indeed happens concurrently, it looks like the population initialization doesn't? At least in `Engine#evolve(EvolutionStart<G, C>)` or `Engine#evolutionStart(EvolutionStart<G, C>)` the given executor doesn't seem to be used.

Is there an out-of-the-box way to do the population initialization concurrently?

**Comment by jenetics** [comment]
Jenetics can't do this out of the box. But you can do something like this:
```java
// Do your population initialization concurrently, if desired.
final ISeq<Phenotype<DoubleGene, Double>> population = ISeq.empty();

// Define the GA engine.
final Engine<DoubleGene, Double> engine = Engine.builder(problem)
	.optimize(Optimize.MINIMUM)
	.offspringSelector(new RouletteWheelSelector<>())
	.build();

// Create evolution stream with pre-evaluated population.
final EvolutionResult<DoubleGene, Double> interimResult = engine.stream(population)
	.limit(Limits.bySteadyFitness(10))
	.collect(EvolutionResult.toBestEvolutionResult());
```

**Comment by beatngu13** [comment]
Thanks for pointing out the alternative approach.

Do you want to keep this open as some sort of feature request (if you think it makes sense)? I'm also happy to contribute some code if that helps.

**Comment by jenetics** [comment]
Currently, I'm not sure if a generalized feature will carry its weight. I will leave it open for now and waiting for a brainwave ;-)
