### ISSUE TITLE
Non-reproducible results although single-threaded and fixed random

### ISSUE THREAD

**Issue by beatngu13** [jenetics/jenetics#654]
I have a little toy project for the knapsack problem:

https://github.com/beatngu13/knapsack-problem/

I recently saw that _sometimes_ the build is failing because an integration test fails:

https://travis-ci.com/beatngu13/knapsack-problem/builds/147879639#L306

The corresponding [`MultiObjectiveIT`](https://github.com/beatngu13/knapsack-problem/blob/master/src/test/java/com/github/beatngu13/knapsackproblem/mo/MultiObjectiveIT.java) is single-threaded and uses a fixed random. Inside the project, I always obtain random via the `RandomRegistry`.

Shouldn't this lead to stable and reproducible results, or am I missing something?

**Comment by jenetics** [comment]
You are right, the behavior must be deterministic. As long as no other initialization code is _destroying_ it. I had a short look at your code and found two possible deterministic _destroyer_:
* In the `Knapsack.newInstance()` method you are using the `Collection.shuffle` method from the JDK, and I'm pretty sure this method is not using my `RandomRegistry` ;-)
* You are also storing the items in a `Set`, which might also introduce non-deterministic elements. Haven't Java changed the iteration order of `Set`s lately?

Maybe there are additional hidden _random_ elements.

**Comment by beatngu13** [comment]
>In the `Knapsack.newInstance()` method you are using the `Collection.shuffle` method from the JDK, and I'm pretty sure this method is not using my `RandomRegistry` ;-)

Oh boy … that was it! Now I pass the random instance to `shuffle`. Thanks for taking the time!
