### ISSUE TITLE
Limit predicate for fixed generation does not work as expected

### ISSUE THREAD

**Issue by varunnayak26** [jenetics/jenetics#655]
The `byFixedGeneration` predicate from `Limits` class is implemeneted as:
```
public static Predicate<Object> byFixedGeneration(final long generation) {
	if (generation < 0) {
		throw new IllegalArgumentException(format(
			"The number of generations must greater than one, but was %d",
			generation
		));
	}

	return new Predicate<Object>() {
		private final AtomicLong _current = new AtomicLong();
		@Override
		public boolean test(final Object o) {
			return _current.incrementAndGet() <= generation;
		}
	};
}

```
There are multiple problems in the above code.

1. The message from the `if` condition does not actually represent the condition. And it does not prevent the usage of `Limits.byFixedGeneration( 0 )`. Even executing the simple hello world example with this predicate as the limit, I observed that the engine still performs one evolution step (`EvolutionResult<G, C> evolve(final EvolutionStart<G, C> start)` method from `Engine` class) with the given evolution. 
2. The predicate itself is incorrect most likely due to the usage of `<=`. By executing the same hello world example using the predicate `Limits.byFixedGeneration( 1 )`, I observed the engine performs evolution step twice. 

In both cases, the results obtained are accurate. 
1. `null` when `Limits.byFixedGeneration( 0 )` is used as a limit predicate.
2. A genotype of generation 1 when `Limits.byFixedGeneration( 1 )` is used as a limit predicate.
The only issue is that it runs through the evolution step one time more. When population initialization and fitness evaluation are expensive, this is inefficient.

**Comment by jenetics** [comment]
The `Limits.byFixedGeneration` predicate works the same way as all other predefined `Limits`. I confess, that its behavior seems to be a little bit odd. The reason for this lies in the `limit` method of the `EvolutionStream`:
```java
EvolutionStream<G, C>limit(final Predicate<? super EvolutionResult<G, C>> proceed);
```
The limiting predicate can expect an `EvolutionResult` and this contract implies that the phenotypes of the result have been evaluated. This also holds for the `Limits.byFixedGeneration` predicate: it gets an _evaluated_ `EvolutionResult`. Even if the limit is _zero_, the engine has to evaluate the initial generation. So, the number of needed evaluations is `generations + 1`. I don't see the possibility to fix this, without breaking the other limiting predicates. What I can do is to add an implementation note to the Javadoc, and explain the behavior.

Point 1.) is a documentation error, I will fix it.

**Comment by jenetics** [comment]
Fixed exception message and improved Javadoc.
