### ISSUE TITLE
Replace Vec#of with VecFactory#ofObjectVec

### ISSUE THREAD

**Issue by beatngu13** [jenetics/jenetics#659]
First of all: Thank you very much for addressing #546 as part of release 5.2.0.

My code previously looked like:

```java
return Vec.of(fitnesses.stream().toArray(Fitness[]::new));
```

Now I would like to use the aforementioned new feature with something like:

```java
private final VecFactory<Fitness[]> vecFactory = VecFactory.ofObjectVec(
		Comparator.naturalOrder(),
		(u, v, i) -> u[i].compareTo(v[i]),
		Optimize.MAXIMUM, Optimize.MAXIMUM, Optimize.MINIMUM);

// ...

return vecFactory.newVec(fitnesses.stream().toArray(Fitness[]::new));
```

However, I'm unsure about the `ElementDistance`. I was looking into `Vec#of` in order to replace it with `VecFactory#ofObjectVec`, where I saw the following code:

```java
static <C extends Comparable<? super C>>
Vec<C[]> of(final C[] array) {
	return of(
		array,
		(u, v, i) -> clamp(u[i].compareTo(v[i]), -1, 1)
	);
}
```

Naturally I would try to do the same, but `Basics#clamp` is internal and I wonder what is the proper way to reproduce the `Vec#of` behavior while providing the new optimization directions.

**Comment by jenetics** [comment]
The `clamp` method just ensures that the values of the `compareTo` method are -1, 0 or 1. No magic about that. The `ElementDistance` function, in general, is needed to prevent clusters of similar solutions in your Pareto-set. In absence of additional information for `Comparable` points, only these three _distance_ values are used. The following code should do it:
```java
private final VecFactory<Fitness[]> vecFactory = VecFactory.ofObjectVec(
	Comparator.naturalOrder(),
	(u, v, i) -> {
		final int cmp = u[i].compareTo(v[i]);
		return cmp < -1 ? -1 : Math.min(cmp, 1);
	},
	Optimize.MAXIMUM, Optimize.MAXIMUM, Optimize.MINIMUM
);
```
But since you also control the implementation of the `Fitness.compareTo` method, ensure you are only returning -1, 1 or 0, and you can use your original version, without the `clamp`.

**Comment by beatngu13** [comment]
Sorry, I totally forgot that this is for plain objects, whereas my `Fitness` class implements `Comparable`. In this case, maybe it would be helpful to have something like:

```
VecFactory.ofComparableVec(List<Optimize>)
VecFactory.ofComparableVec(Optimize...)
VecFactory.ofComparableVec()
```

Which under the hood uses a `GeneralComparableVecFactory`. I can submit a PR if you think this makes sense.

**Comment by jenetics** [comment]
Makes sense, but I would name it
```java
VecFactory.ofObjectVec(List<Optimize>)
VecFactory.ofObjectVec(Optimize...)
```
and probably adding also
```java
VecFactory.ofObjectVec(ElementDistance, List<Optimize>)
VecFactory.ofObjectVec(ElementDistance, Optimize...)
```
 I'm not sure about the `VecFactory.ofComparableVec()`. In this case, you don't need a factory, you can create a `Vec` instance with `Vec.of` directly.

**Comment by jenetics** [comment]
Merged into r6.0.0 branch.

**Comment by beatngu13** [comment]
Wanted to submit a PR, but haven't found time for it … so thanks a lot for doing it! 🙏
