### ISSUE TITLE
Travelling Salesman with movable waypoints

### ISSUE THREAD

**Issue by DavenH** [jenetics/jenetics#660]
Hi, and thank you for the significant and well-written library. 

I have a problem that translates to the TSP, but with movable waypoints (let's say moving a waypoint costs 1.5x the "fuel" to travel between waypoints; you could imagine that an optimal solution brings an far outlier waypoint close to its nearest neighbours). So, it's still a problem of finding the right traversal order, but also of the right repositioning of waypoints.

Modifying the TSP example, I see that using EnumGene is invalid, as the waypoints are non-enumerable: their position is parameterized in this case, and new genes with different positions need to enter the population. 

Could I have a little guidance on what the most appropriate approach with Jenetics is? 

My idea was to replace EnumGenes with AnyGenes and keep most of the TSP example intact, so as to benefit from the gene-permuting logic, though I see further that the provided `Codecs.ofPermutation` is only compatible with EnumGenes, and rewriting that would be a lot of work. 

Any help much appreciated!

**Comment by jenetics** [comment]
Maybe you can go in this direction.
```java
private final ISeq<WayPoint> POINTS = ISeq.empty();

final class MovablePoint {
	final WayPoint point;
	final Point displacement;
	MovablePoint(final WayPoint point, final Point displacement) {
		this.point = point;
		this.displacement = displacement;
	}
}

Codec<ISeq<MovablePoint>, DoubleGene> codec = Codec.of(
	Genotype.of(
		DoubleChromosome.of(DoubleRange.of(0, 1), 100),
		DoubleChromosome.of(DoubleRange.of(-90, 90), 100),
		DoubleChromosome.of(DoubleRange.of(-180, 180), 100)
	),
	gt -> {
		final int[] order = ProxySorter.sort(
			gt.get(0)
				.as(DoubleChromosome.class)
				.toArray()
		);
		final double[] latDisplace = gt.get(1)
			.as(DoubleChromosome.class)
			.toArray();
		final double[] lonDisplace = gt.get(2)
			.as(DoubleChromosome.class)
			.toArray();

		return IntStream.range(0, order.length)
			.mapToObj(i -> new MovablePoint(
				POINTS.get(i),
				WayPoint.of(latDisplace[i], lonDisplace[i])
			))
			.collect(ISeq.toISeq());
	}
);

double fitness(ISeq<MovablePoint> solution) {
	return 0;
}
```


The crucial point is, that you encode the order of the way points as a  double array and define  the order as the sorted indexes of the values. Maybe this will help.

**Comment by DavenH** [comment]
Ingenious, encoding the order that way. Thank you! 
I'm really looking forward to digging into this library.
