### ISSUE TITLE
PartialAlterer uses fitness of unaltered phenotype

### ISSUE THREAD

**Issue by mfriedemann** [jenetics/jenetics#663]
Hey,

I am using a combination of features similar to #562, a mixed genotype with PartialAlterers, to apply a PartiallyMatchedCrossover to change order of operations encoded in one of two chromosomes.

While doing this, I found that the PartialAlterer.Section.merge() method checks whether the **_existing_** phenotype is already evaluated (which it of course is) and uses the **_existing_** fitness value for the altered phenotype, therefore skipping re-evaluation and making the whole exercise rather pointless.

https://github.com/jenetics/jenetics/blob/c47e3b7bfa2fdbb804405f2c30f7190e9eda7098/jenetics/src/main/java/io/jenetics/PartialAlterer.java#L237-L242

I modified it to just return the two-argument version Phenotype.of() without the fitness value, and the results start making a lot more sense and the population is actually evolving.

Best regards,
M.

**Comment by jenetics** [comment]
Ah, thank you for the report.

**Comment by mfriedemann** [comment]
Thank you for looking at it.

BTW (a bit OT) is there a specific reason PartiallyMatchedCrossover extends `Crossover<EnumGene<T>>`? The actual code doesn't seem to require that (in fact, is uses MSeq<T> directly in repair()).
This requires some messing around in our case, because the other chromosome is currently a LongChromosome.

Regards. M.

**Comment by jenetics** [comment]
The reason is, that the `Alterer` interface is generified by the gene type.

**Comment by mfriedemann** [comment]
Yes, but I feel enforcing `EnumGene<T>` instead of allowing some kind of gene directly as `T` is complicating reuse (along the lines of the discussions in #423, #165).
I know you wrote that this usage isn't really supported, but I need to get the job done one way or other (and currently use some ugly reflection hacks to invoke the PartiallyMatchedCrossover as a delegate).

Regards, M.

**Comment by jenetics** [comment]
A combinatorial problem can also be encoded with a `DoubleGene`:
```java
public Codec<int[], DoubleGene> CODEC =
    Codec.of(
        Genotype.of(
            DoubleChromosome.of(0.0, 1.0, 100)
        ),
        gt -> {
            final int[] order = ProxySorter.sort(
                gt.chromosome()
                    .as(DoubleChromosome.class)
                    .toArray()
            );
            return order;
        }
    );
```
Then you can try to encode your sub-problems also with `DoubleGene`s. The drawback of this encoding is, that sorting the `double[]` array has O(n log n) runtime complexity.

**Comment by jenetics** [comment]
Merged into r6.0.0 branch.
