### ISSUE TITLE
Using Tournament Selection without an explicit fitness function (Question)

### ISSUE THREAD

**Issue by ai4java** [jenetics/jenetics#678]
Genetic Algorithms can work in situations where an explicit fitness function does not exist, as long as two individuals can be compared to each other. In these cases, the stage where fitness is calculated for all individuals in the population is skipped, and a flavor of Tournament Selection is used that directly compare the competing individuals to each other to pick the winner of each 'tournament'. Is there a best practice or a suggested way to implement this flavor in Jenetics.io?

Thanks,
Eyal Wirsansky

**Comment by jenetics** [comment]
This kind of GA is not supported directly. Some minor tweaking is necessary to achieve it.
```java
final Factory<Genotype<DoubleGene>> gtf = ...;
final Engine<DoubleGene, Double> engine = Engine.builder(pt -> 0.0, gtf)
    .selector(new MyTournamentSelector())
    .build();

// Collecting the last 10 results.
final ISeq<EvolutionResult<DoubleGene, Double>> results = engine.stream()
    .limit(1000)
    .collect(ISeq.toISeq(10));
```

Since Jenetics requires you to deliver a fitness function, you have at least define one. In the example above, every phenotype is assigned a fitness value of zero. Without a global fitness function, every alterer might become a random _mutator_. Instead of collecting the _best_ result, you might want to collect the latest _n_ results. Simply because without fitness function, there is no best result.

**Comment by ai4java** [comment]
Thank you for your prompt response. It makes perfect sense.
I am struggling, though, when creating 'MyTournamentSelector', to translate the Genotype<DoubleGene> into a double[] - similar to what the engine would do when feeding the data to the fitness function. I believe this is done using the Codec, but I was unable to figure it out so far. Your guidance will be appreciated.

**Comment by jenetics** [comment]
If you put everthing together, your code will look like this:
```java
public class Test {

	static final class MyTournamentSelector implements Selector<DoubleGene, Double> {
		private final Function<Genotype<DoubleGene>, double[]> decoder;

		MyTournamentSelector(final Function<Genotype<DoubleGene>, double[]> decoder) {
			this.decoder = decoder;
		}

		@Override
		public ISeq<Phenotype<DoubleGene, Double>> select(
			final Seq<Phenotype<DoubleGene, Double>> population,
			final int count,
			final Optimize opt
		) {
			final double[] value = decoder.apply(population.get(0).genotype());
			return null;
		}
	}

	public static void main(final String[] args) {
		final Codec<double[], DoubleGene> codec = Codecs.ofVector(DoubleRange.of(0,1), 10);

		final Engine<DoubleGene, Double> engine = Engine.builder(doubles -> 0.0, codec)
			.selector(new MyTournamentSelector(codec.decoder()))
			.build();

		// Collecting the last 10 results.
		final ISeq<EvolutionResult<DoubleGene, Double>> results = engine.stream()
			.limit(1000)
			.collect(ISeq.toISeq(10));
	}

}
```

**Comment by ai4java** [comment]
Thank you very much. This was very helpful.
