### ISSUE TITLE
Deterioration of best fitness

### ISSUE THREAD

**Issue by perfectstrong** [jenetics/jenetics#698]
I'm currently working on a minimizing problem whose genotype is encoded as permutation of input. 

The alterers are `PartiallyMatchedCrossover` and `SwapMutator`. 

The selector is by default, `TournamentSelector(3)`.

I tracked the best fitness over generations and saw that the best objective value _fluctuates_, which should not be possible since the best genotype always wins in `TournamentSelector`. Here is a visualisation of multiple iterations (light blue lines)
![image](https://user-images.githubusercontent.com/23375518/81670754-5d2ce180-9448-11ea-8d1f-e5ad48135813.png)
Is this behavior intended ? Or am i at fault here ?

Example code:
````java
        final Codec<ISeq<PatientCycleDemand>, EnumGene<PatientCycleDemand>> CODEC
                = Codecs.ofPermutation(ISeq.of(cycleDemands));
        Engine<EnumGene<PatientCycleDemand>, Integer> engine = Engine
                .builder(this::eval, CODEC)
                .offspringFraction(offspringFraction)
                .optimize(Optimize.MINIMUM)
                .populationSize(populationSize)
                .alterers(new PartiallyMatchedCrossover<PatientCycleDemand, Integer>(pmcProb)
                                        .andThen(new SwapMutator<>(psmProb)))
                .maximalPhenotypeAge(Integer.MAX_VALUE)
                .executor(executor)
                .build();
        List<PatientCycleDemand> bestChromosome;
        bestChromosome = CODEC.decode(
                engine.stream()
                        .limit(maxGen)
                        .peek(evolutionResult -> bestObjectives.add(evolutionResult.bestFitness()))
                        .collect(EvolutionResult.toBestGenotype()))
                .asList();
````

**Comment by jenetics** [comment]
Hi @perfectstrong,

It is not the case, that the best individual (from a population) is always part of the next generation when using the `TournamentSelector`. If the best individual is never selected for a tournament, it will not be part of the next generation. The `TournamentSelector` only guarantees, that the worst individual is _never_ part of the next generation.

If you want to guarantee, that the best individual is part of the next generation, you have to use the `TruncationSelector` or the `EliteSelector` class, which also uses the `TruncationSelector` internally.

Regards
Franz

**Comment by perfectstrong** [comment]
Indeed, i also realized that after posting the question.
