### ISSUE TITLE
Understanding documentation of  io.jenetics.engine.Limits.byGeneConvergence

### ISSUE THREAD

**Issue by wolfig** [jenetics/jenetics#699]
Hi,

I have a question w.r.t. the documentation of io.jenetics.engine.Limits.byGeneConvergence. In the documentation it reads:

> A termination method that stops the evolution when a user-specified percentage of the genes (convergedGeneRage) that make up a Genotype are deemed as converged. A gene is deemed as converged when the average value of that gene across all of the genotypes in the current population is less than a user-specified percentage (convergenceRate) away **from the maximum gene value** across the genotypes.

What does "from the maximum gene value" mean? Does that mean, the algorithm maximizes the gene value or it maximizes the fitness related to tha gene value and the gene is deemed as converged if  the fitness of the individuals in a population (of a generation) is within a user defined percentage of the maximum fitness value?

**Comment by jenetics** [comment]
To be more precise, a limit-predicate isn't _directly_ part of the optimization process. It doesn't _optimize_ things. It _just_ decides when to stop the optimization process.

The gene-convergence based its stop-decision on the distribution of the gene values and not on the fitness values. Roughly speaking: if the gene values of an population are spread around the search space, it will continue the optimization. If the genes are concentrated in a small area of the search space it is assumed that the population has converged and the optimization is stopped.
