### ISSUE TITLE
GaussianMutator is violating the DoubleGene's upper bound

### ISSUE THREAD

**Issue by pkaib** [jenetics/jenetics#700]
It appears that GaussianMutator.mutate is violating the range constraint on the target DoubleGene by clamping to the gene's exclusive max boundary.  

from mutate:
...
final double max = gene.max().doubleValue();
...
return gene.newInstance(clamp(gaussian*std + value, min, max));

**Comment by jenetics** [comment]
Hi @pkaib,

you are right. That's an error. This bug is probably hidden by another bug. The `DoubleGene.isValid` method is also wrong.

```java
@Override
public boolean isValid() {
    return Double.compare(_allele, _min) >= 0 &&
        Double.compare(_allele, _max) <= 0;
}
```

**Comment by pkaib** [comment]
Would a synthetic inclusive max of (exclusiveMax - Double.MIN_VALUE) prevent the generation of invalid genes by boundary seeking alterers like GaussianMutator?

**Comment by jenetics** [comment]
I'm thinking about a special `clamp` method, which, instead of returning the maximal value, will return the biggest double value which is smaller than the max value. Such a number can be created like
```java
static double nextDown(final double value) {
	final long bits = Double.doubleToLongBits(value);
	return Double.longBitsToDouble(bits - 1);
}

public static void main(final String[] args) {
	System.out.println(nextDown(1.0));
}
```
This will print `0.9999999999999999`.

**Comment by jenetics** [comment]
Merged into r6.1.0 branch.
