### ISSUE TITLE
BitChromosome to Bitset

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#707]
Hi,

I have been using the Constraint interface to repair some chromosomes. First, I convert the BitChromosomes to BitSet, perform the changes and convert again to BitChromosome in order to return the new Phenotype. It seems to me that the conversion does not have the expected behaviour, in the sense that I create a BitChromosome of 25 bits and in the conversion, I got 32.

Find attached the example. The SampleConstraint.java implements the Constraint interface.
[sample-bitset.zip](https://github.com/jenetics/jenetics/files/4686939/sample-bitset.zip)

Would you give it a try? I am using the version 6.0.0. Thanks in advance.

Kind regards,
Antonio

**Comment by jenetics** [comment]
Yes, that seems to be a bug. But for your example I would recommend to use a different factory method.

```java
public static BitChromosome of(
    final BitSet bits,
    final int length,
    final double p
)
```

**Comment by antoniogarmendia** [comment]
Hi,

Thanks for the quick reply. 

What I should do in my real application is to update this BitChromosome. That is why I convert it to BitSet to perform the updates. I use BitSet because there is a factory method to convert it to BitChromosome. The new method you suggest me is to create a new chromosome. I would say that it does not fix for me.

Would you suggest me another way? I was trying to convert to MSeq, but I did not find any factory method to convert it to BitChromosome.

Kind regards,
Antonio

**Comment by jenetics** [comment]
Maybe there is an missundersanding. I recommended to do the follwoing
```java
BitChromosome update(final BitChromosome ch) {
    var bits = ch.toBitSet();
    // Do your update on the bit set, e.g.
    // bits.flip(0);
    return BitChromosome.of(bits, ch.lenght(), ch. oneProbability());
}
```

**Comment by antoniogarmendia** [comment]
Hi,

Sorry, I did not understand well. Thanks, I tested now and seems to work as expected.

Kind regards,
Antonio

**Comment by jenetics** [comment]
Merged into r6.1.0.
