### ISSUE TITLE
Factory method to convert string in a BitChromosome

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#712]
Hi,

I am using the Constraint interface to repair the chromosomes. In this sense, I need to convert BitChromosome.toCanonicalString() and convert it again from an updated character sequence. When I convert to the BitChromosome using `BitChromosome.of` the length of the resulting chromosome is higher.

Find attached an example. I started with a BitChromosome of 25 bits and end up with a bit chromosome of length 32.
[string-bitchromosome.zip](https://github.com/jenetics/jenetics/files/4710801/string-bitchromosome.zip)

Would you give it a try? I am using the version 6.0.0. Thanks in advance.

Kind regards,
Antonio

**Comment by antoniogarmendia** [comment]
Hi,

Debugging the jenetics code a little bit I would say the constructor is not getting the correct length. At this moment, the factory method 
`BitChromosome of(final CharSequence value, final double p)`
that called the constructor it is using `bits.length*8` I would say that it should be value.length() right?

Thanks in advance.

Kind regards,
Antonio

**Comment by jenetics** [comment]
There is also a factory method which takes the length of the bit-string.
```java
public static BitChromosome of(
    final CharSequence value,
    final int length,
    final double p
);
```

**Comment by antoniogarmendia** [comment]
Hi,

Thanks! I do not why I overlooked this function.

Kind regards,
Antonio
