### ISSUE TITLE
Assertion thrown in RouletteWheelSelector with dominated population

### ISSUE THREAD

**Issue by pkaib** [jenetics/jenetics#713]
Getting a "Probabilities doesn't sum to one." assertion when selecting from a dominated population in the roulette selector.  For example, consider a population of 100 with the following fitness distribution:

-6480.008430943731 (99 items)
-6480.008430943683 (1 item)

The result of a call to RouletteWheelSelector::probabilities(pop, 40, Optimize.MINIMUM) will result in a probability distribution of [0.40625, 0,0, 0.0, ...].  The items in this array do not add up to 1 and is subsequently flagged.

**Comment by jenetics** [comment]
Hi @pkaib,
Thanks for the bug report. Some interesting numerical  instabilities here. Have to think about how to fix it.

*Reproduced by*
```java
@Test
public void issue713() {
    final List<DoubleChromosome> chromosomes = new ArrayList<>();

    var gene = DoubleGene.of(-6480.008430943683, -10_000, 10_000);
    var ch = DoubleChromosome.of(gene);
    chromosomes.add(ch);

    for (int i = 1; i < 10; ++i) {
        gene = DoubleGene.of(-6480.008430943731, -10_000, 10_000);
        ch = DoubleChromosome.of(gene);
        chromosomes.add(ch);
    }

    final var population = chromosomes.stream()
        .map(Genotype::of)
        .map(gt -> Phenotype.of(gt, 10, gt.gene().allele()))
        .collect(ISeq.toISeq());

    final var selector = new RouletteWheelSelector<DoubleGene, Double>();
    final double[] p = selector.probabilities(population, 10);
    System.out.println(Arrays.toString(p));

    selector.select(population, 10, Optimize.MAXIMUM);
}
```

**Comment by jenetics** [comment]
Merged into r6.1.0.
