### ISSUE TITLE
How to fix count of bits in Bitchromosome

### ISSUE THREAD

**Issue by ShivKJ** [jenetics/jenetics#728]
Hi
I was working on a problem in which I created a bitchromosome of length 100. I wanted to fix count of bits that get opened. For example, whenever new bitchromosone instance is generated, it must have bit count equals to say 10. Is there a way to incorporate this behaviour.

**Comment by jenetics** [comment]
Hi @ShivKJ,
there is no way fixing the bit count of a bit-chromosome. But it looks like you need an encoding for a _sub-set_ problem, right. If so, you can do your encoding with an `PermutationChromosome`.

```java
Codec<int[], EnumGene<Integer>> codec = Codec.of(
	Genotype.of(
		PermutationChromosome.ofInteger(IntRange.of(0, 99), 10)
	),
	gt -> gt.chromosome().stream()
		.mapToInt(EnumGene::allele)
		.toArray()
);
```
The encoded `int[]` array now contains the indexes of where your `BitChromosome` would have had ones. And the length of the array is always 10. You can also use the predefined [Coecs.ofSubSet​(ISeq<? extends T> basicSet, int size)](https://jenetics.io/javadoc/jenetics/io/jenetics/engine/Codecs.html#ofSubSet(io.jenetics.util.ISeq,int)) method.

**Comment by ShivKJ** [comment]
Thanks, will check this method
