### ISSUE TITLE
repair a Bitchromosome using Constraint interface

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#730]
Hello,

I am using the Constraint interface to repair a BitChromosome, but I am getting a weird behaviour. I implemented this [constraint-sample.zip](https://github.com/jenetics/jenetics/files/4879239/constraint-sample.zip) example where if the number of bits set to true in a BitChromosome is not between 2 (inclusive) and 6 (inclusive), then I substitute it with a static Chromosome (I convert StringBuilder to BitChromosome). The thing is that at the end of the execution I am getting a chromosome with more bits set to true than expected. 

I tried to follow all your comments about the use of raw-types in Jenetics, so I just hope that it is well implemented. Would you please take a look at the code? Thanks for your help.

I am using version 6.0.1.

Kind regards,
Antonio

**Comment by jenetics** [comment]
Hi @antoniogarmendia,

I think I found the problem. The `Constraint` interface only repairs individuals which have been invalidated by the alterers. It is assumed, that the given genotype factory (`Factory<Genotype>`) only creates valid individuals, which is not the case for your encoding. The following code will fix this:
```java
private static final Constraint CONSTRAINT = new SampleConstraint();

private static final Factory GTF = () -> {
    final Factory<Phenotype> ptf = () -> Phenotype.of(
        Genotype.of(
            (Chromosome)PermutationChromosome.ofInteger(25),
            (Chromosome)BitChromosome.of(24)
        ),
        0
    );

    var pt = ptf.newInstance();
    // Try create genotype until it's valid.
    while (!CONSTRAINT.test(pt)) {
        pt = ptf.newInstance();
    }
    return pt.genotype();
};

@SuppressWarnings({ "rawtypes", "unchecked" })
public static void main(String[] args) {
    final Engine engine = Engine
            .builder(SampleMixedGenotype::fitness, GTF)
            .constraint(new SampleConstraint())
    ...
}
```

I'm not sure, whether the `Constraint` should also check newly created individuals. This was the reason, why the engine is created with a genotype factory instead of  the genotype directly.

**Comment by antoniogarmendia** [comment]
Hi,

Thanks a lot! It works, but I also need to check the `Constraint` newly created individuals. The method `repair` in the `Constraint` interface should return a Phenotype, not a Factory<Phenotype>, so I am lost in this sense. Would you know how I should do it? Thanks in advance.

Kind regards,
Antonio

**Comment by jenetics** [comment]
In the r6.1.0 branch I added a default method in the [`Constraint`](https://github.com/jenetics/jenetics/blob/r6.1.0/jenetics/src/main/java/io/jenetics/engine/Constraint.java#L203) interface.
```java
default Factory<Genotype<G>> constrain(final Factory<Genotype<G>> gtf) {
    requireNonNull(gtf);
    return () -> {
        final Phenotype<G, C> result = Phenotype.of(gtf.newInstance(), 1);
        return (test(result) ? result : repair(result, 1)).genotype();
    };
}
```
This allows you to do the following
```java
final Constraint<DoubleGene, Double> constraint = ...;
final Factory<Genotype<DoubleGene>> gtf = ...;
final Engine<DoubleGene, Double> engine = Engine
    .builder(fitness, constraint.constrain(gtf))
    .constraint(constraint)
    .build();
```

And this guarantees, that also newly created individuals are valid. As long as your `repair` method only returns valid individuals.

**Comment by antoniogarmendia** [comment]
Hi,

Thanks! I just built this branch from the sources, but I still get unexpected results. In this example [sample-constraint-bitchromosome-2-6.zip](https://github.com/jenetics/jenetics/files/4891565/sample-constraint-bitchromosome-2-6.zip) I basically do the same as the previous one, but instead of the substitution for a static BitChromosome I do it randomly (If the Bitchromosome has more than 6 bits set to 1, then I set some of those bits to zero and if the BitChromosome has less than 2 bits set to one, then I add some bits to one). Sometimes I get expected results, but sometimes in the Pareto set, I find a Bitchromosome with just one bit set to 1. 

This how I create the new Phenotype in the SampleConstraint

```@SuppressWarnings("unchecked")
	private Phenotype newPhenotype(MSeq<EnumGene<Integer>> repairPc, String stringBitChromosome, double oneProbability, long generation) {
		PermutationChromosome<Integer> pc = new PermutationChromosome<Integer>(repairPc.toISeq());
		BitChromosome bc = BitChromosome.of(stringBitChromosome, stringBitChromosome.length(), oneProbability);
		final Genotype genoType = Genotype.of(
				(Chromosome) pc,
				(Chromosome) bc 
				);		
		return Phenotype.of(genoType, generation);
	}
```
This is wrong, right? Thanks in advance!

Kind regards,
Antonio

**Comment by jenetics** [comment]
The fitness function in your example is returning a constant vector.
```java
@SuppressWarnings("rawtypes")
public static final Vec<double[]> fitness(Genotype genotype) {		
	return VEC_FACTORY.newVec(new double[] {
		//bitCount(genotype),
		cos(4)*2,
		sin(2 + 3),
		cos(3 + 3)*3,
		3
	});
}
```

**Comment by antoniogarmendia** [comment]
Hi,

Why if the fitness function return a vector the given result might be invalid?

In this example, [sample-constraint-bitchromosome-2-6v1.zip](https://github.com/jenetics/jenetics/files/4892399/sample-constraint-bitchromosome-2-6v1.zip) I use this fitness function:

```
public static final VecFactory<double[]> VEC_FACTORY =
			VecFactory.ofDoubleVec(
				Optimize.MAXIMUM,
				Optimize.MINIMUM
	);
	
	@SuppressWarnings("rawtypes")
	public static final Vec<double[]> fitness(Genotype genotype) {		
		return VEC_FACTORY.newVec(new double[] {
			bitCount(genotype),
			bitCount(genotype)			
		});
	} 
	
	@SuppressWarnings("rawtypes")
	public static double bitCount(final Genotype genotype) {
		BitChromosome bc = (BitChromosome) genotype.get(1);			 
		return bc.bitCount();
	}
```
I get BitChromosomes with only one bit set to true, but I do not know if this is a valid minimal example.

Thanks!

Kind regards,
Antonio

**Comment by jenetics** [comment]
Your `repair` function creates invalid phenotypes.
```java
public Phenotype repair(Phenotype individual, long generation) {
	MSeq<EnumGene<Integer>> repairPc = MSeq.of((PermutationChromosome) individual.genotype().get(0));
	BitChromosome bc = ((BitChromosome) individual.genotype().get(1));
	StringBuilder strBuilder = new StringBuilder(bc.toCanonicalString());
	repairNumberOfModules(bc, strBuilder);
	final var pt = newPhenotype(repairPc, strBuilder.toString(), bc.oneProbability(), generation);
	if (!test(pt)) {
		throw new IllegalArgumentException(pt.toString());
	}
	return pt;
}
```
```
Exception in thread "main" java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: [0|8|20|15|22|9|10|1|21|2|23|6|19|3|18|12|11|7|5|17|13|16|4|14|24,00010000|00000000|00000000] -> null
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalArgumentException: [0|8|20|15|22|9|10|1|21|2|23|6|19|3|18|12|11|7|5|17|13|16|4|14|24,00010000|00000000|00000000] -> null
	at SampleConstraint.repair(SampleConstraint.java:39)
	at io.jenetics.engine.Engine.filter(Engine.java:319)
	at io.jenetics.engine.Engine.lambda$evolve$9(Engine.java:234)
	at io.jenetics.engine.Timing.timing(Timing.java:58)
	at io.jenetics.engine.Engine.lambda$evolve$10(Engine.java:233)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 6 more
```

**Comment by antoniogarmendia** [comment]
Hi,

Sorry for that. Indeed, the method was creating invalid phenotypes. Thanks! Now it works very well. Congrats for a very nice tool!

Kind regards,
Antonio
