### ISSUE TITLE
[Question] Is it possible to pause/resume the optimization?

### ISSUE THREAD

**Issue by douglascvas** [jenetics/jenetics#735]
Hi, could you please tell me if it is possible to pause/resume an optimization?
Also, for instance, resume an optimization in case the application crashes. It would be very frustrating having the optimization run for a day or more and then loose it all because the application crashed.

**Comment by jenetics** [comment]
Yes, you can save intermediate results. How to do this is shown in the [ResultRescue](https://github.com/jenetics/jenetics/blob/master/jenetics.example/src/main/java/io/jenetics/example/ResultRescue.java) example.
