### ISSUE TITLE
create a Genotype from an iterable with different chromosome types.

### ISSUE THREAD

**Issue by TheoNguyen611** [jenetics/jenetics#756]
Hello,
 following the issue #165 , I was wondering if there was a simple way to create a genotype from an iterable with different type of chromosome. It would be very useful to parametrize the number of chromosome wanted in the genotype.
Indeed,  this code works :
``` java
List<DoubleChromosome> listChromosomes = new ArrayList<DoubleChromosome>();
final Genotype gt= Genotype.of(listChromosomes);
```
But this one doesn't work :
``` java
List<Chromosome> listChromosomes = new ArrayList<Chromosome>();
listChromosomes.add((Chromosome) DoubleChromosome.of(0.,1., 1));
listChromosomes.add((Chromosome) IntegerChromosome.of(0,1, 1));
final Genotype gt= Genotype.of(listChromosomes);
```
I can't figure out  how to avoid the compilation error :
```The method of(Iterable<? extends Chromosome<G>>) in the type Genotype is not applicable for the arguments (List<Chromosome>)```

For now, I use this method to create the genotype, but it is very limited if I want a different or a large number of chromosomes: 
``` java
final Genotype gt = Genotype.of(
    DoubleChromosome.of(0., 1., 1),
    IntegerChromosome.of(0, 1, 1)
);
```

Thank you so much for your answer!

**Comment by louis-rivoire** [comment]
👍👍

**Comment by jenetics** [comment]
If I understand you correctly, there are two problems you are trying to solve: a) you want create a heterogeneous `Genotype` and b) the number of chromosomes of the `Genotype` should be varying.

Ad a)
If you want to create a heterogeneous `Genotype` you have to give up generics the whole way down. This means, you have to use _raw_-types everywhere.

```java
final var chromosomes = new ArrayList();
chromosomes.add(DoubleChromosome.of(0.,1., 1));
chromosomes.add(IntegerChromosome.of(0,1, 1));
final Genotype gt = Genotype.of(chromosomes);

final Engine engine = Engine.builder(g -> 0.0, gt)
    .build();
``` 

Ad b)
If you need `Genotype`s with a variable length, the `Engine` must be created with a genotype `Factory`.

```java
final var random = new Random();

Factory factory = () -> {
    final int length = random.nextInt(5) + 10;
    final var chromosomes = new ArrayList();
    for (int i = 0; i < length; ++i) {
        if (i%2 == 0) {
            chromosomes.add(DoubleChromosome.of(0.,1., 1));
        } else {
            chromosomes.add(IntegerChromosome.of(0,1, 1));
        }
    }

    return Genotype.of(chromosomes);
};

final Engine engine = Engine.builder(g -> 0.0, factory)
    .build();
```

**Comment by TheoNguyen611** [comment]
Thank you very much, the problem a) was exactly what I was trying to solve :)
