### ISSUE TITLE
Errors in EvolutionResult.java class

### ISSUE THREAD

**Issue by zuzkame** [jenetics/jenetics#757]
Hi, I'm getting 6 errors in **EvolutionResult** class in methods: **toBestGenotype(), toBestPhenotype() and toBestResult().** These functions are used there: _withTotalGenerations(), bestPhenotype()_ and they are not recognized.

**Comment by jenetics** [comment]
Can you write a test (some code) which reproduces the error and attach the stack trace?

**Comment by jenetics** [comment]
Can't be reproduced.
