### ISSUE TITLE
NSGA ii and Tournament Selection

### ISSUE THREAD

**Issue by antoniogarmendia** [jenetics/jenetics#774]
Hi,

I am implementing my own Alterers. Specifically, a Mutator and a Crossover operation for a specific kind of Integer Chromosome. Currently, my execution is as follows:

                //Execution Environment
		final Engine<IntegerGene, Vec<double[]>> engine = Engine.builder(
				new FF(), gtf)
				.offspringSelector(new TournamentSelector<>(2)) // Binary Selector 
				.alterers(
					        new MyCrossover(croosoverRate)
						,new MyMutator(mutatorRate)
						)
				.survivorsSelector(NSGA2Selector.ofVec()) //Survivor Selector
				.populationSize(100) ////NSGA ii paper	
				.build();		
		
At this moment, I am implementing MyCrossover, and I realize that as a parameter I receive the whole population to perform the crossover. But since one of the engine parameters is the TournamentSelector<>(2) I just thought that the Engine just gives me parent1 and parent2 in order that I can return the offspring1 (in this case just one offspring is produced). It seems to me that it does not work like this, right?

Therefore, my question is How should be the best way to accomplishing this? Can I use the TournamentSelector within MyCrossover() to create the same number of offspring as the current population? Like this:

TournamentSelector<IntegerGene, Vec<double[]>> selector = new TournamentSelector<>(2);
selector.select(population, 2, opt);

If this is the case, What is opt in this case? Since I am trying to implement a Multi-Objective algorithm.

Sorry for this long entry. I was not able to do it shortly :-/.

Thanks in advance!

Kind regards,
Antonio

**Comment by jenetics** [comment]
I fear, Jenetics works not the way you are think it does:
1) Selectors are responsible for dividing the population into _offspring_ and _survivors_.
1) The selectors will get the whole population for selecting offspring and survivors.
1) The alterers will get the _selected_ offspring population for the altering step.
1) The sample size of the `TournamentSelector`, in your case 2, is *not* the number of selected individuals. This is also described in the Javadoc.
1) If you implement your own alterer, you are also responsible for selecting the two individuals you want to _crossover_.
1) The alterers will get the selected offspring population for alteration. This means, the alterer has to select the individuals, used for alteration, from the given _offspring_ population, which is delivered by the `Engine` automatically.
1) You can control the number of offspring individuals with the `offspringFraction` parameter of the `Engine`.
1) You can derive your _special_ crossover alterer from the `SinglePointCrossover` class and override the `protected int crossover(final MSeq<G> that, final MSeq<G> other)` methods. This is, most likely, the method you wanted to override. It takes _mutable_ versions of the two individuals you want to corssover.

I hope this answers your questions,
regards
Franz

**Comment by antoniogarmendia** [comment]
Hi Franz,

Thank you so much! This answer clarifies me a lot. However, I still have some questions. 

1) I can extend SinglePointCrossover to implement my alterer. However, the thing is that my crossover does not alter the actual parents. The thing is that two parents produce a new offspring (just one). Therefore, How I should do this? Because the SinglePointCrossover just interchanges the genes but that is not my case.

2) My alterer reduces the population because two parents produce one offspring. How Jenetics keep the size of the population? In which step? In line 8, Listing 1.2 page 3 of your book you filter and removing the killed individuals (killed individuals means remove duplicates?). Does this mean that you remove the duplicates and also add new individuals to the population until reaching the required size? 

3) How the second parent is selected? I mean in SinglePointCrossOver you select one parent using the probability right? How you choose the second parent? 

4) How offspringFraction is guaranteed? The default value is 0.6, then, the population is traversed as many times as necessary until this percentage is reached? 

Sorry in advance if there is a silly question :-/. Thanks for your time!

Kind regards,
Antonio

**Comment by jenetics** [comment]
Ad 1) The following code will give you a template for implementing your own crossover.
```java
class SpecialCrossover<
    G extends Gene<?, G>,
    C extends Comparable<? super C>
>
    extends AbstractAlterer<G, C>
{
    protected SpecialCrossover(double probability) {
        super(probability);
    }

    @Override
    public AltererResult<G, C> alter(Seq<Phenotype<G, C>> population, long generation) {
        final var random = RandomRegistry.random();

        if (random.nextDouble() < _probability) {
            final var pop = new ArrayList<>(population.asList());

            final var pt1 = pop.remove(random.nextInt(pop.size()));
            final var pt2 = pop.remove(random.nextInt(pop.size()));
            final var gt1 = pt1.genotype();
            final var gt2 = pt2.genotype();

            final int chIndex = random.nextInt(min(gt1.length(), gt2.length()));

            final var c1 = MSeq.of(gt1);
            final var c2 = MSeq.of(gt2);
            final var genes1 = MSeq.of(c1.get(chIndex));
            final var genes2 = MSeq.of(c2.get(chIndex));

            final int alterations = crossover(genes1, genes2);

            // c1 is updated and c2 removed from the population.
            c1.set(chIndex, c1.get(chIndex).newInstance(genes1.toISeq()));

            // Now `pop.size() == population.size() - 1`.
            pop.add(Phenotype.of(Genotype.of(c1), generation));

            return AltererResult.of(ISeq.of(pop), alterations);
        }

        return AltererResult.of(population);
    }
    private int crossover(final MSeq<G> that, final MSeq<G> other) {
        // Do the crossover.
        return 1;
    }
}
```

Ad 2) _Missing_ individuals are added (with newly created one) after each generation.
Ad 4) The population is divided into two sets, offspring and survivors. Only the offspring population is altered. After alteration, the two sets are merged again. Then missing individuals are added, so that the defined population size stays constant.

Regards,
Franz

**Comment by antoniogarmendia** [comment]
Hi Franz,

Thanks! Sorry for this late reply, but I was trying to implement my _special alterer_ following this template. I think I implement this correctly. Hopefully I will get good results :-). 

BTW: I am implementing this approach. I found this very interesting. 
[[Ermin]Combining advantages of new chromosomerepresentation scheme and multi-objectivegenetic algorithms for better clustering.pdf](https://github.com/jenetics/jenetics/files/6597685/Ermin.Combining.advantages.of.new.chromosomerepresentation.scheme.and.multi-objectivegenetic.algorithms.for.better.clustering.pdf)
[[Ülker] Linear Linkage Encoding.pdf](https://github.com/jenetics/jenetics/files/6597686/Ulker.Linear.Linkage.Encoding.pdf)

Thanks again!

Kind regards,
Antonio
