### ISSUE TITLE
Final Genotype not correct

### ISSUE THREAD

**Issue by margaridaana** [jenetics/jenetics#775]
Hi, 

I've been using the Jenetics library and for a while my final result has been confusing me. I've created a custom gene and chromosome since my goal is to create a week meal plan, so each gene is a recipe. The fitness function is working however when I finish the code, where I get the best Genotype, the genotype is different and therefore so is the fitness function value, from the best result (from statistics and confirmed by checking the fitness value for each iteration and each genotype). Basically the final result is not the best genotype, I've tried a lot of things and nothing has worked so far, I was wondering if you could help me. 

Thank you in advance.

Kind Regards, 
Margarida

**Comment by jenetics** [comment]
Can' you attach some code, which shows what you have done and describe what you want expect? Without some example it is hard to give you any advice.

lg
Franz

**Comment by margaridaana** [comment]
Thank you for the quick response!
Here is the code: ```
[Genotype<PlanGene> plans=Genotype.of(PlanChromosome.of(scope,context,recipeCandidateGenerator));
int popSize=20;
double probV=0.2;
Engine<PlanGene, Double> engine = Engine
                .builder(PlanGenotype::fitness,plans)
                .populationSize(popSize)
                .offspringFraction (0.7)
                .survivorsSelector (new RouletteWheelSelector<>())
                .offspringSelector(new RouletteWheelSelector<>())
                .alterers(new MultiPointCrossover<>(probV),new Mutator<>(0.2))
                .executor(Runnable::run)
                .build();


final long[] gen = {0};
        List<Double> fitperG = new ArrayList<>();
        List<Genotype> genos=new ArrayList<>();
        List<ISeq> allGenes=new ArrayList<>();
        //final Genotype[] best = {null};
        context.getMealPlanningHistory().resetCurrentPlannedMeals();
       Genotype <PlanGene> result =
                        engine.stream()
                                .limit(bySteadyFitness(15))
                                .limit(200)
                                .peek(statistics)
                                .peek(er -> fitperG.add(er.bestFitness()))
                                .peek(er -> gen[0] =(er.totalGenerations()))
                                .peek(er->genos.add(er.bestPhenotype().genotype()))
                                .peek(er->allGenes.add(er.genotypes()))
                                .collect(EvolutionResult.toBestGenotype());
]
I can also send the PlanGene and PlanChromosome classes I created. The idea is to have a list of recipes and for each mean only some are acceptable (the recipeCandidateGenerator does that) and then I create a week plan with all the meals. 

My fitness function is based on previously developed nutritional heuristics. My problem is that while the code is running I get a maximum fitness value but then as I collect the genotype that should have that same fitness the result is different. 
I've checked and the reason is because the output genotype from the evolutionResult is not the same as the one that corresponds to the best fitness. Hope I made myself clear. Thank you again!

Regards, 
Margarida
```

**Comment by jenetics** [comment]
OK, the code looks quite normal. If you observe such a strange behavior, it might be the fault of the fitness function. Jenetics assumes that the fitness function is stateless (no global mutable state) and deterministic (calculating the fitness of a genotype always returns the same fitness value). Does your fitness function fulfill this requirements?

**Comment by margaridaana** [comment]
I think so, here is the code

```
public static double fitness(Genotype<PlanGene> geno) {

        int geneN=0;
      
        context.getMealPlanningHistory().resetCurrentPlannedMeals(context.getMealPlanningHistory().getPlansForWeekBeingPlanned());
        Chromosome<PlanGene> test=geno.chromosome();
        List<Recipe> testL= toList(test);
        List<MealPlanningScope.DayPlanningScope> dayScope= scope.getDaysToPlan();
        for (MealPlanningScope.DayPlanningScope i:dayScope) {
            List<MealPlanningScope.MealOfDayPlanningScope> mealScope = i.getMealsOfDayToPlan();
          
            for (MealPlanningScope.MealOfDayPlanningScope a: mealScope){
                List<MealOfDayDivision> mealDivisions = context.getDivisionsForMealOfDay(a.getMealOfDay());
                MealPlan OutMeal = new MealPlan();
                OutMeal.setEditable(true);
                Constants.DayOfWeek day = DateUtils.getDayOfWeekFromDate(a.getDate());
                OutMeal.setDayOfWeek(day);
                OutMeal.setMealOfDay(a.getMealOfDay());
                OutMeal.setDate(a.getDate());
                context.getMealPlanningHistory().addUsedMeal(OutMeal);
                for (MealOfDayDivision parts: mealDivisions){
                    Recipe testRecipe=testL.get(geneN);
                    ScaledRecipe plannedRecipe = new ScaledRecipe();
                    OutMeal.addScaledRecipe(plannedRecipe);
                    plannedRecipe.setRecipe(testRecipe);
                    plannedRecipe.setMealOfDayDivision(parts);
                    plannedRecipe.setUser(context.getUser());
                    plannedRecipe.setEditable(false);

                    geneN++;

                   RecipeScaler recipeScaler = new RecipeScaler();
                   recipeScaler.scaleSingleMeal(context, OutMeal);

            }
 }
  }
        List<ScoredMealPlanRecipe> scoresForWholeWeek = heuristicsManager.scoreWeekRecipes(context, scope);
        return scoresForWholeWeek.get(0).getWeekScore(); }
```

The scoreWeekRecipes is deterministic.

**Comment by jenetics** [comment]
What is your `context` doing? This seems to be the cause of your problem, which introduces a _global_ , _mutable_ state into your fitness function. Since you doing some updates on the context (`resetCurrentPlannedMeals`), the fitness function is no longer deterministic. 
Keep in mind that the fitness values for the genotypes are also evaluated concurrently.

**Comment by margaridaana** [comment]
oh ok, I hadn't thought about that. In order to use the scoreWeekRecipes I need to add the plan to the context, and reset the previous genotype from the meal history, any idea how I can still do that without messing with the fitness function?

**Comment by jenetics** [comment]
Sorry, I have not enough knowledge of the problem you want to solve. But the word _history_ rings the alarm bell for me. Maybe you have to rethink you encoding. Any kind of _history_ makes your fitness function nondeterministic. It is really crucial that the result o the fitness function solely depends  on the input genotype. If you need some additional information for calculating the fitness value, it must also be encoded into the input genotype.

That said, there might be a workaround: Jenetics also allows you to evaluate the fitness values of a population at once. This way you have the possibility to use the values of the whole population when calculating a genotype's fitness value. This might solve your _history_ problem. So have a look at the [Evaluator](https://jenetics.io/javadoc/jenetics/6.2/io/jenetics/engine/Evaluator.html) interface.

```java
final Evaluator<IntegerGene, Integer> evaluator = population -> {
    // Calculate the fitness value of 
    // the whole population at once.
    return ...;
};

final Engine<IntegerGene, Integer> engine =
    new Engine.Builder<>(evaluator, gtf)
        // ...
        .build();
```

Using the `Evaluator` interface also gives you control on how the fitness values are calculated, concurrently or serial. Note: the fitness value of a genotype **must** also not depend on the evaluation order of the genotypes!

**Comment by margaridaana** [comment]
Thank you so much, one thing, my custom gene class is this:
 ```
public class PlanGene implements Gene<Recipe,PlanGene> {

	private static final Logger logger = LogManager.getLogger();


//    @Override
//    public Double getAllele() {
//        return null;
//    }
//
//    @Override
//    public PlanGene newInstance() {
//
//        return null;
//    }
//
//    @Override
//    public PlanGene newInstance(Double value) {
//        return null;
//    }
//
//    @Override
//    public boolean isValid() {
//        return false;
//    }

        private static RecipeCandidateGenerator recipeCandidateGenerator;
        private Recipe recipe;
        private MealPlanningContext context;
        private MealPlanningScope.MealOfDayPlanningScope mealScope;
        private MealOfDayDivision mealOfDayDivision;
        private MealPlanningScope scope;

        private PlanGene(Recipe recipe, MealPlanningContext context, MealPlanningScope.MealOfDayPlanningScope mealScope,MealOfDayDivision mealOfDayDivision, RecipeCandidateGenerator recipeCandidateGenerator,MealPlanningScope scope) {
            this.recipe = recipe;
            this.context=context;
            this.mealScope=mealScope;
            this.mealOfDayDivision=mealOfDayDivision;
            this.recipeCandidateGenerator=recipeCandidateGenerator;
            this.scope=scope;

        }

        public static PlanGene of(Recipe recipe,MealPlanningContext context, MealPlanningScope.MealOfDayPlanningScope mealScope,MealOfDayDivision mealOfDayDivision,RecipeCandidateGenerator recipeCandidateGenerator,MealPlanningScope scope) {
            return new PlanGene(recipe,context, mealScope,mealOfDayDivision,recipeCandidateGenerator,scope);
        }

//        public static ISeq<PlanGene> seq(Integer min, Integer max, int length) {
//            Random r = RandomRegistry.getRandom();
//            return MSeq.<CustomGene>ofLength(length).fill(() ->
//                    new CustomGene(random.nextInt(r, min, max))
//            ).toISeq();
//        }

    public static PlanGene of(MealPlanningContext context, MealOfDayDivision parts, MealPlanningScope.MealOfDayPlanningScope a,RecipeCandidateGenerator recipeCandidateGenerator,MealPlanningScope scope) {
            List<Recipe> candidates= recipeCandidateGenerator.candidatesForMealDivision(context,a,parts);
            Random rand = new Random();
            Recipe chosenRecipe=(candidates.get(rand.nextInt(candidates.size())));
            return PlanGene.of(chosenRecipe,context,a,parts,recipeCandidateGenerator,scope);
        }

   // public Recipe allele() {
      //  return recipe;
   // }

        @Override
        public Recipe allele() {
            return recipe;
        }
    @Override
    public Recipe getAllele() {
        return recipe;
    }

    @Override
    public PlanGene newInstance() {
        return of(context,mealOfDayDivision,mealScope,recipeCandidateGenerator,scope);
    }


        public MealPlanningContext getContext()
{
    return context;
}

public MealPlanningScope getScope()
{
    return scope;
}

      public PlanGene newInstance(Recipe recipe) {
           return new PlanGene(recipe,context,mealScope,mealOfDayDivision,recipeCandidateGenerator,scope);
        }

        @Override
        public boolean isValid() {
            return true;
        }

}
```
if instead of accessing the global context I get it from the Gene class is it possible to use? I don't know how the Evaluator works but I don't need the history to search for old things. The resetCurrentPlannedMeals works to delete the previous genotype that was added to the context, I'm not sure if I can do that using the Evaluator.
I'm sorry if I  sound confusing but this is for my thesis and it's my first time working with Java.

**Comment by jenetics** [comment]
The key-word here is _global_ context. If it is mutable it doesn't matter if you add it to the gene, you gained nothing. You only changed the _injection_ method.

Another implementation hint: If you need a `Random` object, get it with the `RandomRegistry.random()` method instead creating an ad-hoc instance with `new Random()`.

**Comment by margaridaana** [comment]
Hello, sorry to be bothering again, I think I solved that issue and I was always getting correct results however today I began having some results (after running the code several times) that did not match, and I've found some weird things in the library code. In the evolutionresult.java in the toBestEvolutionResult, toBestGenotype and toBestPhenotype some functions like: bestPhenotype and withTotalGenerations appear in red and in the file's problems says it cannot solve the method, is this normal or I do have something incorrectly done?
