### ISSUE TITLE
Array as Factory

### ISSUE THREAD

**Issue by abolfazl-sh** [jenetics/jenetics#779]
I want an array of integer be as Factory. did it implemented in jenetics?
in fact I want something like follow:
`Factory<Genotype<IntegerGene[]>>=  Genotype.of(IntegerChorosome[].of(size_of_array, array_of_minimum_value, array_of_maximum_values));`
`array_of_minimum_value` should be an array of minimum value for every element in the array
and `array_of_maximum_values` should be an array of maximum value for every element in the array.
if it didn't implemented please share a clue where should I start.
thanks in advance.

**Comment by jenetics** [comment]
I think you want to do something like the following:
```java
static double fitness(final int[] args) {
    // Your fitness function implementation
    return 0.0;
}

public static void main(final String[] args) {
    // This codec is equivalent to
    //   - size_of_array := 5
    //   - array_of_minimum_value := {0, 2, 4, 5, 8}
    //   - array_of_maximum_value := {10, 12, 14, 15, 18}
    final Codec<int[], IntegerGene> codec = Codecs.ofVector(
        IntRange.of(0, 10),
        IntRange.of(2, 12),
        IntRange.of(4, 14),
        IntRange.of(6, 16),
        IntRange.of(8, 18)
    );

    final Engine<IntegerGene, Double> engine = Engine.builder(Main::fitness, codec)
        // Additional Engine configuration.
        .build();
}
```

**Comment by abolfazl-sh** [comment]
thanks. this is exactly what I needed.
