### ISSUE TITLE
Bug checking Sample arity in class SampleList

### ISSUE THREAD

**Issue by Menoita99** [jenetics/jenetics#803]
I was reading the code to better understand the framework, and I come across what I think it's a bug. 
In the class SampleList the for loop in line 69 is always checking the arity of sampling 0 instead of checking the arity of sampling i.

![image](https://user-images.githubusercontent.com/36867483/137638888-bd53b42a-69cc-4065-a4c0-6ce507695848.png)

**Comment by jenetics** [comment]
Yes, that's a bug.

**Comment by jenetics** [comment]
Merged into r7.0.0 branch.
