### ISSUE TITLE
Adaptive mutation probability

### ISSUE THREAD

**Issue by ebichuuu** [jenetics/jenetics#83]
Hello,

1. According to the manual the fitness function has to be idempotent. Does it mean that the evaluation of the genotype cannot consist of another metaheuristic to solve a subproblem?
2. I would like to implement an adaptive mutation probability, but since I'm not very experienced in programming I'm not sure how to start about it. The mutation probability should increase if a steady fitness limit has been reached. If a new best solution has been found it should be reset to the default value. I thought that maybe SteadyFitnessLimit mechanism could be somehow used for that.

**Comment by jenetics** [comment]
Hi, here are some hints:

ad 1) it is for sure possible to experiment with non-idempotent fitness functions. The evolution Engine doesn't check this property. But the `Phenotype` calculates the fitness value only once and caches it. (This is done for performance reasons.) The _new_ fitness value is only calculated for new `Phenotype` instances, which means that the survivors still return the _old_ fitness value, even for a _changed_ fitness function. 
I haven't tried non-idempotent fitness functions so far. It would be nice if you could share some of your results, if you have any.

ad 2) The `Alterer`/`Mutator` implementations of the library are all immutable by default, but as a workaround, you can implement a `MutableAlterer`, where you can change the underlying immutable alterer:
```java
final class MutableAlterer<
	G extends Gene<?, G>,
	C extends Comparable<? super C>
>
	implements Alterer<G, C>
{
	private final AtomicReference<Alterer<G, C>> _alterer = new AtomicReference<>();

	public MutableAlterer(final Alterer<G, C> selector) {
		_alterer.set(selector);
	}

	public void setAlterer(final Alterer<G, C> selector) {
		_alterer.set(selector);
	}

	@Override
	public int alter(final Population<G, C> population, final long generation) {
		return _alterer.get().alter(population, generation);
	}
}
``` 
You then have to implement also your own steady-fitness terminator, which will set the new mutator with the changed probability, as a side-effect.

I hope could help you starting your experiments,
Franz

**Comment by ebichuuu** [comment]
Hello, thanks for your reply. 

ad 1.) I have tried to apply some other Metaheuristic but received a few error messages when using it for the evaluation. However, I decided to use some basic deterministic heuristic for the Problem for now. Maybe I will try to look into it later again.

ad. 2.) Thank you, I was able to create an steady-fitness based mutation probability.
