### ISSUE TITLE
bitCount seems to produce incorrect results

### ISSUE THREAD

**Issue by akornienko** [jenetics/jenetics#842]
I was experimenting with this library and it seems that results of bitCount are incorrect when a chromosome has a length of 5 bits
Can you please clarify if I misinterpreted the screenshot below?

here is from IntelliJ debug

![bitCount](https://user-images.githubusercontent.com/477560/187728043-93c08882-b6fa-4dcb-98a3-2eef59c8071b.png)

**Comment by akornienko** [comment]
if its helpful - here is how I create genotype factory:
Factory<Genotype<BitGene>> gtf = Genotype.of(BitChromosome.of(5, 0.05), BitChromosome.of(16, 0.05));

**Comment by jenetics** [comment]
Thank you, you are right. There is a bug in the `BitChromosome::bitCount` method for chromosomes smaller then 8.

**Fix**

*Bits.java*

```java
public static int count(final byte[] bits, final int start, final int end) {
    // Special handling for small bit size.
    if (end - start <= Byte.SIZE) {
        int count = 0;
        for (int i = start; i < end; ++i) {
            if (get(bits, i)) {
                ++count;
            }
        }
        return count;
    }

    final int byteStart = start/Byte.SIZE + 1;
    final int byteEnd = end/Byte.SIZE;

    int count = 0;
    for (int i = byteStart; i < byteEnd; ++i) {
        count += count(bits[i]);
    }

    for (int i = start, n = byteStart*Byte.SIZE; i < n; ++i) {
        if (get(bits, i)) {
            ++count;
        }
    }
    for (int i = byteEnd*8; i < end; ++i) {
        if (get(bits, i)) {
            ++count;
        }
    }

    return count;
}
```

*BitsTest.java*

```java
@DataProvider
public Object[][] bitsCountRanges() {
    final var random = new Random(1234);

    final List<Object[]> values = new ArrayList<>();
    values.add(new Object[]{1, 0, 5});
    values.add(new Object[]{1, 0, 7});
    values.add(new Object[]{1, 0, 8});
    values.add(new Object[]{1, 1, 8});
    values.add(new Object[]{2, 8, 10});

    for (int i = 0; i < 100; ++i) {
        final int length = random.nextInt(1, 100);
        final int start = random.nextInt(length*Byte.SIZE);
        final int end = random.nextInt(start, length*Byte.SIZE) + 1;

        values.add(new Object[]{length, start, end});
    }

    return values.toArray(new Object[0][]);
}
```

**Comment by akornienko** [comment]
great, thank you.
We are exploring an option to use jenetics in our project. In our case evaluation of the objective function happens on remote machine (due to complex calculations). Is there any chance to develop an engine that decouples steps in evolve? sort of init, getNextPopulation, getNextResult

**Comment by jenetics** [comment]
You might want to have a look at the [Evolution](https://www.javadoc.io/doc/io.jenetics/jenetics/latest/io.jenetics.base/io/jenetics/engine/Evolution.html) interface and the [EvolutionStream.ofEvolution](https://www.javadoc.io/doc/io.jenetics/jenetics/latest/io.jenetics.base/io/jenetics/engine/EvolutionStream.html#ofEvolution(java.util.function.Supplier,io.jenetics.engine.Evolution)) factory method. This should do the trick. There is also an example in the linked Javadoc.

**Comment by jenetics** [comment]
Merged into r7.1.1.
