### ISSUE TITLE
Random interger value from permutation

### ISSUE THREAD

**Issue by zealrant** [jenetics/jenetics#85]
Hi, I wonder if Jenetic support random integer value from permutation.

It means, I want to get 6 random integer from 0 to 52 and anything doesn't same each other. Like lottery.

I read "EnumGene<Integer>" and "codecs.ofPermutation" part of manual. However, random "Integer" type allow the same number like "11, 11, 12". And "permutation" type is limited by length like [0,length).

So.. Is this type supported in Jenetic?

**Comment by jenetics** [comment]
You are right, the required feature is currently missing in the `PermutationChromosome`. I will add the missing factory method, `PermutationChromosome.ofInteger(IntRange, int)`, for the next release. As a workaround, you can use the following `Codec`:
```java
final Codec<ISeq<Integer>, EnumGene<Integer>> codec = Codec.of(
	Genotype.of(PermutationChromosome.ofInteger(52)),
	gt -> gt.getChromosome().stream().limit(6)
			.map(EnumGene::getAllele)
			.collect(ISeq.toISeq())
);
```

**Comment by jenetics** [comment]
PR: https://github.com/jenetics/jenetics/pull/86

**Comment by jenetics** [comment]
Fix has been merged into r3.4.0.

**Comment by shiddiqeuy** [comment]
nice
