### ISSUE TITLE
Can't run ./jrun io.jenetics.example.image.EvolvingImages on windows

### ISSUE THREAD

**Issue by roma2341** [jenetics/jenetics#868]
Error: Could not find or load main class io.jenetics.example.image.EvolvingImages
Caused by: java.lang.ClassNotFoundException: io.jenetics.example.image.EvolvingImages
So i had to use IDE to be able to run it.

**Comment by jenetics** [comment]
You must first build the library.
```
> ./gradlew jar
> ./jrun io.jenetics.example.image.EvolvingImages
```
Than it will work.

**Comment by roma2341** [comment]
No, it doesn't
![image](https://github.com/jenetics/jenetics/assets/7004017/59c6f20e-68bc-40a1-934d-f0b92b8da2fe)

**Comment by jenetics** [comment]
The Windows version of the script uses the wrong paths.
```
set CLASSPATH=.
for %%m in %MODULES% do (
	set CLASSPATH=!CLASSPATH!;%%m\build\classes\java\main
	set CLASSPATH=!CLASSPATH!;%%m\build\resources\java\main
	set CLASSPATH=!CLASSPATH!;%%m\build\classes\java\test
	set CLASSPATH=!CLASSPATH!;%%m\build\resources\java\test
)
```

You might want to create a PR if this works.

**Comment by roma2341** [comment]
![image](https://github.com/jenetics/jenetics/assets/7004017/cf54fa8d-c2c1-4e94-ab7a-6e7f1a9e486c)
Replaced CLASSPATH in script and got this

**Comment by jenetics** [comment]
Fixed the paths in the script. My initial fix was not correct. The correct paths would be
```
set CLASSPATH=.
for %%m in %MODULES% do (
	set CLASSPATH=!CLASSPATH!;%%m\build\classes\java\main
	set CLASSPATH=!CLASSPATH!;%%m\build\resources\main
	set CLASSPATH=!CLASSPATH!;%%m\build\classes\java\test
	set CLASSPATH=!CLASSPATH!;%%m\build\resources\test
)
```

**Comment by jenetics** [comment]
Merged into r7.2.0.
