### ISSUE TITLE
Question: How to build a custom limit Predicate?

### ISSUE THREAD

**Issue by wolfig** [jenetics/jenetics#882]
I'd like to experiment with my own limit Predicate. How would I implement an own one? I see that the "Limit" class is final. Could you help me with some code lines how to achieve what I want?

Thanks and kind regards
Wolfgang

**Comment by jenetics** [comment]
The `Limits` class is just a collection of pre-defined implementations. Your own limit-predicate don't need to be part of it. You can implement whereever you want. Technically, there are two different ways on how to implement your _limiter_:
1) **Method**
You can implement it as static method with the proper signature. 

It is assumed, that you write the limit-predicate with a `DoubleGene` and a `double` fitness-value. This depends on your encoding.
```java
final class MyLimits {
    static boolean myCriteria(EvolutionResult<DoubleGene, Double> result) { 
        // You the properties the actuall result, for deciding
        // whether you want to proceed or not.
        return ...;
    }
}

var result = Engine.builder(...).build()
    .limit(MyLimits::myCriteria)
    .collect(...);
```
With this method, the decision of whether to proceed the evolution, only depends on the current result.

2) **Class**
If your decission of proceeding the evolution, needs previous results, you need to implement a class which can store previous results.

```java
class MyLimit implements Predicate<EvolutionResult<DoubleGene, Double>> {
    private EvolutionResult<DoubleGene, Double> lastResult;

    @Override
    public boolean test(EvolutionResult<DoubleGene, Double> result) {
        if (/*lastResult*/) {
            ... // Do something with your last result.
        }
        // Remember the last result.
        lastResult = result;

       return ...:
    }
}

var result = Engine.builder(...).build()
    .limit(new MyLimit(/*Maybe some limit parameters*/))
    .collect(...);
```

I hope this will give you an idea on how to implement limits.
