### ISSUE TITLE
Multiple constraint support

### ISSUE THREAD

**Issue by Rojods** [jenetics/jenetics#892]
First issue here! So let me start with the mandatory... thank you! This framework and library is some nice piece of work :).

Now I can go to my issue (possibly and hopefully an oversight on my side).
How can one properly specify multiple constraints with Jenetics? By this question, I do mean with `Engine`?
I took a quick look in the source code for the builder and the engine itself (and naturally also in the user guide) and it does seem to support only **one** constraint. As I will comment below, this is not a "big big" deal, but it is unexpected as the MOEA section of the user guide specifically shows multiple constraints as the target mathematical model, although the examples always use only one constraint :D.

Currently, I am working around it by defining my own "aggregate" constraint like:
```
public class MultiConstraint<A, G extends Gene<A, G>, T extends Comparable<? super T>> implements Constraint<G, T> {

    List<Constraint<G, T>> constraints = new ArrayList<>();

    public MultiConstraint(Constraint<G, T>... constraints) {
        for (Constraint<G, T> c : constraints) {
            this.constraints.add(c);
        }
    }

    @Override
    public boolean test(Phenotype<G, T> individual) {
        for (Constraint<G, T> c : constraints) {
            if (!c.test(individual)) {
                return false;
            }
        }
        return true;
    }

    @Override
    public Phenotype<G, T> repair(Phenotype<G, T> individual, long generation) {
        var repaired = individual;
        for (Constraint<G, T> c : constraints) {
            if (!c.test(repaired)) {
                repaired = c.repair(repaired, generation);
            }
        }
        return repaired;
    }

}
```

which gets the job done but is certainly not the most efficient way to approach the problem, since it requires *re-checking* the valid conditions for an individual in order to make sure that we can apply the repair algorithm.

So, did I miss something? Or does the engine currently lack multi-constraint handling as I guessed it does?
If it is the case that multi-constraint is indeed not implemented, I am happy to provide this snippet of code and maybe a bit more to help make it a reality :).

**Comment by jenetics** [comment]
Hi!

You are right, Jenetics only supports one constraint and your approach is the one to handle this _restriction_. I think, that supporting multiple constraints isn't also not straight forward. How does the different constraints play together? Are they distinct? What to do, if you have overlapping constraints? Does the order of the _check_ and _repair_ calls matter? For me, it wasn't that clear how to handle all the cases. So I deliberatily restricted the library to _only_ one constraint.

I still don't know what the correct constraint model should be implemented. How does MOEA handle it's constraints? 

lg
Franz

**Comment by Rojods** [comment]
Hi Franz!

Thanks for the detailed answer :). I think it is only fair that I answer with equal details and suggestions.

When I first read your answer, I could not figure out what the problem was with the overlapping constraints, their order of execution etc because I was too biased with normal exact algorithms (any branch-and-bound  variant!) and thought: "Well, the order should not matter nor the overlap!", until I realized that in MOEA we gotta literally fix the individuals and this can even fail.

For the moment I keep on going with my "super constraint". Here are my two cents about it in case it is helpful :). 

Unless I misunderstand, Jenetics for now treats all constraints equally, right? A priori this might sound OK, but given how MOEA has to handle constraints, I think a small distinction would be super helpful. Say, constraints can be separated in three categories:
1. Idempotent with no "constraint dependencies" (guaranteed problem-specific no overlap);
2. Idempotent with "constraint dependencies" (guaranteed problem-specific overlap);
3. Non idempotent, black-box. Can fail, can succeed, who knows? We can only check if it is valid or not.

It seems to me that for now we treat all of them as 3, so in the user has to figure out how to put the constraints together. 
But my use case has exactly a mix of these 3, so unless we can find a missing category here, it is a illustrative case!

My use case has a lot to do with job scheduling with a better model of the machines hosting the jobs. I have 3 actually three constraints, one in each category:
1. Allocate certain resources between machines when dependent jobs are mapped between them (problem-specific: always succeeds and needs to be executed only once, so idempotent of 1).
2. Re-order the jobs when the mapping changes in topological order in every machine. (problem-specific: always succeeds and needs to be executed only once _if the mapping is feasible_, so idempotent of 1).
3. Re-map if necessary because a machine has overflow with job consumption. (Non-idempotent: this is basically a bin-packing problem embedded in the use-case, so solving for every individual it is a no-go; I rely on random re-mapping).

In this situation, multiple constraints could be achieved by executing the non-idempotent constraint(s) up to a certain limit and safely executing the idempotent ones _in the right order_ right after. So if we would keep a sort of "constraint graph" for the idempotent ones, and the user guarantees that in their problem the constraint are idempotent, I think Jenetics could _possibly_ safely constraint following a topological iteration on this "constraint graph".

This is a long-shot, of course; but it does not seem to be so insanely far from how constraint programming see their problems, for example. They have an advantage because they can fail the entire search tree, while Jenetics has nothing to fail :). 
On this topic, maybe some constraints could restrict the domain in which the chromosomes take values from? But this would mean that the Genes in a Chromossomes can have different minimum and maximum values, which I already discovered is not allowed :D.

Best,
Rodolfo

**Comment by jenetics** [comment]
Hi Rodolfo!

I think your analysis is quite accurate. Jenetics tries to keep things simple, and therefore treats a constraint like a black box. The user knows best, hopefully, how to handle them.

Constraint Satisfaction Problems [(CSP)](https://en.wikipedia.org/wiki/Constraint_satisfaction_problem) are quite interesting, and I refreshed my knowledge about it lately. After that, I was sure, that Jenetics made the right choice. ;-)  I wouldn't rule out to add a more advanced constraint handling in the future. But this would be a bigger project.

If you have some ideas (and implementations) you are welcome to open a PR. :D

lg
Franz
