### ISSUE TITLE
Shift Mutation, Arbitrary Mutation and Uniform Order Based Crossover

### ISSUE THREAD

**Issue by paul2803-byte** [jenetics/jenetics#894]
Shift Mutation: Two points on the chromosome are selected randomly. Within these points a third point is selected. The genes between the second and the third point are shifted before the first point.

Arbitrary Mutation: Two points on the chromosome are selected randomly. The order of the genes between those points is changed randomly.

Uniform Order Based Crossover: A list of positions is selected randomly (size = half chromosome size). The genes at this positions are reordered as they occur in the other parent. 

For the Mutations two versions were pulled. One selects the points randomly without considering p. The second version implements a mechanism to change p percent of the genes. Hereby the gap between the selected point is chosen based on a random values that got adjusted to have an expectancy value of p.  

For more detailed description of the genetic operations see: Kruse, R., Mostaghim, S., Borgelt, C., Braune, C., & Steinbrecher, M. (2022). Elements of evolutionary algorithms. In Computational Intelligence: A Methodological Introduction (pp. 255-285). Cham: Springer International Publishing.

**Comment by jenetics** [comment]
Merged into r8.0.0.

**Comment by jenetics** [comment]
Hi @paul2803-byte,

I'm currently prepare the library for the next version and try to describe your mutators in the manual. The Javadoc of the _*WithK_ mutators states, the the expected value of the changed genes is _p_. While this is correct (I did some tests), the actual distribution of the `getDistance` method is still not clear. Can you tell me the source of the implemented algorithm and the name of the distribution, this method creates?

Thanks
Franz
