### ISSUE TITLE
Improve default RandomGenerator selection

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#895]
On some JVMs the chosen _default_ `RandomGenerator` is not available, although it is required for valid Java SE platforms. When setting the default generator it should be checked if this generator is available on the current platform.

See #866

**Comment by jenetics** [comment]
Merged into r8.0.0.

**Comment by sfeilmeier** [comment]
Thank you for solving this so quickly. I wanted to take the time to work on this today - only to find that you already fixed it. 🙏
