### ISSUE TITLE
Java 8 problem?

### ISSUE THREAD

**Issue by lfbrito** [jenetics/jenetics#9]
Hi,
I am a bit rusty with Java... but I really can't figure out something that might be very simple...
When I try to use on Eclipse your HelloWorldExample I keep getting a compilation error on this:
        // 3.) Create the execution environment.
        Engine<BitGene, Integer> engine = Engine
            .builder(HelloWorld::eval, gtf)
            .build();

I get:

Exception in thread "main" java.lang.Error: Unresolved compilation problems: 
	The method builder(Function<? super Genotype<G>,? extends C>, Factory<Genotype<G>>) in the type Engine is not applicable for the arguments (HelloWorld::eval, Factory<Genotype<BitGene>>)
	The type HelloWorld does not define eval(Genotype<G>) that is applicable here

	at HelloWorld.main(HelloWorld.java:22)

Any pointers???

**Comment by jenetics** [comment]
Sorry, but It seems that ecplise has problems with (valid) lambda expressions. Also have a look at #6 .

My advice is to use IntelliJ instead.

**Comment by lfbrito** [comment]
Thanks. I thought it could be that.

**Comment by bskaggs** [comment]
I got it working in Eclipse Luna with an explicit cast:

    Engine<BitGene, Integer> engine = 
        Engine.builder((Function<Genotype<BitGene>, Integer>) HelloWorld::eval, gtf).build();`
