### ISSUE TITLE
Need help with creating a genotype

### ISSUE THREAD

**Issue by imaginaryfriend0** [jenetics/jenetics#901]
Hi there,

First of all, thanks for creating Jenetics! Helps a lot with my project!

I have a problem I've been trying to solve last couple of hours with no luck.

Basically, I need to execute evolution process of genotype that consists of 'n' (input by user) Int genes and one Double gene, so total length of chromosome is n+1.

Each Int gene has to have its own range of values (for example, first one is (0,30), second (10,40) etc.), and a Double one has its own range too.

Tried modifying 'MixedGenotype.java', but couldn't figure out how to handle 'dynamic' quantity of genes.

Is it possible to do so?
Thanks!

**Comment by jenetics** [comment]
Hi @imaginaryfriend0,

For this kind of problems, I recommend to use a `DoubleChromosome` of length n + 1 with values in the range [0, 1). When converting the `Genotype` into a instance of your problem space, you can do the needed scaling.

```java
record Ranges(int[] ivalues, double dvalue) {
}

static Codec<Ranges, DoubleGene> codec(IntRange[] iranges, DoubleRange drange) {
    return Codec.of(
        Genotype.of(DoubleChromosome.of(DoubleRange.of(0, 1), iranges.length + 1)),
        gt -> {
            final var ch = gt.chromosome();
            return new Ranges(
                IntStream.range(0, iranges.length)
                    .map(i -> (int)(ch.get(i).doubleValue()*iranges[i].size()) + iranges[i].min())
                    .toArray(),
                ch.get(iranges.length).doubleValue()*(drange.max() - drange.min()) + drange.min()
            );
        }
    );
}
```

Regards
Franz

**Comment by imaginaryfriend0** [comment]
Thank you for a quick reply!
I copied your code to my project, but now having a "Cannot resolve method 'builder(<method reference>, Codec<Ranges, DoubleGene>)'" error in the engine method, any clue what could be the problem here?

`        intRanges = new IntRange[length];
        for (int i = 0; i < length; i++){
            intRanges[i] = IntRange.of(min[i],max[i]);
        }
        doubleRange = DoubleRange.of(0,creditPos);`
        
        `public static double[] RunEvolution(){
        final Engine<DoubleGene, Double> engine = Engine
                .builder(EvolutionAlgorithm::fitness, codec(intRanges,doubleRange))
                .populationSize(1000)
                .selector(new TournamentSelector<>())
                .optimize(Optimize.MAXIMUM)
                .alterers(
                        new Mutator<>(0.05),
                        new MultiPointCrossover<>(0.6)
                )
                .build();
        final EvolutionStatistics<Double,?>
                statistics = EvolutionStatistics.ofNumber();

        final Phenotype <DoubleGene,Double> best = engine.stream()
                .limit(bySteadyFitness(30))
                .peek(statistics)
                .collect(toBestPhenotype());
        return best.genotype().chromosome().stream().mapToDouble(DoubleGene::allele).toArray();
    }

    record Ranges(int[] ivalues, double dvalue) {
    }

    static Codec<Ranges, DoubleGene> codec(IntRange[] iranges, DoubleRange drange) {
        return Codec.of(
                Genotype.of(DoubleChromosome.of(DoubleRange.of(0, 1), iranges.length + 1)),
                gt -> {
                    final var ch = gt.chromosome();
                    return new Ranges(
                            IntStream.range(0, iranges.length)
                                    .map(i -> (int)(ch.get(i).doubleValue()*iranges[i].size()) + iranges[i].min())
                                    .toArray(),
                            ch.get(iranges.length).doubleValue()*(drange.max() - drange.min()) + drange.min()
                    );
                }
        );
    }`

**Comment by imaginaryfriend0** [comment]
Everything works great now! Thanks a lot!
