### ISSUE TITLE
Missing DieHarder Wrapper

### ISSUE THREAD

**Issue by H-K-47** [jenetics/jenetics#902]
I came from this post https://medium.com/@jeneticsga/creating-random-seeds-with-java-3df09bd02188

while the DieHarder results are still in the repo the Wrapper isn't https://github.com/jenetics/jenetics/blob/master/org.jenetics/src/main/java/org/jenetics/internal/util/DieHarder.java

I searched in older Branches but did not have any luck either.

Care to publish it again?

Thanks

**Comment by jenetics** [comment]
High @H-K-47, a little bit late :),

but this class is now available in the [prngine](https://github.com/jenetics/prngine) project:

https://github.com/jenetics/prngine/blob/master/prngine/src/main/java/io/jenetics/prngine/internal/DieHarder.java
