### ISSUE TITLE
Update to Gradle 8.10

### ISSUE THREAD

**Issue by jenetics** [jenetics/jenetics#904]
Gradle should be update to the newest version.

**Comment by jenetics** [comment]
Merged into 8.1.0.

**Comment by R3TRO04** [comment]
Gradle recommends to use 8.10.1 instead of 8.10. 
https://github.com/gradle/gradle/releases/tag/v8.10.1

**Comment by jenetics** [comment]
> Gradle recommends to use 8.10.1 instead of 8.10. https://github.com/gradle/gradle/releases/tag/v8.10.1

Till the next release, I can update it to version 9.0, I guess :)
