### ISSUE TITLE
Real Function example in the user manual not compiled 

### ISSUE THREAD

**Issue by Richard-zhang** [jenetics/jenetics#92]
The "Real Function example in the user manual" seems doesn't compile. The fitness function seems to take final double type as parameter type instead of final Genotype<DoubleGene> which is shown in the example. 

Also, could you give me an example how to support multi-variable optimize, for example, to minimize a two-dimensional map.

**Comment by jenetics** [comment]
Thank you, you are right. For some reason I didn't fully converting the example when I introduced the [Codec](https://github.com/jenetics/jenetics/blob/master/org.jenetics/src/main/java/org/jenetics/engine/Codec.java) interface. The fully compiling and working example is also available here: [RealFunction](https://github.com/jenetics/jenetics/blob/master/org.jenetics.example/src/main/java/org/jenetics/example/RealFunction.java)

Here is an adapted version of the `RealFunction` example for 2D.
```java
import static java.lang.Math.PI;
import static java.lang.Math.cos;
import static java.lang.Math.sin;
import static org.jenetics.engine.EvolutionResult.toBestPhenotype;
import static org.jenetics.engine.limit.bySteadyFitness;

import org.jenetics.DoubleGene;
import org.jenetics.Phenotype;
import org.jenetics.engine.Engine;
import org.jenetics.engine.codecs;
import org.jenetics.util.DoubleRange;

public class Real2DFunction {
    private static double fitness(final double[] x) {
        return cos(0.5 + sin(x[0]))*cos(x[1]);
    }

    public static void main(final String[] args) {
        final Engine<DoubleGene, Double> engine = Engine
            .builder(
                Real2DFunction::fitness,
                codecs.ofVector(DoubleRange.of(0.0, 2.0*PI), 2))
            .build();

        final Phenotype<DoubleGene, Double> best = engine.stream()
            .limit(bySteadyFitness(7))
            .collect(toBestPhenotype());

        System.out.println(best);
    }
}
```

In this example the two dimensions have the same range of [0, 2PI]. If you need different ranges for each dimension, use the [codec.ofVector(DoubleRange...)](http://jenetics.io/javadoc/org.jenetics/org/jenetics/engine/codecs.html#ofVector-org.jenetics.util.DoubleRange...-) codec.

**Comment by jenetics** [comment]
The examples sources are compiled before the manual is created. This guarantees the validity of the examples.

Has been merged into release branch r3.5.0.
